#!/usr/bin/env python3
"""Classify every source change between each old test file and its new module.

Acceptance 5 review aid. For every module in the four `*-migration.json`
manifests, it diffs the old file at the package's unmigrated base revision
with the new module at `HEAD`. It sorts each changed line into three kinds:

- `structural`: a spec §3 edit (inner or outer attribute, `mod`, `use`,
  `#[path]`, a blank line, or a line that differs only by `crate::` vs
  `super::`),
- `comment`: a `//` comment line,
- `other`: anything else. These lines are listed in full for a reviewer.

A nested root compares only its root file (`main.rs` to `mod.rs`); its
children moved as whole files and are counted, not diffed.

The `HEAD` side includes later, documented edits (for example the Phase 7
failure-message fixes), so an `other` line is a review item, not a verdict.

Usage: body-diff.py [--markdown FILE]. Exits 0; the report is the output.
"""

import argparse
import difflib
import json
import pathlib
import re
import subprocess

FEATURE_DIR = pathlib.Path(__file__).resolve().parent.parent
REPO_ROOT = FEATURE_DIR.parent.parent
PACKAGES = [
    ("claudine-cli-migration.json", "9621882ae"),
    ("darkmatter-migration.json", "048e44f7a"),
    ("darkmatter-cli-migration.json", "cb9a3d38b"),
    ("biscuit-terminal-migration.json", "beca6c368"),
]
STRUCTURAL = re.compile(
    r"""^(
        \#!?\[.*\]\s*$            # attribute on one line
      | (pub(\(crate\))?\s+)?mod\s+\w+\s*;   # module declaration
      | (pub(\(crate\))?\s+)?use\s        # import
      | [\w:{}*,\s]*\}?\s*;?\s*$          # continuation of a multi-line use
    )""",
    re.VERBOSE,
)


def git_show(revision, path):
    result = subprocess.run(
        ["git", "show", f"{revision}:{path}"], cwd=REPO_ROOT, capture_output=True, text=True
    )
    return result.stdout.splitlines() if result.returncode == 0 else None


def classify(line):
    stripped = line.strip()
    if not stripped or STRUCTURAL.match(stripped):
        return "structural"
    if stripped.startswith("//"):
        return "comment"
    return "other"


def normalize(line):
    return line.replace("super::", "crate::").rstrip()


def diff_module(before, after):
    counts = {"structural": 0, "comment": 0, "other": 0}
    others = []
    matcher = difflib.SequenceMatcher(
        a=[normalize(line) for line in before], b=[normalize(line) for line in after], autojunk=False
    )
    for tag, a0, a1, b0, b1 in matcher.get_opcodes():
        if tag == "equal":
            continue
        for sign, lines in (("-", before[a0:a1]), ("+", after[b0:b1])):
            for line in lines:
                kind = classify(line)
                counts[kind] += 1
                if kind == "other":
                    others.append(f"{sign} {line.strip()}")
    return counts, others


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--markdown", type=pathlib.Path)
    args = parser.parse_args()

    report = ["# Acceptance 5: source changes by kind", "",
              "Generated by `acceptance/body-diff.py`. Old file at the package's base",
              "revision against the new module at `HEAD`. See the script header for the",
              "classification rules.", ""]
    summary = ["| Package | Base | Modules | Byte-identical | Structural lines | Comment lines | Other lines | Modules with other lines |",
               "|---|---|---:|---:|---:|---:|---:|---:|"]
    details = []
    for file_name, base in PACKAGES:
        manifest = json.loads((FEATURE_DIR / file_name).read_text())
        totals = {"structural": 0, "comment": 0, "other": 0}
        identical = 0
        flagged = 0
        for module in manifest["modules"]:
            before = git_show(base, module["old_path"])
            after = git_show("HEAD", module["new_path"])
            if before is None or after is None:
                details.append(f"- `{module['old_path']}`: missing on one side (before={before is not None}, after={after is not None})")
                flagged += 1
                continue
            if before == after:
                identical += 1
                continue
            counts, others = diff_module(before, after)
            for kind, count in counts.items():
                totals[kind] += count
            if others:
                flagged += 1
                details.append(f"### `{manifest['package']}`: `{module['old_path']}` → `{module['new_path']}`")
                details.append("")
                details.append("```diff")
                details.extend(others)
                details.append("```")
                details.append("")
        summary.append(
            f"| `{manifest['package']}` | `{base}` | {len(manifest['modules'])} | {identical} | "
            f"{totals['structural']} | {totals['comment']} | {totals['other']} | {flagged} |"
        )
    report.extend(summary)
    report.extend(["", "## Other lines, by module", ""])
    report.extend(details or ["None."])
    text = "\n".join(report) + "\n"
    if args.markdown:
        args.markdown.write_text(text)
    print("\n".join(summary))


if __name__ == "__main__":
    main()
