use serde::{Deserialize, Serialize};

use super::{BasicColor, HdrColor};

/// Tailwind CSS color palette.
///
/// This enum provides access to the complete Tailwind CSS color scale,
/// from `50` (lightest) through `950` (darkest) for each color family.
///
/// ## Color Families
///
/// Each color family (Red, Orange, Amber, Yellow, Lime, Green, Emerald,
/// Teal, Cyan, Sky, Blue, Indigo, Violet, Purple, Fuchsia, Pink, Rose,
/// Slate, Gray, Zinc, Neutral) has shades from 50 to 950, plus special
/// values: `Inherit`, `Current`, `Transparent`, `Black`, `White`.
///
/// ## Examples
///
/// ```
/// use renderable::color::Tailwind;
///
/// // Access specific colors from the palette
/// let primary = Tailwind::Blue500;
/// let light_bg = Tailwind::Slate50;
/// let dark_text = Tailwind::Gray900;
///
/// // Common special values
/// let transparent = Tailwind::Transparent;
/// let black = Tailwind::Black;
/// let white = Tailwind::White;
///
/// // Color intensity scales (50 = lightest, 950 = darkest)
/// let red_light = Tailwind::Red200;
/// let red_main = Tailwind::Red500;
/// let red_dark = Tailwind::Red800;
/// ```
///
/// ## Usage with RgbColor
///
/// Convert to RGB for terminal rendering:
///
/// ```
/// use renderable::color::{Color, Tailwind};
///
/// let color = Color::Tailwind(Tailwind::Emerald600);
/// if let Some((r, g, b)) = color.to_rgb() {
///     println!("R: {}, G: {}, B: {}", r, g, b);
/// }
/// ```
///
/// ## Notes
///
/// The palette follows the official Tailwind CSS color values.
/// Shades are designed for both light and dark backgrounds:
/// - 50-200: Light backgrounds, subtle highlights
/// - 300-500: Primary interactive elements
/// - 600-700: Active states, emphasis
/// - 800-950: Dark backgrounds, heavy text
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Tailwind {
    // “specials” commonly present in Tailwind palettes
    Inherit,
    Current,
    Transparent,
    Black,
    White,

    // Red
    Red50,
    Red100,
    Red200,
    Red300,
    Red400,
    Red500,
    Red600,
    Red700,
    Red800,
    Red900,
    Red950,
    // Orange
    Orange50,
    Orange100,
    Orange200,
    Orange300,
    Orange400,
    Orange500,
    Orange600,
    Orange700,
    Orange800,
    Orange900,
    Orange950,
    // Amber
    Amber50,
    Amber100,
    Amber200,
    Amber300,
    Amber400,
    Amber500,
    Amber600,
    Amber700,
    Amber800,
    Amber900,
    Amber950,
    // Yellow
    Yellow50,
    Yellow100,
    Yellow200,
    Yellow300,
    Yellow400,
    Yellow500,
    Yellow600,
    Yellow700,
    Yellow800,
    Yellow900,
    Yellow950,
    // Lime
    Lime50,
    Lime100,
    Lime200,
    Lime300,
    Lime400,
    Lime500,
    Lime600,
    Lime700,
    Lime800,
    Lime900,
    Lime950,
    // Green
    Green50,
    Green100,
    Green200,
    Green300,
    Green400,
    Green500,
    Green600,
    Green700,
    Green800,
    Green900,
    Green950,
    // Emerald
    Emerald50,
    Emerald100,
    Emerald200,
    Emerald300,
    Emerald400,
    Emerald500,
    Emerald600,
    Emerald700,
    Emerald800,
    Emerald900,
    Emerald950,
    // Teal
    Teal50,
    Teal100,
    Teal200,
    Teal300,
    Teal400,
    Teal500,
    Teal600,
    Teal700,
    Teal800,
    Teal900,
    Teal950,
    // Cyan
    Cyan50,
    Cyan100,
    Cyan200,
    Cyan300,
    Cyan400,
    Cyan500,
    Cyan600,
    Cyan700,
    Cyan800,
    Cyan900,
    Cyan950,
    // Sky
    Sky50,
    Sky100,
    Sky200,
    Sky300,
    Sky400,
    Sky500,
    Sky600,
    Sky700,
    Sky800,
    Sky900,
    Sky950,
    // Blue
    Blue50,
    Blue100,
    Blue200,
    Blue300,
    Blue400,
    Blue500,
    Blue600,
    Blue700,
    Blue800,
    Blue900,
    Blue950,
    // Indigo
    Indigo50,
    Indigo100,
    Indigo200,
    Indigo300,
    Indigo400,
    Indigo500,
    Indigo600,
    Indigo700,
    Indigo800,
    Indigo900,
    Indigo950,
    // Violet
    Violet50,
    Violet100,
    Violet200,
    Violet300,
    Violet400,
    Violet500,
    Violet600,
    Violet700,
    Violet800,
    Violet900,
    Violet950,
    // Purple
    Purple50,
    Purple100,
    Purple200,
    Purple300,
    Purple400,
    Purple500,
    Purple600,
    Purple700,
    Purple800,
    Purple900,
    Purple950,
    // Fuchsia
    Fuchsia50,
    Fuchsia100,
    Fuchsia200,
    Fuchsia300,
    Fuchsia400,
    Fuchsia500,
    Fuchsia600,
    Fuchsia700,
    Fuchsia800,
    Fuchsia900,
    Fuchsia950,
    // Pink
    Pink50,
    Pink100,
    Pink200,
    Pink300,
    Pink400,
    Pink500,
    Pink600,
    Pink700,
    Pink800,
    Pink900,
    Pink950,
    // Rose
    Rose50,
    Rose100,
    Rose200,
    Rose300,
    Rose400,
    Rose500,
    Rose600,
    Rose700,
    Rose800,
    Rose900,
    Rose950,

    // Slate
    Slate50,
    Slate100,
    Slate200,
    Slate300,
    Slate400,
    Slate500,
    Slate600,
    Slate700,
    Slate800,
    Slate900,
    Slate950,
    // Gray
    Gray50,
    Gray100,
    Gray200,
    Gray300,
    Gray400,
    Gray500,
    Gray600,
    Gray700,
    Gray800,
    Gray900,
    Gray950,
    // Zinc
    Zinc50,
    Zinc100,
    Zinc200,
    Zinc300,
    Zinc400,
    Zinc500,
    Zinc600,
    Zinc700,
    Zinc800,
    Zinc900,
    Zinc950,
    // Neutral
    Neutral50,
    Neutral100,
    Neutral200,
    Neutral300,
    Neutral400,
    Neutral500,
    Neutral600,
    Neutral700,
    Neutral800,
    Neutral900,
    Neutral950,
    // Stone
    Stone50,
    Stone100,
    Stone200,
    Stone300,
    Stone400,
    Stone500,
    Stone600,
    Stone700,
    Stone800,
    Stone900,
    Stone950,
}

// Generated Tailwind color implementations from build.rs
// Provides: to_hdr_color(), css_var(), hex(), kebab_name(), from_kebab_name(), palette_defaults()
include!(concat!(env!("OUT_DIR"), "/tailwind_colors.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_kebab_name_round_trips_every_palette_entry() {
        let all = [
            Tailwind::Inherit,
            Tailwind::Current,
            Tailwind::Transparent,
            Tailwind::Black,
            Tailwind::White,
            Tailwind::Red50,
            Tailwind::Red100,
            Tailwind::Red200,
            Tailwind::Red300,
            Tailwind::Red400,
            Tailwind::Red500,
            Tailwind::Red600,
            Tailwind::Red700,
            Tailwind::Red800,
            Tailwind::Red900,
            Tailwind::Red950,
            Tailwind::Orange50,
            Tailwind::Orange100,
            Tailwind::Orange200,
            Tailwind::Orange300,
            Tailwind::Orange400,
            Tailwind::Orange500,
            Tailwind::Orange600,
            Tailwind::Orange700,
            Tailwind::Orange800,
            Tailwind::Orange900,
            Tailwind::Orange950,
            Tailwind::Amber50,
            Tailwind::Amber100,
            Tailwind::Amber200,
            Tailwind::Amber300,
            Tailwind::Amber400,
            Tailwind::Amber500,
            Tailwind::Amber600,
            Tailwind::Amber700,
            Tailwind::Amber800,
            Tailwind::Amber900,
            Tailwind::Amber950,
            Tailwind::Yellow50,
            Tailwind::Yellow100,
            Tailwind::Yellow200,
            Tailwind::Yellow300,
            Tailwind::Yellow400,
            Tailwind::Yellow500,
            Tailwind::Yellow600,
            Tailwind::Yellow700,
            Tailwind::Yellow800,
            Tailwind::Yellow900,
            Tailwind::Yellow950,
            Tailwind::Lime50,
            Tailwind::Lime100,
            Tailwind::Lime200,
            Tailwind::Lime300,
            Tailwind::Lime400,
            Tailwind::Lime500,
            Tailwind::Lime600,
            Tailwind::Lime700,
            Tailwind::Lime800,
            Tailwind::Lime900,
            Tailwind::Lime950,
            Tailwind::Green50,
            Tailwind::Green100,
            Tailwind::Green200,
            Tailwind::Green300,
            Tailwind::Green400,
            Tailwind::Green500,
            Tailwind::Green600,
            Tailwind::Green700,
            Tailwind::Green800,
            Tailwind::Green900,
            Tailwind::Green950,
            Tailwind::Emerald50,
            Tailwind::Emerald100,
            Tailwind::Emerald200,
            Tailwind::Emerald300,
            Tailwind::Emerald400,
            Tailwind::Emerald500,
            Tailwind::Emerald600,
            Tailwind::Emerald700,
            Tailwind::Emerald800,
            Tailwind::Emerald900,
            Tailwind::Emerald950,
            Tailwind::Teal50,
            Tailwind::Teal100,
            Tailwind::Teal200,
            Tailwind::Teal300,
            Tailwind::Teal400,
            Tailwind::Teal500,
            Tailwind::Teal600,
            Tailwind::Teal700,
            Tailwind::Teal800,
            Tailwind::Teal900,
            Tailwind::Teal950,
            Tailwind::Cyan50,
            Tailwind::Cyan100,
            Tailwind::Cyan200,
            Tailwind::Cyan300,
            Tailwind::Cyan400,
            Tailwind::Cyan500,
            Tailwind::Cyan600,
            Tailwind::Cyan700,
            Tailwind::Cyan800,
            Tailwind::Cyan900,
            Tailwind::Cyan950,
            Tailwind::Sky50,
            Tailwind::Sky100,
            Tailwind::Sky200,
            Tailwind::Sky300,
            Tailwind::Sky400,
            Tailwind::Sky500,
            Tailwind::Sky600,
            Tailwind::Sky700,
            Tailwind::Sky800,
            Tailwind::Sky900,
            Tailwind::Sky950,
            Tailwind::Blue50,
            Tailwind::Blue100,
            Tailwind::Blue200,
            Tailwind::Blue300,
            Tailwind::Blue400,
            Tailwind::Blue500,
            Tailwind::Blue600,
            Tailwind::Blue700,
            Tailwind::Blue800,
            Tailwind::Blue900,
            Tailwind::Blue950,
            Tailwind::Indigo50,
            Tailwind::Indigo100,
            Tailwind::Indigo200,
            Tailwind::Indigo300,
            Tailwind::Indigo400,
            Tailwind::Indigo500,
            Tailwind::Indigo600,
            Tailwind::Indigo700,
            Tailwind::Indigo800,
            Tailwind::Indigo900,
            Tailwind::Indigo950,
            Tailwind::Violet50,
            Tailwind::Violet100,
            Tailwind::Violet200,
            Tailwind::Violet300,
            Tailwind::Violet400,
            Tailwind::Violet500,
            Tailwind::Violet600,
            Tailwind::Violet700,
            Tailwind::Violet800,
            Tailwind::Violet900,
            Tailwind::Violet950,
            Tailwind::Purple50,
            Tailwind::Purple100,
            Tailwind::Purple200,
            Tailwind::Purple300,
            Tailwind::Purple400,
            Tailwind::Purple500,
            Tailwind::Purple600,
            Tailwind::Purple700,
            Tailwind::Purple800,
            Tailwind::Purple900,
            Tailwind::Purple950,
            Tailwind::Fuchsia50,
            Tailwind::Fuchsia100,
            Tailwind::Fuchsia200,
            Tailwind::Fuchsia300,
            Tailwind::Fuchsia400,
            Tailwind::Fuchsia500,
            Tailwind::Fuchsia600,
            Tailwind::Fuchsia700,
            Tailwind::Fuchsia800,
            Tailwind::Fuchsia900,
            Tailwind::Fuchsia950,
            Tailwind::Pink50,
            Tailwind::Pink100,
            Tailwind::Pink200,
            Tailwind::Pink300,
            Tailwind::Pink400,
            Tailwind::Pink500,
            Tailwind::Pink600,
            Tailwind::Pink700,
            Tailwind::Pink800,
            Tailwind::Pink900,
            Tailwind::Pink950,
            Tailwind::Rose50,
            Tailwind::Rose100,
            Tailwind::Rose200,
            Tailwind::Rose300,
            Tailwind::Rose400,
            Tailwind::Rose500,
            Tailwind::Rose600,
            Tailwind::Rose700,
            Tailwind::Rose800,
            Tailwind::Rose900,
            Tailwind::Rose950,
            Tailwind::Slate50,
            Tailwind::Slate100,
            Tailwind::Slate200,
            Tailwind::Slate300,
            Tailwind::Slate400,
            Tailwind::Slate500,
            Tailwind::Slate600,
            Tailwind::Slate700,
            Tailwind::Slate800,
            Tailwind::Slate900,
            Tailwind::Slate950,
            Tailwind::Gray50,
            Tailwind::Gray100,
            Tailwind::Gray200,
            Tailwind::Gray300,
            Tailwind::Gray400,
            Tailwind::Gray500,
            Tailwind::Gray600,
            Tailwind::Gray700,
            Tailwind::Gray800,
            Tailwind::Gray900,
            Tailwind::Gray950,
            Tailwind::Zinc50,
            Tailwind::Zinc100,
            Tailwind::Zinc200,
            Tailwind::Zinc300,
            Tailwind::Zinc400,
            Tailwind::Zinc500,
            Tailwind::Zinc600,
            Tailwind::Zinc700,
            Tailwind::Zinc800,
            Tailwind::Zinc900,
            Tailwind::Zinc950,
            Tailwind::Neutral50,
            Tailwind::Neutral100,
            Tailwind::Neutral200,
            Tailwind::Neutral300,
            Tailwind::Neutral400,
            Tailwind::Neutral500,
            Tailwind::Neutral600,
            Tailwind::Neutral700,
            Tailwind::Neutral800,
            Tailwind::Neutral900,
            Tailwind::Neutral950,
            Tailwind::Stone50,
            Tailwind::Stone100,
            Tailwind::Stone200,
            Tailwind::Stone300,
            Tailwind::Stone400,
            Tailwind::Stone500,
            Tailwind::Stone600,
            Tailwind::Stone700,
            Tailwind::Stone800,
            Tailwind::Stone900,
            Tailwind::Stone950,
        ];
        for tw in all {
            let kebab = tw.kebab_name();
            let parsed = Tailwind::from_kebab_name(kebab).expect(kebab);
            assert_eq!(parsed, tw, "round-trip failed for {kebab}");
        }
    }

    #[test]
    fn from_kebab_name_rejects_malformed_inputs() {
        assert_eq!(Tailwind::from_kebab_name(""), None);
        assert_eq!(Tailwind::from_kebab_name("red"), None);
        assert_eq!(Tailwind::from_kebab_name("red-9999"), None);
        assert_eq!(Tailwind::from_kebab_name("RED-500"), None);
        assert_eq!(Tailwind::from_kebab_name("not-a-color"), None);
    }

    #[test]
    fn from_kebab_name_accepts_special_keywords() {
        assert_eq!(Tailwind::from_kebab_name("inherit"), Some(Tailwind::Inherit));
        assert_eq!(Tailwind::from_kebab_name("currentColor"), Some(Tailwind::Current));
        assert_eq!(Tailwind::from_kebab_name("transparent"), Some(Tailwind::Transparent));
        assert_eq!(Tailwind::from_kebab_name("black"), Some(Tailwind::Black));
        assert_eq!(Tailwind::from_kebab_name("white"), Some(Tailwind::White));
    }
}
