# set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
set dotenv-load
set positional-arguments


BOLD := '\033[1m'
ITALIC := '\033[3m'
RESET := '\033[0m'
YELLOW2 := '\033[38;5;3m'
BLACK := '\033[30m'
RED := '\033[31m'
GREEN := '\033[32m'
YELLOW := '\033[33m'
BLUE := '\033[34m'
MAGENTA := '\033[35m'
CYAN := '\033[36m'
WHITE := '\033[37m'

default:
    #!/usr/bin/env bash
    set -euo pipefail

    if command -v md &> /dev/null; then
        md just.md
    fi

    echo
    echo "Playa (library & CLI)"
    echo "====================="
    echo ""
    just --list | grep -v 'default'
    echo

# build the library and CLI
build *args="":
    cargo build -p playa -p playa-cli {{args}}

# Test both Library and CLI
test:
    cargo test -p playa -p playa-cli

# Lint both the Library and CLI
lint:
    cargo clippy -p playa -p playa-cli

# Lint (and fix) both the Library and CLI
lint-fix:
    cargo clippy --fix -p playa -p playa-cli

# Install the Playa CLI
install:
    @echo
    @echo "{{BOLD}}Building Playa Library{{RESET}}"
    @echo ""
    @cargo build --release -p playa
    @echo ""
    @echo "{{BOLD}}{{YELLOW}}Installing the Playa CLI{{RESET}}"
    @echo ""
    @cargo install --path ./cli

# Validate the source code without doing a full build
check:
    cargo check -p playa -p playa-cli
