[workspace]
resolver = "2"
members = [
    "biscuit-file/cli",
    "biscuit-file/lib",
    "biscuit-hash/cli",
    "biscuit-hash/lib",
    "biscuit-speaks/cli",
    "biscuit-speaks/lib",
    "biscuit-terminal/cli",
    "biscuit-terminal/lib",
    "claudine/cli",
    "claudine/lib",
    "darkmatter/cli",
    "darkmatter/lib", "homelab/arcam-amp-integration", "homelab/cli", "homelab/eversolo-integration", "homelab/lib", "homelab/server", "homelab/sony-receiver-integration", "homelab/unfolded-integration-helper", "model-citizen/cli", "model-citizen/lib",
    "unchained-ai/model_id",
    "playa/cli",
    "playa/lib",
    "queue/cli",
    "queue/lib",
    "research/cli",
    "research/lib",
    "schematic/define",
    "schematic/definitions",
    "schematic/gen",
    "schematic/oauth",
    "sniff/cli",
    "sniff/lib",
    "tabby",
    "tabby/ui",
    "tree-hugger/cli",
    "tree-hugger/lib",
    "tui",
    "unchained-ai/cli",
    "unchained-ai/gen",
    "unchained-ai/lib", "agent-sandbox/cli", "messenger/cli", "messenger/lib", "biscuit-visualized/src", "worktree/lib", "worktree/cli",
]
exclude = ["schematic/schema"]
