use schematic_define::{ApiResponse, Endpoint, RestMethod};

/// Monitoring endpoints (nodes, cluster, listeners, metrics, stats, alarms, prometheus).
pub fn monitoring_endpoints() -> Vec<Endpoint> {
    vec![
        // Node & Cluster
        Endpoint {
            id: "ListNodes".to_string(),
            method: RestMethod::Get,
            path: "/nodes".to_string(),
            description: "List all nodes in the EMQX cluster".to_string(),
            request: None,
            response: ApiResponse::json_type("ListNodesResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetNode".to_string(),
            method: RestMethod::Get,
            path: "/nodes/{node}".to_string(),
            description: "Get detailed information about a specific node".to_string(),
            request: None,
            response: ApiResponse::json_type("NodeInfo"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetCluster".to_string(),
            method: RestMethod::Get,
            path: "/cluster".to_string(),
            description: "Get cluster status and node membership".to_string(),
            request: None,
            response: ApiResponse::json_type("ClusterStatus"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        // Listeners
        Endpoint {
            id: "ListListeners".to_string(),
            method: RestMethod::Get,
            path: "/listeners".to_string(),
            description: "List all configured listeners".to_string(),
            request: None,
            response: ApiResponse::json_type("ListListenersResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetListener".to_string(),
            method: RestMethod::Get,
            path: "/listeners/{id}".to_string(),
            description: "Get details of a specific listener".to_string(),
            request: None,
            response: ApiResponse::json_type("ListenerInfo"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        // Metrics & Stats
        Endpoint {
            id: "ListMetrics".to_string(),
            method: RestMethod::Get,
            path: "/metrics".to_string(),
            description: "Get broker metrics for all nodes".to_string(),
            request: None,
            response: ApiResponse::json_type("ListMetricsResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "ListStats".to_string(),
            method: RestMethod::Get,
            path: "/stats".to_string(),
            description: "Get broker statistics for all nodes".to_string(),
            request: None,
            response: ApiResponse::json_type("ListStatsResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetPrometheus".to_string(),
            method: RestMethod::Get,
            path: "/prometheus/stats".to_string(),
            description: "Get metrics in Prometheus format".to_string(),
            request: None,
            response: ApiResponse::Text,
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        // Alarms
        Endpoint {
            id: "ListAlarms".to_string(),
            method: RestMethod::Get,
            path: "/alarms".to_string(),
            description: "List active alarms".to_string(),
            request: None,
            response: ApiResponse::json_type("ListAlarmsResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
    ]
}
