set dotenv-load
set positional-arguments

BOLD := '\033[1m'
ITALIC := '\033[3m'
RESET := '\033[0m'
YELLOW2 := '\033[38;5;3m'
BLACK := '\033[30m'
RED := '\033[31m'
GREEN := '\033[32m'
YELLOW := '\033[33m'
BLUE := '\033[34m'
MAGENTA := '\033[35m'
CYAN := '\033[36m'
WHITE := '\033[37m'

default:
    @echo
    @echo "Research"
    @echo "------------------------------------"
    @echo ""
    @just --list | grep -v 'default'
    @echo

# build research modules (cli, lib)
build *args="":
    @echo ""
    @echo "Build Research Modules (CLI, LIB)"
    @echo "---------------------------------"
    @echo ""
    @cargo build -p research-cli -p research-lib {{args}}

# run tests across research modules
test *args="":
    @echo ""
    @echo "Testing Research Modules"
    @echo "------------------------"
    @echo ""
    @cargo test -p research-cli -p research-lib {{args}}

# install the `research` binary into the executable path
install:
    @cargo build --release -p research-cli
    @cargo install --path ./cli --locked

# run the debug release of the Research CLI
cli *args="":
    @cargo run -p research-cli -- {{args}}

# run clippy on research packages
lint:
    @echo ""
    @echo "Linting research Packages"
    @echo "--------------------------"
    @echo ""
    @cargo clippy -p research-lib -- -D warnings
    @cargo clippy -p research-cli -- -D warnings
