gitGraph
    branch fix/sniff
    checkout main
    commit id: "a0f1d1e"
    checkout fix/sniff
    commit id: "+89" type: HIGHLIGHT
    commit id: "85b1c02"
    commit id: "34022b8"
    commit id: "7966e7a"
    commit id: "1bfaea2"
    commit id: "51bfb8a"
    checkout main
    commit id: "12ee425"
    branch feat/schema-enhancement
    checkout feat/schema-enhancement
    commit id: "+50" type: HIGHLIGHT
    commit id: "a811c10"
    commit id: "5ddf29b"
    commit id: "4385291"
    commit id: "4002e8b"
    commit id: "389e3dc"
    checkout main
    commit id: "+3" type: HIGHLIGHT
    commit id: "dfbdce6"
    commit id: "a91fbf0"
    commit id: "92d4328"
    commit id: "3102d9a"
    commit id: "f234565"
    commit id: "2658996"
    commit id: "5fb5502"
    commit id: "f2a3857"
    commit id: "82ecff7"
    commit id: "999032d" tag: "main" tag: "origin/main"
    branch fix/wt-ux
    checkout fix/wt-ux
    commit id: "+63" type: HIGHLIGHT
    commit id: "49f02c6"
    commit id: "b6d2e53"
    commit id: "1e514f6"
    commit id: "d0063a1"
    commit id: "ff61ca9"
    checkout main
