gitGraph
    branch fix/sniff
    checkout main
    commit id: "a0f1d1e"
    checkout fix/sniff
    commit id: "+92" type: HIGHLIGHT
    commit id: "1bfaea2"
    commit id: "51bfb8a"
    checkout main
    commit id: "12ee425"
    branch feat/schema-enhancement
    checkout feat/schema-enhancement
    commit id: "+54" type: HIGHLIGHT
    commit id: "389e3dc"
    checkout main
    commit id: "+12" type: HIGHLIGHT
    commit id: "999032d" tag: "main" tag: "origin/main"
    branch fix/wt-ux
    checkout fix/wt-ux
    commit id: "+67" type: HIGHLIGHT
    commit id: "ff61ca9"
    checkout main
