# set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

BOLD := '\033[1m'
RESET := '\033[0m'

default:
    #!/usr/bin/env bash
    set -euo pipefail

    if command -v md &> /dev/null; then
        md just.md
    fi

    echo
    echo "Biscuit Terminal"
    echo "================"
    echo ""
    just --list | grep -v 'default'
    echo

# build the Biscuit Terminal (library and CLI)
build *args="":
    @echo ""
    @echo "Build Biscuit Terminal"
    @echo "---------------------"
    @echo ""
    @cargo build -p biscuit-terminal {{args}} -p biscuit-terminal-cli {{args}}

# run tests on Biscuit Terminal (library & CLI)
test *args="":
    @echo ""
    @echo "Test Biscuit Terminal"
    @echo "---------------------"
    @echo ""
    @cargo test -p biscuit-terminal {{args}}
    @echo ""

# Lint Biscuit Terminal with Clippy
lint:
    @echo ""
    @echo "Lint Biscuit Terminal"
    @echo "---------------------"
    @echo ""
    @cargo clippy -p biscuit-terminal -p biscuit-terminal-cli

# Lint Biscuit Terminal with Clippy and `--fix` flag on
lint-fix *args="":
    @echo ""
    @echo "Test Biscuit Terminal (--fix)"
    @echo "-----------------------------"
    @echo ""
    @cargo clippy --fix -p biscuit-terminal -p biscuit-terminal-cli {{args}}

# commits all the staged changes using GPT 5.2 (via Opencode)
commit:
    @echo "Committing staged changes in the Rusty Biscuit monorepo to git"
    @echo ""
    @cd ..
    @opencode run commit "-f" --model "openai/gpt-5.2"
    @cd -
    @if command -v so-you-say >/dev/null 2>&1; then \
        so-you-say "git commits completed in rusty-biscuit monorepo"; \
    fi

# Install the Biscuit Terminal CLI
install:
    @echo ""
    @echo "Install Biscuit Terminal CLI"
    @echo "----------------------------"
    @echo ""

    @cargo build --release -p biscuit-terminal
    @cargo install --path ./cli
    @echo ""
    @echo "{{BOLD}}bt{{RESET}} CLI installed"
    @echo ""

# Uses `cargo check` to validate code with the compiler
check:
    @echo ""
    @echo "Check Biscuit Terminal"
    @echo "---------------------"
    @echo ""
    @cargo check -p biscuit-terminal -p biscuit-terminal-cli
    @echo ""

# Get the metadata from the Biscuit Terminal CLI's latest debug build
meta:
    @echo "Metadata from Biscuit Terminal CLI (latest debug build)"
    @echo ""
    @cargo run -p biscuit-terminal-cli

# Example: show an example table with text, integer, and currency based columns
example-table-showcase:
    @cargo run -p biscuit-terminal --example table_showcase

# Example: use the `TwoColum` struct with text on both sides
example-two-column-text:
    @cargo run -p biscuit-terminal --example two-column-prose

# Example: use the `TwoColumn` struct with image in left column, text in right
example-two-column-image:
    @cargo run -p biscuit-terminal --example two_column_with_image

# Open Claude Code in yolo mode
oc *args="":
    @clear
    @echo "Loading {{BOLD}}Opencode{{RESET}}"
    @cd .. && echo "Loading {{BOLD}}Opencode{{RESET}}" && opencode {{args}}

# Open Opencode
cc *args="":
    @clear
    @echo "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
    @cd .. && echo "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})" && claude --dangerously-skip-permissions {{args}}

# Use GPT 5.2 to commit staged changes
commit:
    @cd .. && opencode run commit "-f" --model "openai/gpt-5.2"
    @if command -v so-you-say >/dev/null 2>&1; then \
        so-you-say "git commits completed in rusty-biscuit monorepo"; \
    fi
