BOLD := '\033[1m'
RESET := '\033[0m'

default:
    @echo "{{BOLD}}biscuit-speaks{{RESET}} Library"
    @echo
    @just --list | grep -v 'default'

# build library
build *args="":
    @echo "Building biscuit-speaks..."
    @echo
    @cargo build -p biscuit-speaks {{args}}
    @echo

# test library
test *args="":
    @echo "Testing {{BOLD}}biscuit-speaks{{RESET}} library"
    @echo ""
    @cargo test -p biscuit-speaks --all-features {{args}}

# lint with clippy
lint *args="":
    @cargo clippy -p biscuit-speaks -- {{args}}


# build and show the docs for the library code
docs:
    @echo "Build and then show latest docs for the biscuit-speaks library code"
    @echo ""
    @cargo doc -p biscuit-speaks --open

# Open Claude Code in yolo mode
oc *args="":
    @clear
    @echo "Loading {{BOLD}}Opencode{{RESET}}"
    @cd .. && echo "Loading {{BOLD}}Opencode{{RESET}}" && opencode {{args}}

# Open Opencode
cc *args="":
    @clear
    @echo "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
    @cd .. && echo "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})" && claude --dangerously-skip-permissions {{args}}

# Use GPT 5.2 to commit staged changes
commit:
    @cd .. && opencode run commit "-f" --model "openai/gpt-5.2"
    @if command -v so-you-say >/dev/null 2>&1; then \
        so-you-say "git commits completed in rusty-biscuit monorepo"; \
    fi
    @cd -
