BOLD := '\033[1m'
RESET := '\033[0m'

default:
    @echo "{{BOLD}}biscuit-speaks{{RESET}} Library"
    @echo
    @just --list | grep -v 'default'

# build library
build *args="":
    @echo "Building biscuit-speaks..."
    @echo
    @cargo build -p biscuit-speaks {{args}}
    @echo

# test library
test *args="":
    @echo "Testing {{BOLD}}biscuit-speaks{{RESET}} library"
    @echo ""
    @cargo test -p biscuit-speaks --all-features {{args}}

# lint with clippy
lint *args="":
    @cargo clippy -p biscuit-speaks -- {{args}}


# build and show the docs for the library code
docs:
    @echo "Build and then show latest docs for the biscuit-speaks library code"
    @echo ""
    @cargo doc -p biscuit-speaks --open
