set dotenv-load
set positional-arguments

BOLD := '\033[1m'
ITALIC := '\033[3m'
RESET := '\033[0m'
YELLOW2 := '\033[38;5;3m'
BLACK := '\033[30m'
RED := '\033[31m'
GREEN := '\033[32m'
YELLOW := '\033[33m'
BLUE := '\033[34m'
MAGENTA := '\033[35m'
CYAN := '\033[36m'
WHITE := '\033[37m'

default:
    #!/usr/bin/env bash
    set -euo pipefail

    echo
    if command -v md &> /dev/null; then
        md just.md
    else
        echo "Homelab Library & CLI"
        echo "====================="
    fi

    echo ""
    just --list | grep -v 'default'
    echo

# build Homelab packages (lib, cli)
build *args="":
    @echo ""
    @echo "Build Homelab Packages (Library and Homey CLI)"
    @echo "----------------------------------------------"
    @echo ""
    @cargo build -p homelab -p homey {{args}}

# run tests for Homelab packages
test *args="":
    @echo ""
    @echo "Testing {{BOLD}}Homelab{{RESET}} ({{ITALIC}}Library and Homey CLI{{RESET}})"
    @echo "---------------------------------------"
    @echo ""
    @cargo test -p homelab -p homey {{args}}

# run clippy on Homelab packages
lint:
    @echo ""
    @echo "Linting Homelab Packages"
    @echo "--------------------------"
    @echo ""
    @cargo clippy -p homelab -- -D warnings
    @cargo clippy -p homey -- -D warnings

install:
    @echo ""
    @echo "{{BOLD}}Building Homelab Library{{RESET}}"
    @cargo build -p homelab --release
    @echo ""
    @echo "{{BOLD}}{{YELLOW}}Installing Homelab CLI ({{ITALIC}}homey{{RESET}}{{BOLD}}{{YELLOW}}){{RESET}}"
    @cargo install --path ./cli
    @echo ""
    @echo "{{BOLD}}{{BLUE}}Homelab CLI installed{{RESET}}"
    @echo ""

check:
    @echo ""
    @echo "Checking Homelab Library and CLI"
    @echo ""
    @cargo check -p homelab -p homey

# Open Opencode
oc *args="":
    @clear
    @echo "Loading {{BOLD}}Opencode{{RESET}}"
    @cd .. && opencode {{args}}

# Open Claude Code in yolo mode
cc *args="":
    @clear
    @echo "Loading {{BOLD}}Claude Code{{RESET}} ({{ITALIC}}in yolo mode{{RESET}})"
    @cd .. && claude --dangerously-skip-permissions {{args}}

# Use GPT 5.2 to commit staged changes
commit:
    @cd ..
    @opencode run commit "-f" --model "openai/gpt-5.2-codex"
    @if command -v so-you-say >/dev/null 2>&1; then \
        so-you-say "git commits completed in rusty-biscuit monorepo"; \
    fi

