gitGraph
    commit id: "1314bd6"
    branch fix/wt-ux
    checkout fix/wt-ux
    commit id: "7ba6ea8"
    commit id: "2a7298a"
    branch fix/sniff
    checkout fix/sniff
    commit id: "+95" type: HIGHLIGHT
    commit id: "b3b17f3"
    checkout fix/wt-ux
    checkout main
    merge fix/wt-ux id: "08cf96a" tag: "main"
    merge fix/sniff id: "b47a046" tag: "origin/main"