gitGraph
    commit id: "1111111"
    branch fix/wt-ux
    checkout fix/wt-ux
    commit id: "+1" type: HIGHLIGHT
    commit id: "2a7298a"
    checkout main
    commit id: "+1 " type: HIGHLIGHT
    merge fix/wt-ux id: "08cf96a" tag: "origin/main"
    commit id: "3333333" tag: "main"