// This code was automatically generated by schematic-gen. Do not edit manually.

//! Generated API client for [Bitbucket](https://developer.atlassian.com/cloud/bitbucket/rest/).
//!
//! Bitbucket Cloud REST API v2.0 for repository, PR, issue, and tag workflows
//!
//! ## Authentication
//!
//! Uses HTTP Basic authentication. Set via environment variable: `BITBUCKET_APP_PASSWORD`.
//!
//! ## Features
//!
//! **GET**:
//! - `GetRepository` - Get repository metadata including default branch and workspace info
//! - `ListDirectoryContents` - List directory contents at a specific commit
//! - `GetFileContentRaw` - Get raw file content at a specific commit
//! - `ListPullRequests` - List pull requests (all states)
//! - `GetPullRequest` - Get a single pull request by ID
//! - `ListPullRequestComments` - List comments on a pull request
//! - `ListIssues` - List repository issues
//! - `GetIssue` - Get a single issue by ID
//! - `ListIssueComments` - List comments on an issue
//! - `ListIssueChanges` - List change history for an issue
//! - `ListTags` - List repository tags
//! - `GetTag` - Get a single tag by name
//! - `ListDownloads` - List repository downloads (release artifacts)
//! - `GetDownload` - Download a file from repository downloads
//!
//! ## Example
//!
//! ```ignore
//! use schematic_schema::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), SchematicError> {
//!     let client = Bitbucket::new();
//!     let response = client.get_repository().await?;
//!     println!("{:?}", response);
//!     Ok(())
//! }
//! ```
use serde::{Deserialize, Serialize};
pub use schematic_definitions::bitbucket::*;
use crate::shared::{RequestParts, SchematicError};
/// Request for `GetRepository` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::GetRepositoryRequest;
///
/// let request = GetRepositoryRequest::new("workspace_value", "repo_slug_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
}
impl GetRepositoryRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(workspace: impl Into<String>, repo_slug: impl Into<String>) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/repositories/{}/{}", self.workspace, self.repo_slug);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetRepositoryRequest {
    type Response = Repository;
    const ENDPOINT_ID: &'static str = "GetRepository";
}
/// Request for `ListDirectoryContents` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListDirectoryContentsRequest;
///
/// let request = ListDirectoryContentsRequest::new("workspace_value", "repo_slug_value", "commit_value", "path_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListDirectoryContentsRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: commit
    pub commit: String,
    /// Path parameter: path
    pub path: String,
}
impl ListDirectoryContentsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        commit: impl Into<String>,
        path: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            commit: commit.into(),
            path: path.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/src/{}/{}?pagelen=50", self.workspace, self.repo_slug,
            self.commit, self.path
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListDirectoryContentsRequest {
    type Response = PaginatedResponse<SourceEntry>;
    const ENDPOINT_ID: &'static str = "ListDirectoryContents";
}
/// Request for `GetFileContentRaw` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::GetFileContentRawRequest;
///
/// let request = GetFileContentRawRequest::new("workspace_value", "repo_slug_value", "commit_value", "path_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetFileContentRawRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: commit
    pub commit: String,
    /// Path parameter: path
    pub path: String,
}
impl GetFileContentRawRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        commit: impl Into<String>,
        path: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            commit: commit.into(),
            path: path.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/src/{}/{}", self.workspace, self.repo_slug, self.commit,
            self.path
        );
        Ok(("GET", path, None, vec![("Accept".to_string(), "text/plain".to_string())]))
    }
}
impl crate::shared::EndpointSpec for GetFileContentRawRequest {
    type Response = String;
    const ENDPOINT_ID: &'static str = "GetFileContentRaw";
}
/// Request for `ListPullRequests` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListPullRequestsRequest;
///
/// let request = ListPullRequestsRequest::new("workspace_value", "repo_slug_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListPullRequestsRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
}
impl ListPullRequestsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(workspace: impl Into<String>, repo_slug: impl Into<String>) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/pullrequests?state=all&pagelen=50", self.workspace, self
            .repo_slug
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListPullRequestsRequest {
    type Response = PaginatedResponse<PullRequest>;
    const ENDPOINT_ID: &'static str = "ListPullRequests";
}
/// Request for `GetPullRequest` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::GetPullRequestRequest;
///
/// let request = GetPullRequestRequest::new("workspace_value", "repo_slug_value", "id_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetPullRequestRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: id
    pub id: String,
}
impl GetPullRequestRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        id: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            id: id.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/pullrequests/{}", self.workspace, self.repo_slug, self
            .id
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetPullRequestRequest {
    type Response = PullRequest;
    const ENDPOINT_ID: &'static str = "GetPullRequest";
}
/// Request for `ListPullRequestComments` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListPullRequestCommentsRequest;
///
/// let request = ListPullRequestCommentsRequest::new("workspace_value", "repo_slug_value", "id_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListPullRequestCommentsRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: id
    pub id: String,
}
impl ListPullRequestCommentsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        id: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            id: id.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/pullrequests/{}/comments?pagelen=50", self.workspace,
            self.repo_slug, self.id
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListPullRequestCommentsRequest {
    type Response = PaginatedResponse<PullRequestComment>;
    const ENDPOINT_ID: &'static str = "ListPullRequestComments";
}
/// Request for `ListIssues` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListIssuesRequest;
///
/// let request = ListIssuesRequest::new("workspace_value", "repo_slug_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssuesRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
}
impl ListIssuesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(workspace: impl Into<String>, repo_slug: impl Into<String>) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/issues?pagelen=50", self.workspace, self.repo_slug
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssuesRequest {
    type Response = PaginatedResponse<Issue>;
    const ENDPOINT_ID: &'static str = "ListIssues";
}
/// Request for `GetIssue` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::GetIssueRequest;
///
/// let request = GetIssueRequest::new("workspace_value", "repo_slug_value", "id_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetIssueRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: id
    pub id: String,
}
impl GetIssueRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        id: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            id: id.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/issues/{}", self.workspace, self.repo_slug, self.id
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetIssueRequest {
    type Response = Issue;
    const ENDPOINT_ID: &'static str = "GetIssue";
}
/// Request for `ListIssueComments` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListIssueCommentsRequest;
///
/// let request = ListIssueCommentsRequest::new("workspace_value", "repo_slug_value", "id_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssueCommentsRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: id
    pub id: String,
}
impl ListIssueCommentsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        id: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            id: id.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/issues/{}/comments?pagelen=50", self.workspace, self
            .repo_slug, self.id
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssueCommentsRequest {
    type Response = PaginatedResponse<IssueComment>;
    const ENDPOINT_ID: &'static str = "ListIssueComments";
}
/// Request for `ListIssueChanges` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListIssueChangesRequest;
///
/// let request = ListIssueChangesRequest::new("workspace_value", "repo_slug_value", "id_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssueChangesRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: id
    pub id: String,
}
impl ListIssueChangesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        id: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            id: id.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/issues/{}/changes?pagelen=50", self.workspace, self
            .repo_slug, self.id
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssueChangesRequest {
    type Response = PaginatedResponse<IssueChange>;
    const ENDPOINT_ID: &'static str = "ListIssueChanges";
}
/// Request for `ListTags` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListTagsRequest;
///
/// let request = ListTagsRequest::new("workspace_value", "repo_slug_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListTagsRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
}
impl ListTagsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(workspace: impl Into<String>, repo_slug: impl Into<String>) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/refs/tags?pagelen=50", self.workspace, self.repo_slug
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListTagsRequest {
    type Response = PaginatedResponse<Tag>;
    const ENDPOINT_ID: &'static str = "ListTags";
}
/// Request for `GetTag` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::GetTagRequest;
///
/// let request = GetTagRequest::new("workspace_value", "repo_slug_value", "name_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetTagRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: name
    pub name: String,
}
impl GetTagRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        name: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            name: name.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/refs/tags/{}", self.workspace, self.repo_slug, self.name
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetTagRequest {
    type Response = Tag;
    const ENDPOINT_ID: &'static str = "GetTag";
}
/// Request for `ListDownloads` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::ListDownloadsRequest;
///
/// let request = ListDownloadsRequest::new("workspace_value", "repo_slug_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListDownloadsRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
}
impl ListDownloadsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(workspace: impl Into<String>, repo_slug: impl Into<String>) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/downloads?pagelen=50", self.workspace, self.repo_slug
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListDownloadsRequest {
    type Response = PaginatedResponse<Download>;
    const ENDPOINT_ID: &'static str = "ListDownloads";
}
/// Request for `GetDownload` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::bitbucket::GetDownloadRequest;
///
/// let request = GetDownloadRequest::new("workspace_value", "repo_slug_value", "filename_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetDownloadRequest {
    /// Path parameter: workspace
    pub workspace: String,
    /// Path parameter: repo_slug
    pub repo_slug: String,
    /// Path parameter: filename
    pub filename: String,
}
impl GetDownloadRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        workspace: impl Into<String>,
        repo_slug: impl Into<String>,
        filename: impl Into<String>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            repo_slug: repo_slug.into(),
            filename: filename.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repositories/{}/{}/downloads/{}", self.workspace, self.repo_slug, self
            .filename
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetDownloadRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "GetDownload";
}
/// Request enum for Bitbucket API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum BitbucketRequest {
    /// Get repository metadata including default branch and workspace info
    GetRepository(GetRepositoryRequest),
    /// List directory contents at a specific commit
    ListDirectoryContents(ListDirectoryContentsRequest),
    /// Get raw file content at a specific commit
    GetFileContentRaw(GetFileContentRawRequest),
    /// List pull requests (all states)
    ListPullRequests(ListPullRequestsRequest),
    /// Get a single pull request by ID
    GetPullRequest(GetPullRequestRequest),
    /// List comments on a pull request
    ListPullRequestComments(ListPullRequestCommentsRequest),
    /// List repository issues
    ListIssues(ListIssuesRequest),
    /// Get a single issue by ID
    GetIssue(GetIssueRequest),
    /// List comments on an issue
    ListIssueComments(ListIssueCommentsRequest),
    /// List change history for an issue
    ListIssueChanges(ListIssueChangesRequest),
    /// List repository tags
    ListTags(ListTagsRequest),
    /// Get a single tag by name
    GetTag(GetTagRequest),
    /// List repository downloads (release artifacts)
    ListDownloads(ListDownloadsRequest),
    /// Download a file from repository downloads
    GetDownload(GetDownloadRequest),
}
impl BitbucketRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::GetRepository(req) => req.into_parts(),
            Self::ListDirectoryContents(req) => req.into_parts(),
            Self::GetFileContentRaw(req) => req.into_parts(),
            Self::ListPullRequests(req) => req.into_parts(),
            Self::GetPullRequest(req) => req.into_parts(),
            Self::ListPullRequestComments(req) => req.into_parts(),
            Self::ListIssues(req) => req.into_parts(),
            Self::GetIssue(req) => req.into_parts(),
            Self::ListIssueComments(req) => req.into_parts(),
            Self::ListIssueChanges(req) => req.into_parts(),
            Self::ListTags(req) => req.into_parts(),
            Self::GetTag(req) => req.into_parts(),
            Self::ListDownloads(req) => req.into_parts(),
            Self::GetDownload(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::GetRepository(_) => {
                <GetRepositoryRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListDirectoryContents(_) => {
                <ListDirectoryContentsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetFileContentRaw(_) => {
                <GetFileContentRawRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListPullRequests(_) => {
                <ListPullRequestsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetPullRequest(_) => {
                <GetPullRequestRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListPullRequestComments(_) => {
                <ListPullRequestCommentsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssues(_) => {
                <ListIssuesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetIssue(_) => {
                <GetIssueRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssueComments(_) => {
                <ListIssueCommentsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssueChanges(_) => {
                <ListIssueChangesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListTags(_) => {
                <ListTagsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetTag(_) => {
                <GetTagRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListDownloads(_) => {
                <ListDownloadsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetDownload(_) => {
                <GetDownloadRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
}
impl From<GetRepositoryRequest> for BitbucketRequest {
    fn from(req: GetRepositoryRequest) -> Self {
        Self::GetRepository(req)
    }
}
impl From<ListDirectoryContentsRequest> for BitbucketRequest {
    fn from(req: ListDirectoryContentsRequest) -> Self {
        Self::ListDirectoryContents(req)
    }
}
impl From<GetFileContentRawRequest> for BitbucketRequest {
    fn from(req: GetFileContentRawRequest) -> Self {
        Self::GetFileContentRaw(req)
    }
}
impl From<ListPullRequestsRequest> for BitbucketRequest {
    fn from(req: ListPullRequestsRequest) -> Self {
        Self::ListPullRequests(req)
    }
}
impl From<GetPullRequestRequest> for BitbucketRequest {
    fn from(req: GetPullRequestRequest) -> Self {
        Self::GetPullRequest(req)
    }
}
impl From<ListPullRequestCommentsRequest> for BitbucketRequest {
    fn from(req: ListPullRequestCommentsRequest) -> Self {
        Self::ListPullRequestComments(req)
    }
}
impl From<ListIssuesRequest> for BitbucketRequest {
    fn from(req: ListIssuesRequest) -> Self {
        Self::ListIssues(req)
    }
}
impl From<GetIssueRequest> for BitbucketRequest {
    fn from(req: GetIssueRequest) -> Self {
        Self::GetIssue(req)
    }
}
impl From<ListIssueCommentsRequest> for BitbucketRequest {
    fn from(req: ListIssueCommentsRequest) -> Self {
        Self::ListIssueComments(req)
    }
}
impl From<ListIssueChangesRequest> for BitbucketRequest {
    fn from(req: ListIssueChangesRequest) -> Self {
        Self::ListIssueChanges(req)
    }
}
impl From<ListTagsRequest> for BitbucketRequest {
    fn from(req: ListTagsRequest) -> Self {
        Self::ListTags(req)
    }
}
impl From<GetTagRequest> for BitbucketRequest {
    fn from(req: GetTagRequest) -> Self {
        Self::GetTag(req)
    }
}
impl From<ListDownloadsRequest> for BitbucketRequest {
    fn from(req: ListDownloadsRequest) -> Self {
        Self::ListDownloads(req)
    }
}
impl From<GetDownloadRequest> for BitbucketRequest {
    fn from(req: GetDownloadRequest) -> Self {
        Self::GetDownload(req)
    }
}
/// Bitbucket Cloud REST API v2.0 for repository, PR, issue, and tag workflows client.
pub struct Bitbucket {
    client: reqwest::Client,
    base_url: String,
    /// Environment variable names for authentication credentials.
    env_auth: Vec<String>,
    /// Authentication strategy for this API client.
    auth_strategy: schematic_define::AuthStrategy,
    /// Environment variable for Basic auth username.
    env_username: Option<String>,
    /// Headers builder with environment variable support for credentials.
    headers: schematic_define::Headers,
    /// Variant-specific hooks for response customization.
    variant_hooks: crate::shared::VariantHooks,
}
impl Bitbucket {
    /// Base URL for the API.
    pub const BASE_URL: &'static str = "https://api.bitbucket.org/2.0";
    /// Official API documentation URL, if available.
    pub const DOCS_URL: Option<&'static str> = Some(
        "https://developer.atlassian.com/cloud/bitbucket/rest/",
    );
    /// Creates a new API client with the default base URL.
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec!["BITBUCKET_APP_PASSWORD".to_string()],
            auth_strategy: schematic_define::AuthStrategy::Basic,
            env_username: Some("BITBUCKET_USERNAME".to_string()),
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_USERNAME".to_string()],
                        ),
                    ),
                    basic_pass: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_APP_PASSWORD".to_string()],
                        ),
                    ),
                    api_key: None,
                }),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a custom base URL.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let client = Api::with_base_url("http://localhost:8080/v1");
    /// ```
    pub fn with_base_url(base_url: impl Into<String>) -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: base_url.into(),
            env_auth: vec!["BITBUCKET_APP_PASSWORD".to_string()],
            auth_strategy: schematic_define::AuthStrategy::Basic,
            env_username: Some("BITBUCKET_USERNAME".to_string()),
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_USERNAME".to_string()],
                        ),
                    ),
                    basic_pass: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_APP_PASSWORD".to_string()],
                        ),
                    ),
                    api_key: None,
                }),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client.
    ///
    /// Use this when you need custom timeouts, connection pools, or middleware.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client(custom_client);
    /// ```
    pub fn with_client(client: reqwest::Client) -> Self {
        Self {
            client,
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec!["BITBUCKET_APP_PASSWORD".to_string()],
            auth_strategy: schematic_define::AuthStrategy::Basic,
            env_username: Some("BITBUCKET_USERNAME".to_string()),
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_USERNAME".to_string()],
                        ),
                    ),
                    basic_pass: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_APP_PASSWORD".to_string()],
                        ),
                    ),
                    api_key: None,
                }),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client and custom base URL.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client_and_base_url(custom_client, "http://localhost:8080");
    /// ```
    pub fn with_client_and_base_url(
        client: reqwest::Client,
        base_url: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            env_auth: vec!["BITBUCKET_APP_PASSWORD".to_string()],
            auth_strategy: schematic_define::AuthStrategy::Basic,
            env_username: Some("BITBUCKET_USERNAME".to_string()),
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_USERNAME".to_string()],
                        ),
                    ),
                    basic_pass: Some(
                        schematic_define::EnvList::new(
                            vec!["BITBUCKET_APP_PASSWORD".to_string()],
                        ),
                    ),
                    api_key: None,
                }),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a variant builder for customizing this API client.
    ///
    /// The builder pattern allows fluent configuration of:
    /// - Base URL (for proxies, mock servers, or different environments)
    /// - Authentication credentials (different env var names)
    /// - Authentication strategy
    /// - Response hooks for JSON transformation and mutation
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::UpdateStrategy;
    ///
    /// let api = Api::new();
    ///
    /// // Create a variant pointing to a staging server with a response hook
    /// let staging = api.variant()
    ///     .base_url("https://staging.api.com/v1")
    ///     .env_auth(vec!["STAGING_API_KEY".to_string()])
    ///     .mutate_response::<ListModelsRequest>(|ctx, response| {
    ///         response.data.retain(|m| !m.id.contains("deprecated"));
    ///         Ok(())
    ///     })
    ///     .build();
    /// ```
    #[must_use]
    pub fn variant(&self) -> BitbucketVariantBuilder<'_> {
        BitbucketVariantBuilder::new(self)
    }
    /// Creates a variant of this API client with different configuration.
    ///
    /// This is a convenience method equivalent to:
    /// ```ignore
    /// api.variant()
    ///     .base_url(base_url)
    ///     .env_auth(env_auth)
    ///     .auth_update(strategy)
    ///     .build()
    /// ```
    ///
    /// ## Arguments
    ///
    /// * `base_url` - New base URL for this variant
    /// * `env_auth` - New environment variable names for credentials
    /// * `strategy` - How to update the auth strategy:
    ///   - `UpdateStrategy::NoChange` - Keep current auth strategy
    ///   - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    pub fn variant_with(
        &self,
        base_url: impl Into<String>,
        env_auth: Vec<String>,
        strategy: schematic_define::UpdateStrategy,
    ) -> Self {
        self.variant()
            .base_url(base_url)
            .env_auth(env_auth)
            .auth_update(strategy)
            .build()
    }
    /// Creates a variant of this API client with custom headers configuration.
    ///
    /// This is a convenience method for creating variants with fully customized
    /// headers, including environment variable mapping for credentials.
    ///
    /// ## Arguments
    ///
    /// * `headers` - Headers builder with environment mapping configured
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::{Headers, EnvMapping, EnvList};
    ///
    /// let custom_headers = Headers::default()
    ///     .with_env_mapping(EnvMapping {
    ///         bearer_token: Some(EnvList::single("STAGING_TOKEN")),
    ///         basic_user: None,
    ///         basic_pass: None,
    ///         api_key: None,
    ///     })
    ///     .header("X-Environment", "staging");
    ///
    /// let staging_client = api.variant_with_headers(custom_headers);
    /// ```
    pub fn variant_with_headers(&self, headers: schematic_define::Headers) -> Self {
        self.variant().headers_builder(headers).build()
    }
    /// Returns a reference to the underlying HTTP client.
    ///
    /// Use this for custom requests that aren't covered by the generated methods,
    /// such as paginated endpoints that require query parameters.
    pub fn http_client(&self) -> &reqwest::Client {
        &self.client
    }
    /// Returns the base URL for this API client.
    pub fn api_base_url(&self) -> &str {
        &self.base_url
    }
    /// Returns the API key header name and value for authentication.
    ///
    /// Returns `None` if the authentication strategy is not `ApiKey`
    /// or if the API key environment variable is not set.
    pub fn api_key_header(&self) -> Option<(String, String)> {
        match &self.auth_strategy {
            schematic_define::AuthStrategy::ApiKey { header } => {
                for env_name in &self.env_auth {
                    if let Ok(value) = std::env::var(env_name) {
                        return Some((header.clone(), value));
                    }
                }
                None
            }
            _ => None,
        }
    }
}
impl Default for Bitbucket {
    fn default() -> Self {
        Self::new()
    }
}
/// Builder for creating customized variants of the API client.
///
/// Use [`#struct_name::variant()`] to create a builder, then chain
/// configuration methods and call [`build()`](Self::build) to create
/// the variant client.
pub struct BitbucketVariantBuilder<'a> {
    base: &'a Bitbucket,
    base_url: Option<String>,
    env_auth: Option<Vec<String>>,
    auth_update: schematic_define::UpdateStrategy,
    headers: Option<schematic_define::Headers>,
    pre_response_json: Option<std::sync::Arc<crate::shared::PreResponseJsonHook>>,
    response_mutators: std::collections::HashMap<
        &'static str,
        std::sync::Arc<dyn crate::shared::AnyResponseMutator>,
    >,
}
impl<'a> BitbucketVariantBuilder<'a> {
    /// Creates a new variant builder from the base API client.
    fn new(base: &'a Bitbucket) -> Self {
        Self {
            base,
            base_url: None,
            env_auth: None,
            auth_update: schematic_define::UpdateStrategy::NoChange,
            headers: None,
            pre_response_json: None,
            response_mutators: std::collections::HashMap::new(),
        }
    }
    /// Sets the base URL for the variant.
    ///
    /// If not set, the original client's base URL is used.
    #[must_use]
    pub fn base_url(mut self, url: impl Into<String>) -> Self {
        self.base_url = Some(url.into());
        self
    }
    /// Sets the environment variable names for authentication.
    ///
    /// If not set, the original client's env_auth is used.
    #[must_use]
    pub fn env_auth(mut self, env_auth: Vec<String>) -> Self {
        self.env_auth = Some(env_auth);
        self
    }
    /// Sets how the authentication strategy should be updated.
    ///
    /// - `UpdateStrategy::NoChange` - Keep current auth strategy (default)
    /// - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    #[must_use]
    pub fn auth_update(mut self, strategy: schematic_define::UpdateStrategy) -> Self {
        self.auth_update = strategy;
        self
    }
    /// Sets custom headers for the variant using a Headers builder.
    ///
    /// This replaces the entire headers configuration, including environment
    /// variable mapping. If not set, the original client's headers are used.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::{Headers, EnvMapping, EnvList};
    ///
    /// let custom = Headers::default()
    ///     .with_env_mapping(EnvMapping {
    ///         bearer_token: Some(EnvList::single("STAGING_KEY")),
    ///         basic_user: None,
    ///         basic_pass: None,
    ///         api_key: None,
    ///     })
    ///     .header("X-Custom", "value");
    ///
    /// let variant = api.variant().headers_builder(custom).build();
    /// ```
    #[must_use]
    pub fn headers_builder(mut self, headers: schematic_define::Headers) -> Self {
        self.headers = Some(headers);
        self
    }
    /// Sets a pre-response JSON transformation hook.
    ///
    /// This hook runs after receiving an HTTP response but before
    /// deserializing to the response type. Use it to reshape JSON
    /// payloads to match expected structures.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// // Unwrap a { data: ... } envelope
    /// variant.pre_response_json(|ctx, json| {
    ///     Ok(json.get("data").cloned().unwrap_or(json))
    /// })
    /// ```
    #[must_use]
    pub fn pre_response_json<F>(mut self, hook: F) -> Self
    where
        F: Fn(
                &crate::shared::ResponseContext,
                serde_json::Value,
            ) -> Result<serde_json::Value, crate::shared::SchematicError> + Send + Sync
            + 'static,
    {
        self.pre_response_json = Some(std::sync::Arc::new(hook));
        self
    }
    /// Registers a response mutation hook for a specific endpoint.
    ///
    /// This hook runs after deserializing the response and can mutate
    /// the response object in place. The endpoint is identified by its
    /// request type.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// variant.mutate_response::<ListModelsRequest>(|ctx, response| {
    ///     response.data.retain(|m| !m.id.contains("deprecated"));
    ///     Ok(())
    /// })
    /// ```
    #[must_use]
    pub fn mutate_response<R, F>(mut self, hook: F) -> Self
    where
        R: crate::shared::EndpointSpec,
        R::Response: Send + Sync + 'static,
        F: Fn(
                &crate::shared::ResponseContext,
                &mut R::Response,
            ) -> Result<(), crate::shared::SchematicError> + Send + Sync + 'static,
    {
        self.response_mutators
            .insert(
                R::ENDPOINT_ID,
                std::sync::Arc::new(crate::shared::TypedMutator::new(hook)),
            );
        self
    }
    /// Builds the variant API client with the configured options.
    ///
    /// Options not explicitly set will inherit from the base client.
    #[must_use]
    pub fn build(self) -> Bitbucket {
        let auth_strategy = match self.auth_update {
            schematic_define::UpdateStrategy::NoChange => self.base.auth_strategy.clone(),
            schematic_define::UpdateStrategy::ChangeTo(auth) => auth,
            _ => self.base.auth_strategy.clone(),
        };
        Bitbucket {
            client: self.base.client.clone(),
            base_url: self.base_url.unwrap_or_else(|| self.base.base_url.clone()),
            env_auth: self.env_auth.unwrap_or_else(|| self.base.env_auth.clone()),
            auth_strategy,
            env_username: self.base.env_username.clone(),
            headers: self.headers.unwrap_or_else(|| self.base.headers.clone()),
            variant_hooks: crate::shared::VariantHooks {
                pre_response_json: self.pre_response_json,
                response_mutators: self.response_mutators,
            },
        }
    }
}
impl Bitbucket {
    /// Builds and sends an HTTP request, returning the raw response plus context.
    ///
    /// This is an internal helper method used by the public request methods.
    /// Returns both the response and the context needed for hook processing.
    async fn build_and_send_request(
        &self,
        request: impl Into<BitbucketRequest>,
    ) -> Result<(reqwest::Response, crate::shared::ResponseContext), SchematicError> {
        let request = request.into();
        let endpoint_id = request.endpoint_id();
        let (method, path, body, endpoint_headers) = request.into_parts()?;
        let url = format!("{}{}", self.base_url, path);
        let mut req_builder = match method {
            "GET" => self.client.get(&url),
            "POST" => self.client.post(&url),
            "PUT" => self.client.put(&url),
            "PATCH" => self.client.patch(&url),
            "DELETE" => self.client.delete(&url),
            "HEAD" => self.client.head(&url),
            "OPTIONS" => self.client.request(reqwest::Method::OPTIONS, &url),
            _ => return Err(SchematicError::UnsupportedMethod(method.to_string())),
        };
        if !self.headers.has_authorization() {
            match &self.auth_strategy {
                schematic_define::AuthStrategy::None => {}
                schematic_define::AuthStrategy::BearerToken { header } => {
                    let header_name = header.as_deref().unwrap_or("Authorization");
                    let token = self
                        .env_auth
                        .iter()
                        .find_map(|var| std::env::var(var).ok())
                        .ok_or_else(|| SchematicError::MissingCredential {
                            env_vars: self.env_auth.clone(),
                        })?;
                    req_builder = req_builder
                        .header(header_name, format!("Bearer {}", token));
                }
                schematic_define::AuthStrategy::ApiKey { header } => {
                    let key = self
                        .env_auth
                        .iter()
                        .find_map(|var| std::env::var(var).ok())
                        .ok_or_else(|| SchematicError::MissingCredential {
                            env_vars: self.env_auth.clone(),
                        })?;
                    req_builder = req_builder.header(header.as_str(), key);
                }
                schematic_define::AuthStrategy::Basic => {
                    let username_env = self
                        .env_username
                        .as_deref()
                        .unwrap_or("USERNAME");
                    let password_env = self
                        .env_auth
                        .first()
                        .map(String::as_str)
                        .unwrap_or("PASSWORD");
                    let username = std::env::var(username_env)
                        .map_err(|_| SchematicError::MissingCredential {
                            env_vars: vec![username_env.to_string()],
                        })?;
                    let password = std::env::var(password_env)
                        .map_err(|_| SchematicError::MissingCredential {
                            env_vars: vec![password_env.to_string()],
                        })?;
                    req_builder = req_builder.basic_auth(username, Some(password));
                }
                _ => {}
            }
        }
        let api_headers = self.headers.clone().from_env().build()?;
        let merged_headers = Self::merge_headers(&api_headers, &endpoint_headers);
        for (key, value) in merged_headers {
            req_builder = req_builder.header(key.as_str(), value.as_str());
        }
        if let Some(body) = body {
            req_builder = req_builder
                .header("Content-Type", "application/json")
                .body(body);
        }
        let response = req_builder.send().await?;
        if !response.status().is_success() {
            let status = response.status().as_u16();
            let body_text = response.text().await.unwrap_or_default();
            return Err(SchematicError::ApiError {
                status,
                body: body_text,
            });
        }
        let status = response.status().as_u16();
        let headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();
        let ctx = crate::shared::ResponseContext::new(
            endpoint_id,
            method,
            path.clone(),
            url,
            status,
            headers,
        );
        Ok((response, ctx))
    }
    /// Merges API-level and endpoint-level headers.
    ///
    /// Endpoint headers override API headers for matching keys (case-insensitive).
    /// Returns a new Vec with the merged headers.
    fn merge_headers(
        api_headers: &[(String, String)],
        endpoint_headers: &[(String, String)],
    ) -> Vec<(String, String)> {
        let mut result: Vec<(String, String)> = Vec::new();
        for (api_key, api_value) in api_headers {
            let has_override = endpoint_headers
                .iter()
                .any(|(k, _)| k.eq_ignore_ascii_case(api_key));
            if !has_override {
                result.push((api_key.clone(), api_value.clone()));
            }
        }
        for (key, value) in endpoint_headers {
            result.push((key.clone(), value.clone()));
        }
        result
    }
    /// Executes an API request expecting a JSON response.
    ///
    /// Takes any request type that can be converted into the request enum
    /// and returns the deserialized response. If response hooks are configured
    /// via the variant builder, they will be applied.
    ///
    /// ## Hooks
    ///
    /// If configured via `variant()`:
    /// - `pre_response_json` - Transforms JSON before deserialization
    /// - `mutate_response` - Mutates the response after deserialization
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The HTTP request fails (network error, timeout, etc.)
    /// - The response indicates a non-success status code
    /// - The response body cannot be deserialized as JSON
    /// - A hook returns an error
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn request<T: serde::de::DeserializeOwned + Send + Sync + 'static>(
        &self,
        request: impl Into<BitbucketRequest>,
    ) -> Result<T, SchematicError> {
        let (response, ctx) = self.build_and_send_request(request).await?;
        let has_pre_hook = self.variant_hooks.pre_response_json.is_some();
        let has_mutator = self
            .variant_hooks
            .response_mutators
            .contains_key(ctx.endpoint_id);
        if has_pre_hook || has_mutator {
            let bytes = response.bytes().await?;
            let mut json_value: serde_json::Value = serde_json::from_slice(&bytes)?;
            if let Some(ref hook) = self.variant_hooks.pre_response_json {
                json_value = hook(&ctx, json_value)?;
            }
            let mut result: T = serde_json::from_value(json_value)?;
            if let Some(mutator) = self
                .variant_hooks
                .response_mutators
                .get(ctx.endpoint_id)
            {
                mutator.mutate(&ctx, &mut result)?;
            }
            Ok(result)
        } else {
            let result = response.json::<T>().await?;
            Ok(result)
        }
    }
    /// Executes an API request expecting a binary response.
    ///
    /// Returns the raw bytes of the response body. Use this for endpoints
    /// that return binary data like audio files, images, or ZIP archives.
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The HTTP request fails (network error, timeout, etc.)
    /// - The response indicates a non-success status code
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn request_bytes(
        &self,
        request: impl Into<BitbucketRequest>,
    ) -> Result<bytes::Bytes, SchematicError> {
        let (response, _ctx) = self.build_and_send_request(request).await?;
        let bytes = response.bytes().await?;
        Ok(bytes)
    }
    /// Executes an API request expecting a plain text response.
    ///
    /// Returns the response body as a String.
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The HTTP request fails (network error, timeout, etc.)
    /// - The response indicates a non-success status code
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn request_text(
        &self,
        request: impl Into<BitbucketRequest>,
    ) -> Result<String, SchematicError> {
        let (response, _ctx) = self.build_and_send_request(request).await?;
        let text = response.text().await?;
        Ok(text)
    }
    /// Convenience method for the `GetFileContentRaw` endpoint.
    ///
    /// Get raw file content at a specific commit
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn get_file_content_raw(
        &self,
        request: GetFileContentRawRequest,
    ) -> Result<String, SchematicError> {
        self.request_text(request).await
    }
    /// Convenience method for the `GetDownload` endpoint.
    ///
    /// Download a file from repository downloads
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn get_download(
        &self,
        request: GetDownloadRequest,
    ) -> Result<bytes::Bytes, SchematicError> {
        self.request_bytes(request).await
    }
}
