// This code was automatically generated by schematic-gen. Do not edit manually.

//! Generated API client for [GitLab](https://docs.gitlab.com/api/rest/).
//!
//! GitLab REST API v4 for repository, MR, issue, and release workflows
//!
//! ## Authentication
//!
//! Uses API key authentication via the `PRIVATE-TOKEN` header. Set via environment variable: `GITLAB_TOKEN` or `GITLAB_PRIVATE_TOKEN`.
//!
//! ## Features
//!
//! **GET**:
//! - `ListRepositoryTree` - List repository tree recursively (files and directories)
//! - `GetRepositoryFile` - Get file content (Base64 encoded, provide git_ref for branch/tag)
//! - `ListMergeRequests` - List merge requests with metadata
//! - `GetMergeRequest` - Get a single merge request by IID
//! - `ListMergeRequestCommits` - List commits in a merge request
//! - `ListMergeRequestChanges` - Get merge request with file changes/diffs
//! - `ListIssues` - List issues
//! - `GetIssue` - Get a single issue by IID
//! - `ListIssueNotes` - List comments/notes on an issue
//! - `ListIssueParticipants` - List participants on an issue
//! - `ListTags` - List repository tags (check `release` field for release tags)
//! - `GetTag` - Get a single tag by name
//! - `ListReleases` - List releases
//! - `GetRelease` - Get a single release by tag name
//! - `GetLatestRelease` - Get the latest release
//!
//! ## Example
//!
//! ```ignore
//! use schematic_schema::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), SchematicError> {
//!     let client = GitLab::new();
//!     let response = client.list_repository_tree().await?;
//!     println!("{:?}", response);
//!     Ok(())
//! }
//! ```
use serde::{Deserialize, Serialize};
pub use schematic_definitions::gitlab::*;
use crate::shared::{Paginated, RequestParts, SchematicError};
/// Request for `ListRepositoryTree` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListRepositoryTreeRequest;
///
/// let request = ListRepositoryTreeRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_recursive(/* value */)
///     .with_git_ref(/* value */)
///     .with_path(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListRepositoryTreeRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Include files from subdirectories recursively
    pub recursive: Option<bool>,
    /// Query parameter: Branch, tag, or commit SHA to list tree for
    pub git_ref: Option<String>,
    /// Query parameter: Subdirectory path to list
    pub path: Option<String>,
}
impl ListRepositoryTreeRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            recursive: None,
            git_ref: None,
            path: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `recursive` query parameter.
    pub fn with_recursive(mut self, value: bool) -> Self {
        self.recursive = Some(value);
        self
    }
    /// Sets the `git_ref` query parameter.
    pub fn with_git_ref(mut self, value: String) -> Self {
        self.git_ref = Some(value);
        self
    }
    /// Sets the `path` query parameter.
    pub fn with_path(mut self, value: String) -> Self {
        self.path = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/repository/tree", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.recursive {
            query_pairs.push(("recursive", value.to_string()));
        }
        if let Some(ref value) = self.git_ref {
            query_pairs.push(("git_ref", value.to_string()));
        }
        if let Some(ref value) = self.path {
            query_pairs.push(("path", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListRepositoryTreeRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            recursive: None,
            git_ref: None,
            path: None,
        }
    }
}
impl From<String> for ListRepositoryTreeRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            recursive: None,
            git_ref: None,
            path: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListRepositoryTreeRequest {
    type Response = Vec<TreeItem>;
    const ENDPOINT_ID: &'static str = "ListRepositoryTree";
}
/// Request for `GetRepositoryFile` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::GetRepositoryFileRequest;
///
/// let request = GetRepositoryFileRequest::new("id_value", "file_path_value", "git_ref_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryFileRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: file_path
    pub file_path: String,
    /// Path parameter: git_ref
    pub git_ref: String,
}
impl GetRepositoryFileRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        id: impl Into<String>,
        file_path: impl Into<String>,
        git_ref: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            file_path: file_path.into(),
            git_ref: git_ref.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/repository/files/{}?ref={}", self.id, self.file_path, self
            .git_ref
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetRepositoryFileRequest {
    type Response = FileContent;
    const ENDPOINT_ID: &'static str = "GetRepositoryFile";
}
/// Request for `ListMergeRequests` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListMergeRequestsRequest;
///
/// let request = ListMergeRequestsRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_state(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListMergeRequestsRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Filter by merge request state
    pub state: Option<String>,
}
impl ListMergeRequestsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            state: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `state` query parameter.
    pub fn with_state(mut self, value: String) -> Self {
        self.state = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/merge_requests", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.state {
            query_pairs.push(("state", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListMergeRequestsRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl From<String> for ListMergeRequestsRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListMergeRequestsRequest {
    type Response = Vec<MergeRequest>;
    const ENDPOINT_ID: &'static str = "ListMergeRequests";
}
/// Request for `GetMergeRequest` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::GetMergeRequestRequest;
///
/// let request = GetMergeRequestRequest::new("id_value", "merge_request_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetMergeRequestRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: merge_request_iid
    pub merge_request_iid: String,
}
impl GetMergeRequestRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, merge_request_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            merge_request_iid: merge_request_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/merge_requests/{}", self.id, self.merge_request_iid
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetMergeRequestRequest {
    type Response = MergeRequest;
    const ENDPOINT_ID: &'static str = "GetMergeRequest";
}
/// Request for `ListMergeRequestCommits` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListMergeRequestCommitsRequest;
///
/// let request = ListMergeRequestCommitsRequest::new("id_value", "merge_request_iid_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListMergeRequestCommitsRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: merge_request_iid
    pub merge_request_iid: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListMergeRequestCommitsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, merge_request_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            merge_request_iid: merge_request_iid.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!(
            "/projects/{}/merge_requests/{}/commits", self.id, self.merge_request_iid
        );
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListMergeRequestCommitsRequest {
    type Response = Vec<Commit>;
    const ENDPOINT_ID: &'static str = "ListMergeRequestCommits";
}
/// Request for `ListMergeRequestChanges` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListMergeRequestChangesRequest;
///
/// let request = ListMergeRequestChangesRequest::new("id_value", "merge_request_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListMergeRequestChangesRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: merge_request_iid
    pub merge_request_iid: String,
}
impl ListMergeRequestChangesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, merge_request_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            merge_request_iid: merge_request_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/merge_requests/{}/changes", self.id, self.merge_request_iid
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListMergeRequestChangesRequest {
    type Response = MergeRequestChanges;
    const ENDPOINT_ID: &'static str = "ListMergeRequestChanges";
}
/// Request for `ListIssues` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListIssuesRequest;
///
/// let request = ListIssuesRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_state(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssuesRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Filter by issue state
    pub state: Option<String>,
}
impl ListIssuesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            state: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `state` query parameter.
    pub fn with_state(mut self, value: String) -> Self {
        self.state = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/issues", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.state {
            query_pairs.push(("state", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListIssuesRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl From<String> for ListIssuesRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListIssuesRequest {
    type Response = Vec<Issue>;
    const ENDPOINT_ID: &'static str = "ListIssues";
}
/// Request for `GetIssue` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::GetIssueRequest;
///
/// let request = GetIssueRequest::new("id_value", "issue_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetIssueRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: issue_iid
    pub issue_iid: String,
}
impl GetIssueRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, issue_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            issue_iid: issue_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/issues/{}", self.id, self.issue_iid);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetIssueRequest {
    type Response = Issue;
    const ENDPOINT_ID: &'static str = "GetIssue";
}
/// Request for `ListIssueNotes` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListIssueNotesRequest;
///
/// let request = ListIssueNotesRequest::new("id_value", "issue_iid_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssueNotesRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: issue_iid
    pub issue_iid: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListIssueNotesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, issue_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            issue_iid: issue_iid.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/issues/{}/notes", self.id, self.issue_iid);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssueNotesRequest {
    type Response = Vec<Note>;
    const ENDPOINT_ID: &'static str = "ListIssueNotes";
}
/// Request for `ListIssueParticipants` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListIssueParticipantsRequest;
///
/// let request = ListIssueParticipantsRequest::new("id_value", "issue_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssueParticipantsRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: issue_iid
    pub issue_iid: String,
}
impl ListIssueParticipantsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, issue_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            issue_iid: issue_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/issues/{}/participants", self.id, self.issue_iid
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssueParticipantsRequest {
    type Response = Vec<User>;
    const ENDPOINT_ID: &'static str = "ListIssueParticipants";
}
/// Request for `ListTags` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListTagsRequest;
///
/// let request = ListTagsRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListTagsRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListTagsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/repository/tags", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListTagsRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
        }
    }
}
impl From<String> for ListTagsRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListTagsRequest {
    type Response = Vec<Tag>;
    const ENDPOINT_ID: &'static str = "ListTags";
}
/// Request for `GetTag` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::GetTagRequest;
///
/// let request = GetTagRequest::new("id_value", "tag_name_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetTagRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: tag_name
    pub tag_name: String,
}
impl GetTagRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, tag_name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            tag_name: tag_name.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/repository/tags/{}", self.id, self.tag_name);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetTagRequest {
    type Response = Tag;
    const ENDPOINT_ID: &'static str = "GetTag";
}
/// Request for `ListReleases` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::ListReleasesRequest;
///
/// let request = ListReleasesRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListReleasesRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListReleasesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/releases", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListReleasesRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
        }
    }
}
impl From<String> for ListReleasesRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListReleasesRequest {
    type Response = Vec<Release>;
    const ENDPOINT_ID: &'static str = "ListReleases";
}
/// Request for `GetRelease` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::GetReleaseRequest;
///
/// let request = GetReleaseRequest::new("id_value", "tag_name_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetReleaseRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: tag_name
    pub tag_name: String,
}
impl GetReleaseRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, tag_name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            tag_name: tag_name.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/releases/{}", self.id, self.tag_name);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetReleaseRequest {
    type Response = Release;
    const ENDPOINT_ID: &'static str = "GetRelease";
}
/// Request for `GetLatestRelease` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::gitlab::GetLatestReleaseRequest;
///
/// let request = GetLatestReleaseRequest::new("id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetLatestReleaseRequest {
    /// Path parameter: id
    pub id: String,
}
impl GetLatestReleaseRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/releases/permalink/latest", self.id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetLatestReleaseRequest {
    fn from(param: &str) -> Self {
        Self { id: param.to_string() }
    }
}
impl From<String> for GetLatestReleaseRequest {
    fn from(param: String) -> Self {
        Self { id: param }
    }
}
impl crate::shared::EndpointSpec for GetLatestReleaseRequest {
    type Response = Release;
    const ENDPOINT_ID: &'static str = "GetLatestRelease";
}
impl Paginated for ListRepositoryTreeRequest {}
impl Paginated for ListMergeRequestsRequest {}
impl Paginated for ListMergeRequestCommitsRequest {}
impl Paginated for ListIssuesRequest {}
impl Paginated for ListIssueNotesRequest {}
impl Paginated for ListTagsRequest {}
impl Paginated for ListReleasesRequest {}
/// Request enum for GitLab API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum GitLabRequest {
    /// List repository tree recursively (files and directories)
    ListRepositoryTree(ListRepositoryTreeRequest),
    /// Get file content (Base64 encoded, provide git_ref for branch/tag)
    GetRepositoryFile(GetRepositoryFileRequest),
    /// List merge requests with metadata
    ListMergeRequests(ListMergeRequestsRequest),
    /// Get a single merge request by IID
    GetMergeRequest(GetMergeRequestRequest),
    /// List commits in a merge request
    ListMergeRequestCommits(ListMergeRequestCommitsRequest),
    /// Get merge request with file changes/diffs
    ListMergeRequestChanges(ListMergeRequestChangesRequest),
    /// List issues
    ListIssues(ListIssuesRequest),
    /// Get a single issue by IID
    GetIssue(GetIssueRequest),
    /// List comments/notes on an issue
    ListIssueNotes(ListIssueNotesRequest),
    /// List participants on an issue
    ListIssueParticipants(ListIssueParticipantsRequest),
    /// List repository tags (check `release` field for release tags)
    ListTags(ListTagsRequest),
    /// Get a single tag by name
    GetTag(GetTagRequest),
    /// List releases
    ListReleases(ListReleasesRequest),
    /// Get a single release by tag name
    GetRelease(GetReleaseRequest),
    /// Get the latest release
    GetLatestRelease(GetLatestReleaseRequest),
}
impl GitLabRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::ListRepositoryTree(req) => req.into_parts(),
            Self::GetRepositoryFile(req) => req.into_parts(),
            Self::ListMergeRequests(req) => req.into_parts(),
            Self::GetMergeRequest(req) => req.into_parts(),
            Self::ListMergeRequestCommits(req) => req.into_parts(),
            Self::ListMergeRequestChanges(req) => req.into_parts(),
            Self::ListIssues(req) => req.into_parts(),
            Self::GetIssue(req) => req.into_parts(),
            Self::ListIssueNotes(req) => req.into_parts(),
            Self::ListIssueParticipants(req) => req.into_parts(),
            Self::ListTags(req) => req.into_parts(),
            Self::GetTag(req) => req.into_parts(),
            Self::ListReleases(req) => req.into_parts(),
            Self::GetRelease(req) => req.into_parts(),
            Self::GetLatestRelease(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::ListRepositoryTree(_) => {
                <ListRepositoryTreeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetRepositoryFile(_) => {
                <GetRepositoryFileRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListMergeRequests(_) => {
                <ListMergeRequestsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetMergeRequest(_) => {
                <GetMergeRequestRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListMergeRequestCommits(_) => {
                <ListMergeRequestCommitsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListMergeRequestChanges(_) => {
                <ListMergeRequestChangesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssues(_) => {
                <ListIssuesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetIssue(_) => {
                <GetIssueRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssueNotes(_) => {
                <ListIssueNotesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssueParticipants(_) => {
                <ListIssueParticipantsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListTags(_) => {
                <ListTagsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetTag(_) => {
                <GetTagRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListReleases(_) => {
                <ListReleasesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetRelease(_) => {
                <GetReleaseRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetLatestRelease(_) => {
                <GetLatestReleaseRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
}
impl From<ListRepositoryTreeRequest> for GitLabRequest {
    fn from(req: ListRepositoryTreeRequest) -> Self {
        Self::ListRepositoryTree(req)
    }
}
impl From<GetRepositoryFileRequest> for GitLabRequest {
    fn from(req: GetRepositoryFileRequest) -> Self {
        Self::GetRepositoryFile(req)
    }
}
impl From<ListMergeRequestsRequest> for GitLabRequest {
    fn from(req: ListMergeRequestsRequest) -> Self {
        Self::ListMergeRequests(req)
    }
}
impl From<GetMergeRequestRequest> for GitLabRequest {
    fn from(req: GetMergeRequestRequest) -> Self {
        Self::GetMergeRequest(req)
    }
}
impl From<ListMergeRequestCommitsRequest> for GitLabRequest {
    fn from(req: ListMergeRequestCommitsRequest) -> Self {
        Self::ListMergeRequestCommits(req)
    }
}
impl From<ListMergeRequestChangesRequest> for GitLabRequest {
    fn from(req: ListMergeRequestChangesRequest) -> Self {
        Self::ListMergeRequestChanges(req)
    }
}
impl From<ListIssuesRequest> for GitLabRequest {
    fn from(req: ListIssuesRequest) -> Self {
        Self::ListIssues(req)
    }
}
impl From<GetIssueRequest> for GitLabRequest {
    fn from(req: GetIssueRequest) -> Self {
        Self::GetIssue(req)
    }
}
impl From<ListIssueNotesRequest> for GitLabRequest {
    fn from(req: ListIssueNotesRequest) -> Self {
        Self::ListIssueNotes(req)
    }
}
impl From<ListIssueParticipantsRequest> for GitLabRequest {
    fn from(req: ListIssueParticipantsRequest) -> Self {
        Self::ListIssueParticipants(req)
    }
}
impl From<ListTagsRequest> for GitLabRequest {
    fn from(req: ListTagsRequest) -> Self {
        Self::ListTags(req)
    }
}
impl From<GetTagRequest> for GitLabRequest {
    fn from(req: GetTagRequest) -> Self {
        Self::GetTag(req)
    }
}
impl From<ListReleasesRequest> for GitLabRequest {
    fn from(req: ListReleasesRequest) -> Self {
        Self::ListReleases(req)
    }
}
impl From<GetReleaseRequest> for GitLabRequest {
    fn from(req: GetReleaseRequest) -> Self {
        Self::GetRelease(req)
    }
}
impl From<GetLatestReleaseRequest> for GitLabRequest {
    fn from(req: GetLatestReleaseRequest) -> Self {
        Self::GetLatestRelease(req)
    }
}
/// GitLab REST API v4 for repository, MR, issue, and release workflows client.
pub struct GitLab {
    client: reqwest::Client,
    base_url: String,
    /// Environment variable names for authentication credentials.
    env_auth: Vec<String>,
    /// Authentication strategy for this API client.
    auth_strategy: schematic_define::AuthStrategy,
    /// Environment variable for Basic auth username.
    env_username: Option<String>,
    /// Headers builder with environment variable support for credentials.
    headers: schematic_define::Headers,
    /// Variant-specific hooks for response customization.
    variant_hooks: crate::shared::VariantHooks,
}
impl GitLab {
    /// Base URL for the API.
    pub const BASE_URL: &'static str = "https://gitlab.com/api/v4";
    /// Official API documentation URL, if available.
    pub const DOCS_URL: Option<&'static str> = Some("https://docs.gitlab.com/api/rest/");
    /// Creates a new API client with the default base URL.
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN".to_string()
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(
                            vec![
                                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN"
                                .to_string()
                            ],
                        ),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a custom base URL.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let client = Api::with_base_url("http://localhost:8080/v1");
    /// ```
    pub fn with_base_url(base_url: impl Into<String>) -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: base_url.into(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN".to_string()
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(
                            vec![
                                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN"
                                .to_string()
                            ],
                        ),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client.
    ///
    /// Use this when you need custom timeouts, connection pools, or middleware.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client(custom_client);
    /// ```
    pub fn with_client(client: reqwest::Client) -> Self {
        Self {
            client,
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN".to_string()
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(
                            vec![
                                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN"
                                .to_string()
                            ],
                        ),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client and custom base URL.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client_and_base_url(custom_client, "http://localhost:8080");
    /// ```
    pub fn with_client_and_base_url(
        client: reqwest::Client,
        base_url: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN".to_string()
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(
                            vec![
                                "GITLAB_TOKEN".to_string(), "GITLAB_PRIVATE_TOKEN"
                                .to_string()
                            ],
                        ),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a variant builder for customizing this API client.
    ///
    /// The builder pattern allows fluent configuration of:
    /// - Base URL (for proxies, mock servers, or different environments)
    /// - Authentication credentials (different env var names)
    /// - Authentication strategy
    /// - Response hooks for JSON transformation and mutation
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::UpdateStrategy;
    ///
    /// let api = Api::new();
    ///
    /// // Create a variant pointing to a staging server with a response hook
    /// let staging = api.variant()
    ///     .base_url("https://staging.api.com/v1")
    ///     .env_auth(vec!["STAGING_API_KEY".to_string()])
    ///     .mutate_response::<ListModelsRequest>(|ctx, response| {
    ///         response.data.retain(|m| !m.id.contains("deprecated"));
    ///         Ok(())
    ///     })
    ///     .build();
    /// ```
    #[must_use]
    pub fn variant(&self) -> GitLabVariantBuilder<'_> {
        GitLabVariantBuilder::new(self)
    }
    /// Creates a variant of this API client with different configuration.
    ///
    /// This is a convenience method equivalent to:
    /// ```ignore
    /// api.variant()
    ///     .base_url(base_url)
    ///     .env_auth(env_auth)
    ///     .auth_update(strategy)
    ///     .build()
    /// ```
    ///
    /// ## Arguments
    ///
    /// * `base_url` - New base URL for this variant
    /// * `env_auth` - New environment variable names for credentials
    /// * `strategy` - How to update the auth strategy:
    ///   - `UpdateStrategy::NoChange` - Keep current auth strategy
    ///   - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    pub fn variant_with(
        &self,
        base_url: impl Into<String>,
        env_auth: Vec<String>,
        strategy: schematic_define::UpdateStrategy,
    ) -> Self {
        self.variant()
            .base_url(base_url)
            .env_auth(env_auth)
            .auth_update(strategy)
            .build()
    }
    /// Creates a variant of this API client with custom headers configuration.
    ///
    /// This is a convenience method for creating variants with fully customized
    /// headers, including environment variable mapping for credentials.
    ///
    /// ## Arguments
    ///
    /// * `headers` - Headers builder with environment mapping configured
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::{Headers, EnvMapping, EnvList};
    ///
    /// let custom_headers = Headers::default()
    ///     .with_env_mapping(EnvMapping {
    ///         bearer_token: Some(EnvList::single("STAGING_TOKEN")),
    ///         basic_user: None,
    ///         basic_pass: None,
    ///         api_key: None,
    ///     })
    ///     .header("X-Environment", "staging");
    ///
    /// let staging_client = api.variant_with_headers(custom_headers);
    /// ```
    pub fn variant_with_headers(&self, headers: schematic_define::Headers) -> Self {
        self.variant().headers_builder(headers).build()
    }
    /// Returns a reference to the underlying HTTP client.
    ///
    /// Use this for custom requests that aren't covered by the generated methods,
    /// such as paginated endpoints that require query parameters.
    pub fn http_client(&self) -> &reqwest::Client {
        &self.client
    }
    /// Returns the base URL for this API client.
    pub fn api_base_url(&self) -> &str {
        &self.base_url
    }
    /// Returns the API key header name and value for authentication.
    ///
    /// Returns `None` if the authentication strategy is not `ApiKey`
    /// or if the API key environment variable is not set.
    pub fn api_key_header(&self) -> Option<(String, String)> {
        match &self.auth_strategy {
            schematic_define::AuthStrategy::ApiKey { header } => {
                for env_name in &self.env_auth {
                    if let Ok(value) = std::env::var(env_name) {
                        return Some((header.clone(), value));
                    }
                }
                None
            }
            _ => None,
        }
    }
}
impl Default for GitLab {
    fn default() -> Self {
        Self::new()
    }
}
/// Builder for creating customized variants of the API client.
///
/// Use [`#struct_name::variant()`] to create a builder, then chain
/// configuration methods and call [`build()`](Self::build) to create
/// the variant client.
pub struct GitLabVariantBuilder<'a> {
    base: &'a GitLab,
    base_url: Option<String>,
    env_auth: Option<Vec<String>>,
    auth_update: schematic_define::UpdateStrategy,
    headers: Option<schematic_define::Headers>,
    pre_response_json: Option<std::sync::Arc<crate::shared::PreResponseJsonHook>>,
    response_mutators: std::collections::HashMap<
        &'static str,
        std::sync::Arc<dyn crate::shared::AnyResponseMutator>,
    >,
}
impl<'a> GitLabVariantBuilder<'a> {
    /// Creates a new variant builder from the base API client.
    fn new(base: &'a GitLab) -> Self {
        Self {
            base,
            base_url: None,
            env_auth: None,
            auth_update: schematic_define::UpdateStrategy::NoChange,
            headers: None,
            pre_response_json: None,
            response_mutators: std::collections::HashMap::new(),
        }
    }
    /// Sets the base URL for the variant.
    ///
    /// If not set, the original client's base URL is used.
    #[must_use]
    pub fn base_url(mut self, url: impl Into<String>) -> Self {
        self.base_url = Some(url.into());
        self
    }
    /// Sets the environment variable names for authentication.
    ///
    /// If not set, the original client's env_auth is used.
    #[must_use]
    pub fn env_auth(mut self, env_auth: Vec<String>) -> Self {
        self.env_auth = Some(env_auth);
        self
    }
    /// Sets how the authentication strategy should be updated.
    ///
    /// - `UpdateStrategy::NoChange` - Keep current auth strategy (default)
    /// - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    #[must_use]
    pub fn auth_update(mut self, strategy: schematic_define::UpdateStrategy) -> Self {
        self.auth_update = strategy;
        self
    }
    /// Sets custom headers for the variant using a Headers builder.
    ///
    /// This replaces the entire headers configuration, including environment
    /// variable mapping. If not set, the original client's headers are used.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::{Headers, EnvMapping, EnvList};
    ///
    /// let custom = Headers::default()
    ///     .with_env_mapping(EnvMapping {
    ///         bearer_token: Some(EnvList::single("STAGING_KEY")),
    ///         basic_user: None,
    ///         basic_pass: None,
    ///         api_key: None,
    ///     })
    ///     .header("X-Custom", "value");
    ///
    /// let variant = api.variant().headers_builder(custom).build();
    /// ```
    #[must_use]
    pub fn headers_builder(mut self, headers: schematic_define::Headers) -> Self {
        self.headers = Some(headers);
        self
    }
    /// Sets a pre-response JSON transformation hook.
    ///
    /// This hook runs after receiving an HTTP response but before
    /// deserializing to the response type. Use it to reshape JSON
    /// payloads to match expected structures.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// // Unwrap a { data: ... } envelope
    /// variant.pre_response_json(|ctx, json| {
    ///     Ok(json.get("data").cloned().unwrap_or(json))
    /// })
    /// ```
    #[must_use]
    pub fn pre_response_json<F>(mut self, hook: F) -> Self
    where
        F: Fn(
                &crate::shared::ResponseContext,
                serde_json::Value,
            ) -> Result<serde_json::Value, crate::shared::SchematicError> + Send + Sync
            + 'static,
    {
        self.pre_response_json = Some(std::sync::Arc::new(hook));
        self
    }
    /// Registers a response mutation hook for a specific endpoint.
    ///
    /// This hook runs after deserializing the response and can mutate
    /// the response object in place. The endpoint is identified by its
    /// request type.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// variant.mutate_response::<ListModelsRequest>(|ctx, response| {
    ///     response.data.retain(|m| !m.id.contains("deprecated"));
    ///     Ok(())
    /// })
    /// ```
    #[must_use]
    pub fn mutate_response<R, F>(mut self, hook: F) -> Self
    where
        R: crate::shared::EndpointSpec,
        R::Response: Send + Sync + 'static,
        F: Fn(
                &crate::shared::ResponseContext,
                &mut R::Response,
            ) -> Result<(), crate::shared::SchematicError> + Send + Sync + 'static,
    {
        self.response_mutators
            .insert(
                R::ENDPOINT_ID,
                std::sync::Arc::new(crate::shared::TypedMutator::new(hook)),
            );
        self
    }
    /// Builds the variant API client with the configured options.
    ///
    /// Options not explicitly set will inherit from the base client.
    #[must_use]
    pub fn build(self) -> GitLab {
        let auth_strategy = match self.auth_update {
            schematic_define::UpdateStrategy::NoChange => self.base.auth_strategy.clone(),
            schematic_define::UpdateStrategy::ChangeTo(auth) => auth,
            _ => self.base.auth_strategy.clone(),
        };
        GitLab {
            client: self.base.client.clone(),
            base_url: self.base_url.unwrap_or_else(|| self.base.base_url.clone()),
            env_auth: self.env_auth.unwrap_or_else(|| self.base.env_auth.clone()),
            auth_strategy,
            env_username: self.base.env_username.clone(),
            headers: self.headers.unwrap_or_else(|| self.base.headers.clone()),
            variant_hooks: crate::shared::VariantHooks {
                pre_response_json: self.pre_response_json,
                response_mutators: self.response_mutators,
            },
        }
    }
}
impl GitLab {
    /// Builds and sends an HTTP request, returning the raw response plus context.
    ///
    /// This is an internal helper method used by the public request methods.
    /// Returns both the response and the context needed for hook processing.
    async fn build_and_send_request(
        &self,
        request: impl Into<GitLabRequest>,
    ) -> Result<(reqwest::Response, crate::shared::ResponseContext), SchematicError> {
        let request = request.into();
        let endpoint_id = request.endpoint_id();
        let (method, path, body, endpoint_headers) = request.into_parts()?;
        let url = format!("{}{}", self.base_url, path);
        let mut req_builder = match method {
            "GET" => self.client.get(&url),
            "POST" => self.client.post(&url),
            "PUT" => self.client.put(&url),
            "PATCH" => self.client.patch(&url),
            "DELETE" => self.client.delete(&url),
            "HEAD" => self.client.head(&url),
            "OPTIONS" => self.client.request(reqwest::Method::OPTIONS, &url),
            _ => return Err(SchematicError::UnsupportedMethod(method.to_string())),
        };
        if !self.headers.has_authorization() {
            match &self.auth_strategy {
                schematic_define::AuthStrategy::None => {}
                schematic_define::AuthStrategy::BearerToken { header } => {
                    let header_name = header.as_deref().unwrap_or("Authorization");
                    let token = self
                        .env_auth
                        .iter()
                        .find_map(|var| std::env::var(var).ok())
                        .ok_or_else(|| SchematicError::MissingCredential {
                            env_vars: self.env_auth.clone(),
                        })?;
                    req_builder = req_builder
                        .header(header_name, format!("Bearer {}", token));
                }
                schematic_define::AuthStrategy::ApiKey { header } => {
                    let key = self
                        .env_auth
                        .iter()
                        .find_map(|var| std::env::var(var).ok())
                        .ok_or_else(|| SchematicError::MissingCredential {
                            env_vars: self.env_auth.clone(),
                        })?;
                    req_builder = req_builder.header(header.as_str(), key);
                }
                schematic_define::AuthStrategy::Basic => {
                    let username_env = self
                        .env_username
                        .as_deref()
                        .unwrap_or("USERNAME");
                    let password_env = self
                        .env_auth
                        .first()
                        .map(String::as_str)
                        .unwrap_or("PASSWORD");
                    let username = std::env::var(username_env)
                        .map_err(|_| SchematicError::MissingCredential {
                            env_vars: vec![username_env.to_string()],
                        })?;
                    let password = std::env::var(password_env)
                        .map_err(|_| SchematicError::MissingCredential {
                            env_vars: vec![password_env.to_string()],
                        })?;
                    req_builder = req_builder.basic_auth(username, Some(password));
                }
                _ => {}
            }
        }
        let api_headers = self.headers.clone().from_env().build()?;
        let merged_headers = Self::merge_headers(&api_headers, &endpoint_headers);
        for (key, value) in merged_headers {
            req_builder = req_builder.header(key.as_str(), value.as_str());
        }
        if let Some(body) = body {
            req_builder = req_builder
                .header("Content-Type", "application/json")
                .body(body);
        }
        let response = req_builder.send().await?;
        if !response.status().is_success() {
            let status = response.status().as_u16();
            let body_text = response.text().await.unwrap_or_default();
            return Err(SchematicError::ApiError {
                status,
                body: body_text,
            });
        }
        let status = response.status().as_u16();
        let headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();
        let ctx = crate::shared::ResponseContext::new(
            endpoint_id,
            method,
            path.clone(),
            url,
            status,
            headers,
        );
        Ok((response, ctx))
    }
    /// Merges API-level and endpoint-level headers.
    ///
    /// Endpoint headers override API headers for matching keys (case-insensitive).
    /// Returns a new Vec with the merged headers.
    fn merge_headers(
        api_headers: &[(String, String)],
        endpoint_headers: &[(String, String)],
    ) -> Vec<(String, String)> {
        let mut result: Vec<(String, String)> = Vec::new();
        for (api_key, api_value) in api_headers {
            let has_override = endpoint_headers
                .iter()
                .any(|(k, _)| k.eq_ignore_ascii_case(api_key));
            if !has_override {
                result.push((api_key.clone(), api_value.clone()));
            }
        }
        for (key, value) in endpoint_headers {
            result.push((key.clone(), value.clone()));
        }
        result
    }
    /// Executes an API request expecting a JSON response.
    ///
    /// Takes any request type that can be converted into the request enum
    /// and returns the deserialized response. If response hooks are configured
    /// via the variant builder, they will be applied.
    ///
    /// ## Hooks
    ///
    /// If configured via `variant()`:
    /// - `pre_response_json` - Transforms JSON before deserialization
    /// - `mutate_response` - Mutates the response after deserialization
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The HTTP request fails (network error, timeout, etc.)
    /// - The response indicates a non-success status code
    /// - The response body cannot be deserialized as JSON
    /// - A hook returns an error
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn request<T: serde::de::DeserializeOwned + Send + Sync + 'static>(
        &self,
        request: impl Into<GitLabRequest>,
    ) -> Result<T, SchematicError> {
        let (response, ctx) = self.build_and_send_request(request).await?;
        let has_pre_hook = self.variant_hooks.pre_response_json.is_some();
        let has_mutator = self
            .variant_hooks
            .response_mutators
            .contains_key(ctx.endpoint_id);
        if has_pre_hook || has_mutator {
            let bytes = response.bytes().await?;
            let mut json_value: serde_json::Value = serde_json::from_slice(&bytes)?;
            if let Some(ref hook) = self.variant_hooks.pre_response_json {
                json_value = hook(&ctx, json_value)?;
            }
            let mut result: T = serde_json::from_value(json_value)?;
            if let Some(mutator) = self
                .variant_hooks
                .response_mutators
                .get(ctx.endpoint_id)
            {
                mutator.mutate(&ctx, &mut result)?;
            }
            Ok(result)
        } else {
            let result = response.json::<T>().await?;
            Ok(result)
        }
    }
}
