// This code was automatically generated by schematic-gen. Do not edit manually.

//! Generated API client for [GitLab](https://docs.gitlab.com/api/rest/).
//!
//! GitLab REST API v4 for repository, MR, issue, and release workflows
//!
//! ## Authentication
//!
//! Uses API key authentication via the `PRIVATE-TOKEN` header. Set via environment variable: `GITLAB_TOKEN` or `GITLAB_PRIVATE_TOKEN`.
//!
//! ## Features
//!
//! **GET**:
//! - `ListRepositoryTree` - List repository tree recursively (files and directories)
//! - `GetRepositoryFile` - Get file content (Base64 encoded, provide git_ref for branch/tag)
//! - `ListMergeRequests` - List merge requests with metadata
//! - `GetMergeRequest` - Get a single merge request by IID
//! - `ListMergeRequestCommits` - List commits in a merge request
//! - `ListMergeRequestChanges` - Get merge request with file changes/diffs
//! - `ListIssues` - List issues
//! - `GetIssue` - Get a single issue by IID
//! - `ListIssueNotes` - List comments/notes on an issue
//! - `ListIssueParticipants` - List participants on an issue
//! - `ListTags` - List repository tags (check `release` field for release tags)
//! - `GetTag` - Get a single tag by name
//! - `ListReleases` - List releases
//! - `GetRelease` - Get a single release by tag name
//! - `GetLatestRelease` - Get the latest release
//! - `GetProject` - Get project metadata (use URL-encoded path or numeric ID)
//! - `ListProjectPipelines` - List CI/CD pipelines for a project
//! - `ListGroupProjects` - List projects in a group
//!
//! ## Examples
//!
//! ```text
//! use schematic_schema::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), SchematicError> {
//!     let client = GitLab::new();
//!     let response = client.list_repository_tree().await?;
//!     println!("{:?}", response);
//!     Ok(())
//! }
//! ```
//!
//! ### Override Base URL
//!
//! ```text
//! use schematic_schema::prelude::*;
//!
//! let client = GitLab::with_base_url("https://staging.example.com/v1");
//! ```
use crate::shared::{Paginated, RequestParts, SchematicError};
pub use schematic_definitions::gitlab::*;
use serde::{Deserialize, Serialize};
/// Request for `ListRepositoryTree` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListRepositoryTreeRequest;
///
/// let request = ListRepositoryTreeRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_recursive(/* value */)
///     .with_git_ref(/* value */)
///     .with_path(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListRepositoryTreeRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Include files from subdirectories recursively
    pub recursive: Option<bool>,
    /// Query parameter: Branch, tag, or commit SHA to list tree for
    pub git_ref: Option<String>,
    /// Query parameter: Subdirectory path to list
    pub path: Option<String>,
}
impl ListRepositoryTreeRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            recursive: None,
            git_ref: None,
            path: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `recursive` query parameter.
    pub fn with_recursive(mut self, value: bool) -> Self {
        self.recursive = Some(value);
        self
    }
    /// Sets the `git_ref` query parameter.
    pub fn with_git_ref(mut self, value: String) -> Self {
        self.git_ref = Some(value);
        self
    }
    /// Sets the `path` query parameter.
    pub fn with_path(mut self, value: String) -> Self {
        self.path = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/repository/tree", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.recursive {
            query_pairs.push(("recursive", value.to_string()));
        }
        if let Some(ref value) = self.git_ref {
            query_pairs.push(("git_ref", value.to_string()));
        }
        if let Some(ref value) = self.path {
            query_pairs.push(("path", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListRepositoryTreeRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            recursive: None,
            git_ref: None,
            path: None,
        }
    }
}
impl From<String> for ListRepositoryTreeRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            recursive: None,
            git_ref: None,
            path: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListRepositoryTreeRequest {
    type Response = Vec<TreeItem>;
    const ENDPOINT_ID: &'static str = "ListRepositoryTree";
}
/// Request for `GetRepositoryFile` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetRepositoryFileRequest;
///
/// let request = GetRepositoryFileRequest::new("id_value", "file_path_value", "git_ref_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetRepositoryFileRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: file_path
    pub file_path: String,
    /// Path parameter: git_ref
    pub git_ref: String,
}
impl GetRepositoryFileRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        id: impl Into<String>,
        file_path: impl Into<String>,
        git_ref: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            file_path: file_path.into(),
            git_ref: git_ref.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/repository/files/{}?ref={}",
            self.id, self.file_path, self.git_ref
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetRepositoryFileRequest {
    type Response = FileContent;
    const ENDPOINT_ID: &'static str = "GetRepositoryFile";
}
/// Request for `ListMergeRequests` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListMergeRequestsRequest;
///
/// let request = ListMergeRequestsRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_state(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListMergeRequestsRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Filter by merge request state
    pub state: Option<String>,
}
impl ListMergeRequestsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            state: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `state` query parameter.
    pub fn with_state(mut self, value: String) -> Self {
        self.state = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/merge_requests", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.state {
            query_pairs.push(("state", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListMergeRequestsRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl From<String> for ListMergeRequestsRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListMergeRequestsRequest {
    type Response = Vec<MergeRequest>;
    const ENDPOINT_ID: &'static str = "ListMergeRequests";
}
/// Request for `GetMergeRequest` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetMergeRequestRequest;
///
/// let request = GetMergeRequestRequest::new("id_value", "merge_request_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetMergeRequestRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: merge_request_iid
    pub merge_request_iid: String,
}
impl GetMergeRequestRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, merge_request_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            merge_request_iid: merge_request_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/merge_requests/{}",
            self.id, self.merge_request_iid
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetMergeRequestRequest {
    type Response = MergeRequest;
    const ENDPOINT_ID: &'static str = "GetMergeRequest";
}
/// Request for `ListMergeRequestCommits` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListMergeRequestCommitsRequest;
///
/// let request = ListMergeRequestCommitsRequest::new("id_value", "merge_request_iid_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListMergeRequestCommitsRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: merge_request_iid
    pub merge_request_iid: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListMergeRequestCommitsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, merge_request_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            merge_request_iid: merge_request_iid.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!(
            "/projects/{}/merge_requests/{}/commits",
            self.id, self.merge_request_iid
        );
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListMergeRequestCommitsRequest {
    type Response = Vec<Commit>;
    const ENDPOINT_ID: &'static str = "ListMergeRequestCommits";
}
/// Request for `ListMergeRequestChanges` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListMergeRequestChangesRequest;
///
/// let request = ListMergeRequestChangesRequest::new("id_value", "merge_request_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListMergeRequestChangesRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: merge_request_iid
    pub merge_request_iid: String,
}
impl ListMergeRequestChangesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, merge_request_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            merge_request_iid: merge_request_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/merge_requests/{}/changes",
            self.id, self.merge_request_iid
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListMergeRequestChangesRequest {
    type Response = MergeRequestChanges;
    const ENDPOINT_ID: &'static str = "ListMergeRequestChanges";
}
/// Request for `ListIssues` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListIssuesRequest;
///
/// let request = ListIssuesRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_state(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssuesRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Filter by issue state
    pub state: Option<String>,
}
impl ListIssuesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            state: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `state` query parameter.
    pub fn with_state(mut self, value: String) -> Self {
        self.state = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/issues", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.state {
            query_pairs.push(("state", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListIssuesRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl From<String> for ListIssuesRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            state: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListIssuesRequest {
    type Response = Vec<Issue>;
    const ENDPOINT_ID: &'static str = "ListIssues";
}
/// Request for `GetIssue` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetIssueRequest;
///
/// let request = GetIssueRequest::new("id_value", "issue_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetIssueRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: issue_iid
    pub issue_iid: String,
}
impl GetIssueRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, issue_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            issue_iid: issue_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/issues/{}", self.id, self.issue_iid);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetIssueRequest {
    type Response = Issue;
    const ENDPOINT_ID: &'static str = "GetIssue";
}
/// Request for `ListIssueNotes` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListIssueNotesRequest;
///
/// let request = ListIssueNotesRequest::new("id_value", "issue_iid_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssueNotesRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: issue_iid
    pub issue_iid: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListIssueNotesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, issue_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            issue_iid: issue_iid.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/issues/{}/notes", self.id, self.issue_iid);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssueNotesRequest {
    type Response = Vec<Note>;
    const ENDPOINT_ID: &'static str = "ListIssueNotes";
}
/// Request for `ListIssueParticipants` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListIssueParticipantsRequest;
///
/// let request = ListIssueParticipantsRequest::new("id_value", "issue_iid_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListIssueParticipantsRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: issue_iid
    pub issue_iid: String,
}
impl ListIssueParticipantsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, issue_iid: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            issue_iid: issue_iid.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/projects/{}/issues/{}/participants",
            self.id, self.issue_iid
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListIssueParticipantsRequest {
    type Response = Vec<User>;
    const ENDPOINT_ID: &'static str = "ListIssueParticipants";
}
/// Request for `ListTags` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListTagsRequest;
///
/// let request = ListTagsRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListTagsRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListTagsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/repository/tags", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListTagsRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
        }
    }
}
impl From<String> for ListTagsRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListTagsRequest {
    type Response = Vec<Tag>;
    const ENDPOINT_ID: &'static str = "ListTags";
}
/// Request for `GetTag` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetTagRequest;
///
/// let request = GetTagRequest::new("id_value", "tag_name_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetTagRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: tag_name
    pub tag_name: String,
}
impl GetTagRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, tag_name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            tag_name: tag_name.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/repository/tags/{}", self.id, self.tag_name);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetTagRequest {
    type Response = Tag;
    const ENDPOINT_ID: &'static str = "GetTag";
}
/// Request for `ListReleases` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListReleasesRequest;
///
/// let request = ListReleasesRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListReleasesRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
}
impl ListReleasesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/releases", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListReleasesRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
        }
    }
}
impl From<String> for ListReleasesRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListReleasesRequest {
    type Response = Vec<Release>;
    const ENDPOINT_ID: &'static str = "ListReleases";
}
/// Request for `GetRelease` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetReleaseRequest;
///
/// let request = GetReleaseRequest::new("id_value", "tag_name_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetReleaseRequest {
    /// Path parameter: id
    pub id: String,
    /// Path parameter: tag_name
    pub tag_name: String,
}
impl GetReleaseRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>, tag_name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            tag_name: tag_name.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/releases/{}", self.id, self.tag_name);
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetReleaseRequest {
    type Response = Release;
    const ENDPOINT_ID: &'static str = "GetRelease";
}
/// Request for `GetLatestRelease` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetLatestReleaseRequest;
///
/// let request = GetLatestReleaseRequest::new("id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetLatestReleaseRequest {
    /// Path parameter: id
    pub id: String,
}
impl GetLatestReleaseRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}/releases/permalink/latest", self.id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetLatestReleaseRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
        }
    }
}
impl From<String> for GetLatestReleaseRequest {
    fn from(param: String) -> Self {
        Self { id: param }
    }
}
impl crate::shared::EndpointSpec for GetLatestReleaseRequest {
    type Response = Release;
    const ENDPOINT_ID: &'static str = "GetLatestRelease";
}
/// Request for `GetProject` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::GetProjectRequest;
///
/// let request = GetProjectRequest::new("id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetProjectRequest {
    /// Path parameter: id
    pub id: String,
}
impl GetProjectRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/projects/{}", self.id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetProjectRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
        }
    }
}
impl From<String> for GetProjectRequest {
    fn from(param: String) -> Self {
        Self { id: param }
    }
}
impl crate::shared::EndpointSpec for GetProjectRequest {
    type Response = Project;
    const ENDPOINT_ID: &'static str = "GetProject";
}
/// Request for `ListProjectPipelines` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListProjectPipelinesRequest;
///
/// let request = ListProjectPipelinesRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_status(/* value */)
///     .with_source(/* value */)
///     .with_git_ref(/* value */)
///     .with_sha(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListProjectPipelinesRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Filter by pipeline status
    pub status: Option<String>,
    /// Query parameter: Filter by pipeline source (e.g., push, merge_request_event, schedule)
    pub source: Option<String>,
    /// Query parameter: Filter by branch or tag name
    pub git_ref: Option<String>,
    /// Query parameter: Filter by commit SHA
    pub sha: Option<String>,
}
impl ListProjectPipelinesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            status: None,
            source: None,
            git_ref: None,
            sha: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `status` query parameter.
    pub fn with_status(mut self, value: String) -> Self {
        self.status = Some(value);
        self
    }
    /// Sets the `source` query parameter.
    pub fn with_source(mut self, value: String) -> Self {
        self.source = Some(value);
        self
    }
    /// Sets the `git_ref` query parameter.
    pub fn with_git_ref(mut self, value: String) -> Self {
        self.git_ref = Some(value);
        self
    }
    /// Sets the `sha` query parameter.
    pub fn with_sha(mut self, value: String) -> Self {
        self.sha = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/projects/{}/pipelines", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.status {
            query_pairs.push(("status", value.to_string()));
        }
        if let Some(ref value) = self.source {
            query_pairs.push(("source", value.to_string()));
        }
        if let Some(ref value) = self.git_ref {
            query_pairs.push(("git_ref", value.to_string()));
        }
        if let Some(ref value) = self.sha {
            query_pairs.push(("sha", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListProjectPipelinesRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            status: None,
            source: None,
            git_ref: None,
            sha: None,
        }
    }
}
impl From<String> for ListProjectPipelinesRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            status: None,
            source: None,
            git_ref: None,
            sha: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListProjectPipelinesRequest {
    type Response = Vec<Pipeline>;
    const ENDPOINT_ID: &'static str = "ListProjectPipelines";
}
/// Request for `ListGroupProjects` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::gitlab::ListGroupProjectsRequest;
///
/// let request = ListGroupProjectsRequest::new("id_value")
///     .with_page(/* value */)
///     .with_per_page(/* value */)
///     .with_archived(/* value */)
///     .with_visibility(/* value */)
///     .with_order_by(/* value */)
///     .with_sort(/* value */)
///     .with_include_subgroups(/* value */)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListGroupProjectsRequest {
    /// Path parameter: id
    pub id: String,
    /// Query parameter: Page number (1-indexed, default: 1)
    pub page: Option<i64>,
    /// Query parameter: Items per page (default: 100, max: 100)
    pub per_page: Option<i64>,
    /// Query parameter: Filter by archived status
    pub archived: Option<bool>,
    /// Query parameter: Filter by visibility level
    pub visibility: Option<String>,
    /// Query parameter: Sort field
    pub order_by: Option<String>,
    /// Query parameter: Sort direction
    pub sort: Option<String>,
    /// Query parameter: Include projects from subgroups
    pub include_subgroups: Option<bool>,
}
impl ListGroupProjectsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            page: None,
            per_page: None,
            archived: None,
            visibility: None,
            order_by: None,
            sort: None,
            include_subgroups: None,
        }
    }
    /// Sets the `page` query parameter.
    pub fn with_page(mut self, value: i64) -> Self {
        self.page = Some(value);
        self
    }
    /// Sets the `per_page` query parameter.
    pub fn with_per_page(mut self, value: i64) -> Self {
        self.per_page = Some(value);
        self
    }
    /// Sets the `archived` query parameter.
    pub fn with_archived(mut self, value: bool) -> Self {
        self.archived = Some(value);
        self
    }
    /// Sets the `visibility` query parameter.
    pub fn with_visibility(mut self, value: String) -> Self {
        self.visibility = Some(value);
        self
    }
    /// Sets the `order_by` query parameter.
    pub fn with_order_by(mut self, value: String) -> Self {
        self.order_by = Some(value);
        self
    }
    /// Sets the `sort` query parameter.
    pub fn with_sort(mut self, value: String) -> Self {
        self.sort = Some(value);
        self
    }
    /// Sets the `include_subgroups` query parameter.
    pub fn with_include_subgroups(mut self, value: bool) -> Self {
        self.include_subgroups = Some(value);
        self
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let mut path = format!("/groups/{}/projects", self.id);
        let mut query_pairs: Vec<(&str, String)> = Vec::new();
        if let Some(ref value) = self.page {
            query_pairs.push(("page", value.to_string()));
        }
        if let Some(ref value) = self.per_page {
            query_pairs.push(("per_page", value.to_string()));
        }
        if let Some(ref value) = self.archived {
            query_pairs.push(("archived", value.to_string()));
        }
        if let Some(ref value) = self.visibility {
            query_pairs.push(("visibility", value.to_string()));
        }
        if let Some(ref value) = self.order_by {
            query_pairs.push(("order_by", value.to_string()));
        }
        if let Some(ref value) = self.sort {
            query_pairs.push(("sort", value.to_string()));
        }
        if let Some(ref value) = self.include_subgroups {
            query_pairs.push(("include_subgroups", value.to_string()));
        }
        if !query_pairs.is_empty() {
            let query_string: String = query_pairs
                .iter()
                .map(|(k, v)| format!("{}={}", k, urlencoding::encode(v)))
                .collect::<Vec<_>>()
                .join("&");
            if path.contains('?') {
                path.push_str(&format!("&{}", query_string));
            } else {
                path.push_str(&format!("?{}", query_string));
            }
        }
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListGroupProjectsRequest {
    fn from(param: &str) -> Self {
        Self {
            id: param.to_string(),
            page: None,
            per_page: None,
            archived: None,
            visibility: None,
            order_by: None,
            sort: None,
            include_subgroups: None,
        }
    }
}
impl From<String> for ListGroupProjectsRequest {
    fn from(param: String) -> Self {
        Self {
            id: param,
            page: None,
            per_page: None,
            archived: None,
            visibility: None,
            order_by: None,
            sort: None,
            include_subgroups: None,
        }
    }
}
impl crate::shared::EndpointSpec for ListGroupProjectsRequest {
    type Response = Vec<Project>;
    const ENDPOINT_ID: &'static str = "ListGroupProjects";
}
impl Paginated for ListRepositoryTreeRequest {}
impl Paginated for ListMergeRequestsRequest {}
impl Paginated for ListMergeRequestCommitsRequest {}
impl Paginated for ListIssuesRequest {}
impl Paginated for ListIssueNotesRequest {}
impl Paginated for ListTagsRequest {}
impl Paginated for ListReleasesRequest {}
impl Paginated for ListProjectPipelinesRequest {}
impl Paginated for ListGroupProjectsRequest {}
/// Request enum for GitLab API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum GitLabRequest {
    /// List repository tree recursively (files and directories)
    ListRepositoryTree(ListRepositoryTreeRequest),
    /// Get file content (Base64 encoded, provide git_ref for branch/tag)
    GetRepositoryFile(GetRepositoryFileRequest),
    /// List merge requests with metadata
    ListMergeRequests(ListMergeRequestsRequest),
    /// Get a single merge request by IID
    GetMergeRequest(GetMergeRequestRequest),
    /// List commits in a merge request
    ListMergeRequestCommits(ListMergeRequestCommitsRequest),
    /// Get merge request with file changes/diffs
    ListMergeRequestChanges(ListMergeRequestChangesRequest),
    /// List issues
    ListIssues(ListIssuesRequest),
    /// Get a single issue by IID
    GetIssue(GetIssueRequest),
    /// List comments/notes on an issue
    ListIssueNotes(ListIssueNotesRequest),
    /// List participants on an issue
    ListIssueParticipants(ListIssueParticipantsRequest),
    /// List repository tags (check `release` field for release tags)
    ListTags(ListTagsRequest),
    /// Get a single tag by name
    GetTag(GetTagRequest),
    /// List releases
    ListReleases(ListReleasesRequest),
    /// Get a single release by tag name
    GetRelease(GetReleaseRequest),
    /// Get the latest release
    GetLatestRelease(GetLatestReleaseRequest),
    /// Get project metadata (use URL-encoded path or numeric ID)
    GetProject(GetProjectRequest),
    /// List CI/CD pipelines for a project
    ListProjectPipelines(ListProjectPipelinesRequest),
    /// List projects in a group
    ListGroupProjects(ListGroupProjectsRequest),
}
impl GitLabRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::ListRepositoryTree(req) => req.into_parts(),
            Self::GetRepositoryFile(req) => req.into_parts(),
            Self::ListMergeRequests(req) => req.into_parts(),
            Self::GetMergeRequest(req) => req.into_parts(),
            Self::ListMergeRequestCommits(req) => req.into_parts(),
            Self::ListMergeRequestChanges(req) => req.into_parts(),
            Self::ListIssues(req) => req.into_parts(),
            Self::GetIssue(req) => req.into_parts(),
            Self::ListIssueNotes(req) => req.into_parts(),
            Self::ListIssueParticipants(req) => req.into_parts(),
            Self::ListTags(req) => req.into_parts(),
            Self::GetTag(req) => req.into_parts(),
            Self::ListReleases(req) => req.into_parts(),
            Self::GetRelease(req) => req.into_parts(),
            Self::GetLatestRelease(req) => req.into_parts(),
            Self::GetProject(req) => req.into_parts(),
            Self::ListProjectPipelines(req) => req.into_parts(),
            Self::ListGroupProjects(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::ListRepositoryTree(_) => {
                <ListRepositoryTreeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetRepositoryFile(_) => {
                <GetRepositoryFileRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListMergeRequests(_) => {
                <ListMergeRequestsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetMergeRequest(_) => {
                <GetMergeRequestRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListMergeRequestCommits(_) => {
                <ListMergeRequestCommitsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListMergeRequestChanges(_) => {
                <ListMergeRequestChangesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssues(_) => <ListIssuesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID,
            Self::GetIssue(_) => <GetIssueRequest as crate::shared::EndpointSpec>::ENDPOINT_ID,
            Self::ListIssueNotes(_) => {
                <ListIssueNotesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListIssueParticipants(_) => {
                <ListIssueParticipantsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListTags(_) => <ListTagsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID,
            Self::GetTag(_) => <GetTagRequest as crate::shared::EndpointSpec>::ENDPOINT_ID,
            Self::ListReleases(_) => {
                <ListReleasesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetRelease(_) => <GetReleaseRequest as crate::shared::EndpointSpec>::ENDPOINT_ID,
            Self::GetLatestRelease(_) => {
                <GetLatestReleaseRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetProject(_) => <GetProjectRequest as crate::shared::EndpointSpec>::ENDPOINT_ID,
            Self::ListProjectPipelines(_) => {
                <ListProjectPipelinesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListGroupProjects(_) => {
                <ListGroupProjectsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
}
impl From<ListRepositoryTreeRequest> for GitLabRequest {
    fn from(req: ListRepositoryTreeRequest) -> Self {
        Self::ListRepositoryTree(req)
    }
}
impl From<GetRepositoryFileRequest> for GitLabRequest {
    fn from(req: GetRepositoryFileRequest) -> Self {
        Self::GetRepositoryFile(req)
    }
}
impl From<ListMergeRequestsRequest> for GitLabRequest {
    fn from(req: ListMergeRequestsRequest) -> Self {
        Self::ListMergeRequests(req)
    }
}
impl From<GetMergeRequestRequest> for GitLabRequest {
    fn from(req: GetMergeRequestRequest) -> Self {
        Self::GetMergeRequest(req)
    }
}
impl From<ListMergeRequestCommitsRequest> for GitLabRequest {
    fn from(req: ListMergeRequestCommitsRequest) -> Self {
        Self::ListMergeRequestCommits(req)
    }
}
impl From<ListMergeRequestChangesRequest> for GitLabRequest {
    fn from(req: ListMergeRequestChangesRequest) -> Self {
        Self::ListMergeRequestChanges(req)
    }
}
impl From<ListIssuesRequest> for GitLabRequest {
    fn from(req: ListIssuesRequest) -> Self {
        Self::ListIssues(req)
    }
}
impl From<GetIssueRequest> for GitLabRequest {
    fn from(req: GetIssueRequest) -> Self {
        Self::GetIssue(req)
    }
}
impl From<ListIssueNotesRequest> for GitLabRequest {
    fn from(req: ListIssueNotesRequest) -> Self {
        Self::ListIssueNotes(req)
    }
}
impl From<ListIssueParticipantsRequest> for GitLabRequest {
    fn from(req: ListIssueParticipantsRequest) -> Self {
        Self::ListIssueParticipants(req)
    }
}
impl From<ListTagsRequest> for GitLabRequest {
    fn from(req: ListTagsRequest) -> Self {
        Self::ListTags(req)
    }
}
impl From<GetTagRequest> for GitLabRequest {
    fn from(req: GetTagRequest) -> Self {
        Self::GetTag(req)
    }
}
impl From<ListReleasesRequest> for GitLabRequest {
    fn from(req: ListReleasesRequest) -> Self {
        Self::ListReleases(req)
    }
}
impl From<GetReleaseRequest> for GitLabRequest {
    fn from(req: GetReleaseRequest) -> Self {
        Self::GetRelease(req)
    }
}
impl From<GetLatestReleaseRequest> for GitLabRequest {
    fn from(req: GetLatestReleaseRequest) -> Self {
        Self::GetLatestRelease(req)
    }
}
impl From<GetProjectRequest> for GitLabRequest {
    fn from(req: GetProjectRequest) -> Self {
        Self::GetProject(req)
    }
}
impl From<ListProjectPipelinesRequest> for GitLabRequest {
    fn from(req: ListProjectPipelinesRequest) -> Self {
        Self::ListProjectPipelines(req)
    }
}
impl From<ListGroupProjectsRequest> for GitLabRequest {
    fn from(req: ListGroupProjectsRequest) -> Self {
        Self::ListGroupProjects(req)
    }
}
/// GitLab REST API v4 for repository, MR, issue, and release workflows client.
pub struct GitLab {
    client: reqwest::Client,
    base_url: String,
    /// Environment variable names for authentication credentials.
    env_auth: Vec<String>,
    /// Authentication strategy for this API client.
    auth_strategy: schematic_define::AuthStrategy,
    /// Effective authentication policy for this API client.
    auth_policy: schematic_define::AuthPolicy,
    /// Environment variable for Basic auth username.
    env_username: Option<String>,
    /// Headers builder with environment variable support for credentials.
    headers: schematic_define::Headers,
    /// Variant-specific hooks for response customization.
    variant_hooks: crate::shared::VariantHooks,
}
impl GitLab {
    /// Base URL for the API.
    pub const BASE_URL: &'static str = "https://gitlab.com/api/v4";
    /// Official API documentation URL, if available.
    pub const DOCS_URL: Option<&'static str> = Some("https://docs.gitlab.com/api/rest/");
    /// Creates a new API client with the default base URL.
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(),
                "GITLAB_PRIVATE_TOKEN".to_string(),
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            auth_policy: schematic_define::AuthPolicy {
                explicit: vec![schematic_define::AuthMethod::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }],
                env_fallback: Some(schematic_define::EnvAuthStrategy::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(vec![
                            "GITLAB_TOKEN".to_string(),
                            "GITLAB_PRIVATE_TOKEN".to_string(),
                        ]),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                    oauth_client_id: None,
                    oauth_client_secret: None,
                    oauth_redirect_uri: None,
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a custom base URL.
    ///
    /// ## Examples
    ///
    /// ```text
    /// let client = Api::with_base_url("http://localhost:8080/v1");
    /// ```
    pub fn with_base_url(base_url: impl Into<String>) -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: base_url.into(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(),
                "GITLAB_PRIVATE_TOKEN".to_string(),
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            auth_policy: schematic_define::AuthPolicy {
                explicit: vec![schematic_define::AuthMethod::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }],
                env_fallback: Some(schematic_define::EnvAuthStrategy::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(vec![
                            "GITLAB_TOKEN".to_string(),
                            "GITLAB_PRIVATE_TOKEN".to_string(),
                        ]),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                    oauth_client_id: None,
                    oauth_client_secret: None,
                    oauth_redirect_uri: None,
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client.
    ///
    /// Use this when you need custom timeouts, connection pools, or middleware.
    ///
    /// ## Examples
    ///
    /// ```text
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client(custom_client);
    /// ```
    pub fn with_client(client: reqwest::Client) -> Self {
        Self {
            client,
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(),
                "GITLAB_PRIVATE_TOKEN".to_string(),
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            auth_policy: schematic_define::AuthPolicy {
                explicit: vec![schematic_define::AuthMethod::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }],
                env_fallback: Some(schematic_define::EnvAuthStrategy::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(vec![
                            "GITLAB_TOKEN".to_string(),
                            "GITLAB_PRIVATE_TOKEN".to_string(),
                        ]),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                    oauth_client_id: None,
                    oauth_client_secret: None,
                    oauth_redirect_uri: None,
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client and custom base URL.
    ///
    /// ## Examples
    ///
    /// ```text
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client_and_base_url(custom_client, "http://localhost:8080");
    /// ```
    pub fn with_client_and_base_url(client: reqwest::Client, base_url: impl Into<String>) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            env_auth: vec![
                "GITLAB_TOKEN".to_string(),
                "GITLAB_PRIVATE_TOKEN".to_string(),
            ],
            auth_strategy: schematic_define::AuthStrategy::ApiKey {
                header: "PRIVATE-TOKEN".to_string(),
            },
            auth_policy: schematic_define::AuthPolicy {
                explicit: vec![schematic_define::AuthMethod::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }],
                env_fallback: Some(schematic_define::EnvAuthStrategy::ApiKey {
                    header: "PRIVATE-TOKEN".to_string(),
                }),
            },
            env_username: None,
            headers: schematic_define::Headers::default()
                .with_env_mapping(schematic_define::EnvMapping {
                    bearer_token: None,
                    basic_user: None,
                    basic_pass: None,
                    api_key: Some(schematic_define::ApiKeyEnv {
                        names: schematic_define::EnvList::new(vec![
                            "GITLAB_TOKEN".to_string(),
                            "GITLAB_PRIVATE_TOKEN".to_string(),
                        ]),
                        header: "PRIVATE-TOKEN".to_string(),
                    }),
                    oauth_client_id: None,
                    oauth_client_secret: None,
                    oauth_redirect_uri: None,
                })
                .header("User-Agent", "schematic-gitlab-client"),
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a variant builder for customizing this API client.
    ///
    /// The builder pattern allows fluent configuration of:
    /// - Base URL (for proxies, mock servers, or different environments)
    /// - Authentication credentials (different env var names)
    /// - Authentication strategy
    /// - Response hooks for JSON transformation and mutation
    ///
    /// ## Examples
    ///
    /// ```text
    /// use schematic_define::UpdateStrategy;
    ///
    /// let api = Api::new();
    ///
    /// // Create a variant pointing to a staging server with a response hook
    /// let staging = api.variant()
    ///     .base_url("https://staging.api.com/v1")
    ///     .env_auth(vec!["STAGING_API_KEY".to_string()])
    ///     .mutate_response::<ListModelsRequest>(|ctx, response| {
    ///         response.data.retain(|m| !m.id.contains("deprecated"));
    ///         Ok(())
    ///     })
    ///     .build();
    /// ```
    #[must_use]
    pub fn variant(&self) -> GitLabVariantBuilder<'_> {
        GitLabVariantBuilder::new(self)
    }
    /// Creates a variant of this API client with different configuration.
    ///
    /// This is a convenience method equivalent to:
    /// ```text
    /// api.variant()
    ///     .base_url(base_url)
    ///     .env_auth(env_auth)
    ///     .auth_update(strategy)
    ///     .build()
    /// ```
    ///
    /// ## Arguments
    ///
    /// * `base_url` - New base URL for this variant
    /// * `env_auth` - New environment variable names for credentials
    /// * `strategy` - How to update the auth strategy:
    ///   - `UpdateStrategy::NoChange` - Keep current auth strategy
    ///   - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    pub fn variant_with(
        &self,
        base_url: impl Into<String>,
        env_auth: Vec<String>,
        strategy: schematic_define::UpdateStrategy,
    ) -> Self {
        self.variant()
            .base_url(base_url)
            .env_auth(env_auth)
            .auth_update(strategy)
            .build()
    }
    /// Creates a variant of this API client with custom headers configuration.
    ///
    /// This is a convenience method for creating variants with fully customized
    /// headers, including environment variable mapping for credentials.
    ///
    /// ## Arguments
    ///
    /// * `headers` - Headers builder with environment mapping configured
    ///
    /// ## Examples
    ///
    /// ```text
    /// use schematic_define::{Headers, EnvMapping, EnvList};
    ///
    /// let custom_headers = Headers::default()
    ///     .with_env_mapping(EnvMapping {
    ///         bearer_token: Some(EnvList::single("STAGING_TOKEN")),
    ///         basic_user: None,
    ///         basic_pass: None,
    ///         api_key: None,
    ///     })
    ///     .header("X-Environment", "staging");
    ///
    /// let staging_client = api.variant_with_headers(custom_headers);
    /// ```
    pub fn variant_with_headers(&self, headers: schematic_define::Headers) -> Self {
        self.variant().headers_builder(headers).build()
    }
    /// Returns a reference to the underlying HTTP client.
    ///
    /// Use this for custom requests that aren't covered by the generated methods,
    /// such as paginated endpoints that require query parameters.
    pub fn http_client(&self) -> &reqwest::Client {
        &self.client
    }
    /// Returns the base URL for this API client.
    pub fn api_base_url(&self) -> &str {
        &self.base_url
    }
    /// Returns the effective authentication policy for this client.
    pub fn auth_policy(&self) -> &schematic_define::AuthPolicy {
        &self.auth_policy
    }
    /// Returns OAuth2 provider metadata, if this client accepts OAuth tokens.
    pub fn oauth_config(&self) -> Option<&schematic_define::OAuth2Config> {
        self.auth_policy.oauth2()
    }
    /// Returns the API key header name and value for authentication.
    ///
    /// Returns `None` if the authentication strategy is not `ApiKey`
    /// or if the API key environment variable is not set.
    pub fn api_key_header(&self) -> Option<(String, String)> {
        let header = self
            .auth_policy
            .explicit
            .iter()
            .find_map(|method| match method {
                schematic_define::AuthMethod::ApiKey { header } => Some(header.clone()),
                _ => None,
            })
            .or_else(|| {
                self.headers
                    .env_mapping()
                    .api_key
                    .as_ref()
                    .map(|api_key| api_key.header.clone())
            });
        header.and_then(|header| {
            self.headers
                .env_mapping()
                .api_key
                .as_ref()
                .and_then(|api_key| {
                    api_key
                        .names
                        .names()
                        .iter()
                        .find_map(|env_name| std::env::var(env_name).ok())
                })
                .map(|value| (header, value))
        })
    }
    /// Returns a clone of this client configured with an explicit API key.
    #[must_use]
    pub fn api_key(&self, key: impl Into<String>) -> Self {
        self.variant()
            .headers_builder(self.headers.clone().use_api_key(key, "PRIVATE-TOKEN"))
            .build()
    }
}
impl Default for GitLab {
    fn default() -> Self {
        Self::new()
    }
}
/// Builder for creating customized variants of the API client.
///
/// Use [`#struct_name::variant()`] to create a builder, then chain
/// configuration methods and call [`build()`](Self::build) to create
/// the variant client.
pub struct GitLabVariantBuilder<'a> {
    base: &'a GitLab,
    base_url: Option<String>,
    env_auth: Option<Vec<String>>,
    auth_update: schematic_define::UpdateStrategy,
    headers: Option<schematic_define::Headers>,
    pre_response_json: Option<std::sync::Arc<crate::shared::PreResponseJsonHook>>,
    response_mutators: std::collections::HashMap<
        &'static str,
        std::sync::Arc<dyn crate::shared::AnyResponseMutator>,
    >,
}
impl<'a> GitLabVariantBuilder<'a> {
    /// Creates a new variant builder from the base API client.
    fn new(base: &'a GitLab) -> Self {
        Self {
            base,
            base_url: None,
            env_auth: None,
            auth_update: schematic_define::UpdateStrategy::NoChange,
            headers: None,
            pre_response_json: None,
            response_mutators: std::collections::HashMap::new(),
        }
    }
    /// Sets the base URL for the variant.
    ///
    /// If not set, the original client's base URL is used.
    #[must_use]
    pub fn base_url(mut self, url: impl Into<String>) -> Self {
        self.base_url = Some(url.into());
        self
    }
    /// Sets the environment variable names for authentication.
    ///
    /// If not set, the original client's env_auth is used.
    #[must_use]
    pub fn env_auth(mut self, env_auth: Vec<String>) -> Self {
        self.env_auth = Some(env_auth);
        self
    }
    /// Sets how the authentication strategy should be updated.
    ///
    /// - `UpdateStrategy::NoChange` - Keep current auth strategy (default)
    /// - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    #[must_use]
    pub fn auth_update(mut self, strategy: schematic_define::UpdateStrategy) -> Self {
        self.auth_update = strategy;
        self
    }
    /// Sets custom headers for the variant using a Headers builder.
    ///
    /// This replaces the entire headers configuration, including environment
    /// variable mapping. If not set, the original client's headers are used.
    ///
    /// ## Examples
    ///
    /// ```text
    /// use schematic_define::{Headers, EnvMapping, EnvList};
    ///
    /// let custom = Headers::default()
    ///     .with_env_mapping(EnvMapping {
    ///         bearer_token: Some(EnvList::single("STAGING_KEY")),
    ///         basic_user: None,
    ///         basic_pass: None,
    ///         api_key: None,
    ///     })
    ///     .header("X-Custom", "value");
    ///
    /// let variant = api.variant().headers_builder(custom).build();
    /// ```
    #[must_use]
    pub fn headers_builder(mut self, headers: schematic_define::Headers) -> Self {
        self.headers = Some(headers);
        self
    }
    /// Sets a pre-response JSON transformation hook.
    ///
    /// This hook runs after receiving an HTTP response but before
    /// deserializing to the response type. Use it to reshape JSON
    /// payloads to match expected structures.
    ///
    /// ## Examples
    ///
    /// ```text
    /// // Unwrap a { data: ... } envelope
    /// variant.pre_response_json(|ctx, json| {
    ///     Ok(json.get("data").cloned().unwrap_or(json))
    /// })
    /// ```
    #[must_use]
    pub fn pre_response_json<F>(mut self, hook: F) -> Self
    where
        F: Fn(
                &crate::shared::ResponseContext,
                serde_json::Value,
            ) -> Result<serde_json::Value, crate::shared::SchematicError>
            + Send
            + Sync
            + 'static,
    {
        self.pre_response_json = Some(std::sync::Arc::new(hook));
        self
    }
    /// Registers a response mutation hook for a specific endpoint.
    ///
    /// This hook runs after deserializing the response and can mutate
    /// the response object in place. The endpoint is identified by its
    /// request type.
    ///
    /// ## Examples
    ///
    /// ```text
    /// variant.mutate_response::<ListModelsRequest>(|ctx, response| {
    ///     response.data.retain(|m| !m.id.contains("deprecated"));
    ///     Ok(())
    /// })
    /// ```
    #[must_use]
    pub fn mutate_response<R, F>(mut self, hook: F) -> Self
    where
        R: crate::shared::EndpointSpec,
        R::Response: Send + Sync + 'static,
        F: Fn(
                &crate::shared::ResponseContext,
                &mut R::Response,
            ) -> Result<(), crate::shared::SchematicError>
            + Send
            + Sync
            + 'static,
    {
        self.response_mutators.insert(
            R::ENDPOINT_ID,
            std::sync::Arc::new(crate::shared::TypedMutator::new(hook)),
        );
        self
    }
    /// Builds the variant API client with the configured options.
    ///
    /// Options not explicitly set will inherit from the base client.
    #[must_use]
    pub fn build(self) -> GitLab {
        let auth_update = self.auth_update.clone();
        let auth_policy = match auth_update.clone() {
            schematic_define::UpdateStrategy::NoChange => self.base.auth_policy.clone(),
            schematic_define::UpdateStrategy::ChangeTo(ref auth) => {
                schematic_define::AuthPolicy::from_auth_strategy(auth)
            }
            _ => self.base.auth_policy.clone(),
        };
        let auth_strategy = match auth_update.clone() {
            schematic_define::UpdateStrategy::NoChange => self.base.auth_strategy.clone(),
            schematic_define::UpdateStrategy::ChangeTo(auth) => auth,
            _ => self.base.auth_strategy.clone(),
        };
        let has_env_auth_override = self.env_auth.is_some();
        let env_auth = self.env_auth.unwrap_or_else(|| self.base.env_auth.clone());
        let headers = match self.headers {
            Some(headers) => headers,
            None if has_env_auth_override
                || !matches!(auth_update, schematic_define::UpdateStrategy::NoChange) =>
            {
                self.base.headers.clone().with_env_mapping(
                    schematic_define::RestApi::legacy_env_mapping_for(
                        &auth_strategy,
                        &env_auth,
                        self.base.env_username.as_deref(),
                    ),
                )
            }
            None => self.base.headers.clone(),
        };
        GitLab {
            client: self.base.client.clone(),
            base_url: self.base_url.unwrap_or_else(|| self.base.base_url.clone()),
            env_auth,
            auth_strategy,
            auth_policy,
            env_username: self.base.env_username.clone(),
            headers,
            variant_hooks: crate::shared::VariantHooks {
                pre_response_json: self.pre_response_json,
                response_mutators: self.response_mutators,
            },
        }
    }
}
impl GitLab {
    fn auth_is_required(&self) -> bool {
        !self.auth_policy.explicit.is_empty() || self.auth_policy.env_fallback.is_some()
    }
    fn accepted_explicit_auth_methods(&self) -> Vec<String> {
        self.auth_policy
            .explicit
            .iter()
            .map(|method| match method {
                schematic_define::AuthMethod::BearerToken { header } => match header.as_deref() {
                    Some(header) => format!("an explicit bearer token in `{header}`"),
                    None => "an explicit bearer token".to_string(),
                },
                schematic_define::AuthMethod::ApiKey { header } => {
                    format!("an explicit API key in `{header}`")
                }
                schematic_define::AuthMethod::Basic => {
                    "explicit basic auth credentials".to_string()
                }
                schematic_define::AuthMethod::OAuth2(_) => {
                    "an explicit OAuth access token".to_string()
                }
                _ => "explicit authentication".to_string(),
            })
            .collect()
    }
    fn env_fallback_var_names(&self) -> Vec<String> {
        match &self.auth_policy.env_fallback {
            Some(schematic_define::EnvAuthStrategy::BearerToken { .. }) => self
                .headers
                .env_mapping()
                .bearer_token
                .as_ref()
                .map(|list| list.names().to_vec())
                .unwrap_or_default(),
            Some(schematic_define::EnvAuthStrategy::ApiKey { .. }) => self
                .headers
                .env_mapping()
                .api_key
                .as_ref()
                .map(|api_key| api_key.names.names().to_vec())
                .unwrap_or_default(),
            Some(schematic_define::EnvAuthStrategy::Basic) => {
                let mut vars = Vec::new();
                if let Some(user) = self.headers.env_mapping().basic_user.as_ref() {
                    vars.extend(user.names().iter().cloned());
                }
                if let Some(pass) = self.headers.env_mapping().basic_pass.as_ref() {
                    vars.extend(pass.names().iter().cloned());
                }
                vars
            }
            None => Vec::new(),
            _ => Vec::new(),
        }
    }
    fn authentication_required_error(&self) -> SchematicError {
        let explicit_methods = self.accepted_explicit_auth_methods();
        let env_fallback_vars = self.env_fallback_var_names();
        let mut options = Vec::new();
        if !explicit_methods.is_empty() {
            options.push(explicit_methods.join(", "));
        }
        if !env_fallback_vars.is_empty() {
            options.push(format!(
                "set one of the fallback env vars `{}`",
                env_fallback_vars.join("`, `")
            ));
        }
        let mut message = if options.is_empty() {
            "Authentication required.".to_string()
        } else {
            format!("Authentication required: {}.", options.join(" or "))
        };
        if self.auth_policy.oauth2().is_some() {
            message
                .push_str(
                    " Obtain the OAuth token with schematic-oauth, then inject it with `.oauth_token(...)`.",
                );
        }
        SchematicError::AuthenticationRequired {
            message,
            explicit_methods,
            env_fallback_vars,
        }
    }
    fn apply_env_fallback(&self, headers: schematic_define::Headers) -> schematic_define::Headers {
        let env_mapping = self.headers.env_mapping().clone();
        match &self.auth_policy.env_fallback {
            Some(schematic_define::EnvAuthStrategy::BearerToken { header }) => {
                let token = env_mapping.bearer_token.as_ref().and_then(|list| {
                    list.names()
                        .iter()
                        .find_map(|name| std::env::var(name).ok())
                });
                match (token, header.as_deref()) {
                    (Some(token), Some(header)) => {
                        headers.use_bearer_token_with_header(token, header)
                    }
                    (Some(token), None) => headers.use_bearer_token(token),
                    _ => headers,
                }
            }
            Some(schematic_define::EnvAuthStrategy::ApiKey { header }) => {
                let key = env_mapping.api_key.as_ref().and_then(|api_key| {
                    api_key
                        .names
                        .names()
                        .iter()
                        .find_map(|name| std::env::var(name).ok())
                });
                match key {
                    Some(key) => headers.header(header.clone(), key),
                    None => headers,
                }
            }
            Some(schematic_define::EnvAuthStrategy::Basic) => {
                let username = env_mapping.basic_user.as_ref().and_then(|list| {
                    list.names()
                        .iter()
                        .find_map(|name| std::env::var(name).ok())
                });
                let password = env_mapping.basic_pass.as_ref().and_then(|list| {
                    list.names()
                        .iter()
                        .find_map(|name| std::env::var(name).ok())
                });
                match (username, password) {
                    (Some(username), Some(password)) => headers.use_basic_auth(username, password),
                    _ => headers,
                }
            }
            None => headers,
            _ => headers,
        }
    }
    fn headers_satisfy_fallback(&self, headers: &schematic_define::Headers) -> bool {
        match &self.auth_policy.env_fallback {
            Some(schematic_define::EnvAuthStrategy::BearerToken { header }) => {
                header.as_deref().map_or_else(
                    || headers.has_authorization(),
                    |header| headers.has_header(header),
                )
            }
            Some(schematic_define::EnvAuthStrategy::ApiKey { header }) => {
                headers.has_header(header)
            }
            Some(schematic_define::EnvAuthStrategy::Basic) => headers.has_authorization(),
            None => false,
            _ => false,
        }
    }
    fn resolve_request_headers(&self) -> Result<Vec<(String, String)>, SchematicError> {
        let mut headers = self.headers.clone();
        if !headers.has_explicit_auth() {
            headers = self.apply_env_fallback(headers);
        }
        if self.auth_is_required()
            && !headers.has_explicit_auth()
            && !self.headers_satisfy_fallback(&headers)
        {
            return Err(self.authentication_required_error());
        }
        headers.build().map_err(SchematicError::from)
    }
    /// Builds and sends an HTTP request, returning the raw response plus context.
    ///
    /// This is an internal helper method used by the public request methods.
    /// Returns both the response and the context needed for hook processing.
    async fn build_and_send_request(
        &self,
        request: impl Into<GitLabRequest>,
    ) -> Result<(reqwest::Response, crate::shared::ResponseContext), SchematicError> {
        let request = request.into();
        let endpoint_id = request.endpoint_id();
        let (method, path, body, endpoint_headers) = request.into_parts()?;
        let url = format!("{}{}", self.base_url, path);
        let mut req_builder = match method {
            "GET" => self.client.get(&url),
            "POST" => self.client.post(&url),
            "PUT" => self.client.put(&url),
            "PATCH" => self.client.patch(&url),
            "DELETE" => self.client.delete(&url),
            "HEAD" => self.client.head(&url),
            "OPTIONS" => self.client.request(reqwest::Method::OPTIONS, &url),
            _ => return Err(SchematicError::UnsupportedMethod(method.to_string())),
        };
        let api_headers = self.resolve_request_headers()?;
        let merged_headers = Self::merge_headers(&api_headers, &endpoint_headers);
        for (key, value) in merged_headers {
            req_builder = req_builder.header(key.as_str(), value.as_str());
        }
        if let Some(body) = body {
            req_builder = req_builder
                .header("Content-Type", "application/json")
                .body(body);
        }
        let response = req_builder.send().await?;
        if !response.status().is_success() {
            let status = response.status().as_u16();
            let body_text = response.text().await.unwrap_or_default();
            return Err(SchematicError::ApiError {
                status,
                body: body_text,
            });
        }
        let status = response.status().as_u16();
        let headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();
        let ctx = crate::shared::ResponseContext::new(
            endpoint_id,
            method,
            path.clone(),
            url,
            status,
            headers,
        );
        Ok((response, ctx))
    }
    /// Merges API-level and endpoint-level headers.
    ///
    /// Endpoint headers override API headers for matching keys (case-insensitive).
    /// Returns a new Vec with the merged headers.
    fn merge_headers(
        api_headers: &[(String, String)],
        endpoint_headers: &[(String, String)],
    ) -> Vec<(String, String)> {
        let mut result: Vec<(String, String)> = Vec::new();
        for (api_key, api_value) in api_headers {
            let has_override = endpoint_headers
                .iter()
                .any(|(k, _)| k.eq_ignore_ascii_case(api_key));
            if !has_override {
                result.push((api_key.clone(), api_value.clone()));
            }
        }
        for (key, value) in endpoint_headers {
            result.push((key.clone(), value.clone()));
        }
        result
    }
    /// Executes an API request expecting a JSON response.
    ///
    /// Takes any request type that can be converted into the request enum
    /// and returns the deserialized response. If response hooks are configured
    /// via the variant builder, they will be applied.
    ///
    /// ## Hooks
    ///
    /// If configured via `variant()`:
    /// - `pre_response_json` - Transforms JSON before deserialization
    /// - `mutate_response` - Mutates the response after deserialization
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The HTTP request fails (network error, timeout, etc.)
    /// - The response indicates a non-success status code
    /// - The response body cannot be deserialized as JSON
    /// - A hook returns an error
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn request<T: serde::de::DeserializeOwned + Send + Sync + 'static>(
        &self,
        request: impl Into<GitLabRequest>,
    ) -> Result<T, SchematicError> {
        let (response, ctx) = self.build_and_send_request(request).await?;
        let has_pre_hook = self.variant_hooks.pre_response_json.is_some();
        let has_mutator = self
            .variant_hooks
            .response_mutators
            .contains_key(ctx.endpoint_id);
        if has_pre_hook || has_mutator {
            let bytes = response.bytes().await?;
            let mut json_value: serde_json::Value = serde_json::from_slice(&bytes)?;
            if let Some(ref hook) = self.variant_hooks.pre_response_json {
                json_value = hook(&ctx, json_value)?;
            }
            let mut result: T = serde_json::from_value(json_value)?;
            if let Some(mutator) = self.variant_hooks.response_mutators.get(ctx.endpoint_id) {
                mutator.mutate(&ctx, &mut result)?;
            }
            Ok(result)
        } else {
            let result = response.json::<T>().await?;
            Ok(result)
        }
    }
}
