// This code was automatically generated by schematic-gen. Do not edit manually.

//! Generated REST API clients.
//!
//! Each API is available as a separate module with its client struct,
//! request types, and response types re-exported from definitions.
//!
//! ## Available APIs
//!
//! | Module | Client | Description | Auth |
//! |--------|--------|-------------|------|
//! | [`lmstudio`] | [`LmStudio`](lmstudio::LmStudio) | LM Studio v1 native REST API for local LLM inference and model management | Bearer |
//!
//! ## Quick Start
//!
//! Use the prelude for convenient imports:
//!
//! ```ignore
//! use schematic_schema::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), SchematicError> {
//!     let client = LmStudio::new();
//!     let response = client.list_models().await?;
//!     println!("{:?}", response);
//!     Ok(())
//! }
//! ```
//!
//! ## Ergonomic Features
//!
//! Generated clients include several convenience features:
//!
//! - **`From<&str>` / `From<String>`** on single-param request structs
//! - **`From<BodyType>`** on body-only request structs
//! - **`#[must_use]`** on all async methods to catch missing `.await`
//! - **`DOCS_URL`** constant on each client for programmatic doc access
//! - **`variant()`** method for creating alternate configurations
//!
//! ## Variants
//!
//! Create alternate client configurations for staging, testing, or different
//! environments using the [`variant()`](lmstudio::LmStudio::variant) builder
//! or [`variant_with()`](lmstudio::LmStudio::variant_with) convenience method:
//!
//! ```ignore
//! use schematic_schema::prelude::*;
//! use schematic_define::UpdateStrategy;
//!
//! let client = LmStudio::new();
//!
//! // Simple environment switch with variant_with()
//! let staging = client.variant_with(
//!     "https://staging.example.com/v1",
//!     vec!["STAGING_LM_API_TOKEN".to_string()],
//!     UpdateStrategy::NoChange,
//! );
//!
//! // Full builder with response hooks
//! let custom = client.variant()
//!     .base_url("http://localhost:8080/v1")
//!     .env_auth(vec!["LOCAL_KEY".to_string()])
//!     .auth_update(UpdateStrategy::ChangeTo(schematic_define::AuthStrategy::ApiKey {
//!         header: "X-API-Key".to_string(),
//!     }))
//!     .pre_response_json(|_ctx, json| Ok(json))
//!     .build();
//! ```
//!
//! ## Error Handling
//!
//! All request methods return `Result<T, SchematicError>`. See
//! [`shared::SchematicError`] for the full error enum and handling examples.
pub mod shared;
pub mod prelude;
pub mod lmstudio;
