//! Generated REST API clients.
//!
//! This code was automatically generated by schematic-gen. Do not edit manually.
//!
//! ## Available APIs
//!
//! Each API is available as a separate module with its client struct,
//! request types, and response types re-exported from definitions.
//!
//! ## Quick Start
//!
//! Use the prelude for convenient imports:
//!
//! ```ignore
//! use schematic_schema::prelude::*;
//! ```
pub mod shared;
pub mod prelude;
pub mod elevenlabs;
