// This code was automatically generated by schematic-gen. Do not edit manually.

//! Generated API client for [OpenAI](https://platform.openai.com/docs/api-reference).
//!
//! OpenAI REST API for model management
//!
//! ## Authentication
//!
//! Uses Bearer token authentication via the `Authorization` header. Set via environment variable: `OPENAI_API_KEY`.
//!
//! ## Features
//!
//! **DELETE**:
//! - `DeleteModel` - Delete a fine-tuned model
//!
//! **GET**:
//! - `ListModels` - Lists the currently available models
//! - `RetrieveModel` - Retrieves a model instance
//!
//! ## Example
//!
//! ```ignore
//! use schematic_schema::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), SchematicError> {
//!     let client = OpenAI::new();
//!     let response = client.list_models().await?;
//!     println!("{:?}", response);
//!     Ok(())
//! }
//! ```
use serde::{Deserialize, Serialize};
pub use schematic_definitions::openai::*;
use crate::shared::{RequestParts, SchematicError};
/// Request for `ListModels` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::openai::ListModelsRequest;
///
/// let request = ListModelsRequest::default();
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelsRequest {}
impl ListModelsRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/models".to_string();
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListModelsRequest {
    type Response = ListModelsResponse;
    const ENDPOINT_ID: &'static str = "ListModels";
}
/// Request for `RetrieveModel` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::openai::RetrieveModelRequest;
///
/// let request = RetrieveModelRequest::new("model_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct RetrieveModelRequest {
    /// Path parameter: model
    pub model: String,
}
impl RetrieveModelRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(model: impl Into<String>) -> Self {
        Self { model: model.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/models/{}", self.model);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for RetrieveModelRequest {
    fn from(param: &str) -> Self {
        Self { model: param.to_string() }
    }
}
impl From<String> for RetrieveModelRequest {
    fn from(param: String) -> Self {
        Self { model: param }
    }
}
impl crate::shared::EndpointSpec for RetrieveModelRequest {
    type Response = Model;
    const ENDPOINT_ID: &'static str = "RetrieveModel";
}
/// Request for `DeleteModel` endpoint.
///
/// ## Example
///
/// ```ignore
/// use schematic_schema::openai::DeleteModelRequest;
///
/// let request = DeleteModelRequest::new("model_value");
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteModelRequest {
    /// Path parameter: model
    pub model: String,
}
impl DeleteModelRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(model: impl Into<String>) -> Self {
        Self { model: model.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/models/{}", self.model);
        Ok(("DELETE", path, None, vec![]))
    }
}
impl From<&str> for DeleteModelRequest {
    fn from(param: &str) -> Self {
        Self { model: param.to_string() }
    }
}
impl From<String> for DeleteModelRequest {
    fn from(param: String) -> Self {
        Self { model: param }
    }
}
impl crate::shared::EndpointSpec for DeleteModelRequest {
    type Response = DeleteModelResponse;
    const ENDPOINT_ID: &'static str = "DeleteModel";
}
/// Request enum for OpenAI API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum OpenAIRequest {
    /// Lists the currently available models
    ListModels(ListModelsRequest),
    /// Retrieves a model instance
    RetrieveModel(RetrieveModelRequest),
    /// Delete a fine-tuned model
    DeleteModel(DeleteModelRequest),
}
impl OpenAIRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::ListModels(req) => req.into_parts(),
            Self::RetrieveModel(req) => req.into_parts(),
            Self::DeleteModel(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::ListModels(_) => {
                <ListModelsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::RetrieveModel(_) => {
                <RetrieveModelRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::DeleteModel(_) => {
                <DeleteModelRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
}
impl From<ListModelsRequest> for OpenAIRequest {
    fn from(req: ListModelsRequest) -> Self {
        Self::ListModels(req)
    }
}
impl From<RetrieveModelRequest> for OpenAIRequest {
    fn from(req: RetrieveModelRequest) -> Self {
        Self::RetrieveModel(req)
    }
}
impl From<DeleteModelRequest> for OpenAIRequest {
    fn from(req: DeleteModelRequest) -> Self {
        Self::DeleteModel(req)
    }
}
/// OpenAI REST API for model management client.
pub struct OpenAI {
    client: reqwest::Client,
    base_url: String,
    /// Environment variable names for authentication credentials.
    env_auth: Vec<String>,
    /// Authentication strategy for this API client.
    auth_strategy: schematic_define::AuthStrategy,
    /// Environment variable for Basic auth username.
    env_username: Option<String>,
    /// Default HTTP headers to include with every request.
    headers: Vec<(String, String)>,
    /// Variant-specific hooks for response customization.
    variant_hooks: crate::shared::VariantHooks,
}
impl OpenAI {
    /// Base URL for the API.
    pub const BASE_URL: &'static str = "https://api.openai.com/v1";
    /// Official API documentation URL, if available.
    pub const DOCS_URL: Option<&'static str> = Some(
        "https://platform.openai.com/docs/api-reference",
    );
    /// Creates a new API client with the default base URL.
    pub fn new() -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec!["OPENAI_API_KEY".to_string()],
            auth_strategy: schematic_define::AuthStrategy::BearerToken {
                header: None,
            },
            env_username: None,
            headers: vec![],
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a custom base URL.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let client = Api::with_base_url("http://localhost:8080/v1");
    /// ```
    pub fn with_base_url(base_url: impl Into<String>) -> Self {
        Self {
            client: reqwest::Client::new(),
            base_url: base_url.into(),
            env_auth: vec!["OPENAI_API_KEY".to_string()],
            auth_strategy: schematic_define::AuthStrategy::BearerToken {
                header: None,
            },
            env_username: None,
            headers: vec![],
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client.
    ///
    /// Use this when you need custom timeouts, connection pools, or middleware.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client(custom_client);
    /// ```
    pub fn with_client(client: reqwest::Client) -> Self {
        Self {
            client,
            base_url: Self::BASE_URL.to_string(),
            env_auth: vec!["OPENAI_API_KEY".to_string()],
            auth_strategy: schematic_define::AuthStrategy::BearerToken {
                header: None,
            },
            env_username: None,
            headers: vec![],
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a new API client with a pre-configured reqwest client and custom base URL.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// let custom_client = reqwest::Client::builder()
    ///     .timeout(std::time::Duration::from_secs(60))
    ///     .build()
    ///     .unwrap();
    /// let api = Api::with_client_and_base_url(custom_client, "http://localhost:8080");
    /// ```
    pub fn with_client_and_base_url(
        client: reqwest::Client,
        base_url: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            env_auth: vec!["OPENAI_API_KEY".to_string()],
            auth_strategy: schematic_define::AuthStrategy::BearerToken {
                header: None,
            },
            env_username: None,
            headers: vec![],
            variant_hooks: crate::shared::VariantHooks::default(),
        }
    }
    /// Creates a variant builder for customizing this API client.
    ///
    /// The builder pattern allows fluent configuration of:
    /// - Base URL (for proxies, mock servers, or different environments)
    /// - Authentication credentials (different env var names)
    /// - Authentication strategy
    /// - Response hooks for JSON transformation and mutation
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// use schematic_define::UpdateStrategy;
    ///
    /// let api = Api::new();
    ///
    /// // Create a variant pointing to a staging server with a response hook
    /// let staging = api.variant()
    ///     .base_url("https://staging.api.com/v1")
    ///     .env_auth(vec!["STAGING_API_KEY".to_string()])
    ///     .mutate_response::<ListModelsRequest>(|ctx, response| {
    ///         response.data.retain(|m| !m.id.contains("deprecated"));
    ///         Ok(())
    ///     })
    ///     .build();
    /// ```
    #[must_use]
    pub fn variant(&self) -> OpenAIVariantBuilder<'_> {
        OpenAIVariantBuilder::new(self)
    }
    /// Creates a variant of this API client with different configuration.
    ///
    /// This is a convenience method equivalent to:
    /// ```ignore
    /// api.variant()
    ///     .base_url(base_url)
    ///     .env_auth(env_auth)
    ///     .auth_update(strategy)
    ///     .build()
    /// ```
    ///
    /// ## Arguments
    ///
    /// * `base_url` - New base URL for this variant
    /// * `env_auth` - New environment variable names for credentials
    /// * `strategy` - How to update the auth strategy:
    ///   - `UpdateStrategy::NoChange` - Keep current auth strategy
    ///   - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    pub fn variant_with(
        &self,
        base_url: impl Into<String>,
        env_auth: Vec<String>,
        strategy: schematic_define::UpdateStrategy,
    ) -> Self {
        self.variant()
            .base_url(base_url)
            .env_auth(env_auth)
            .auth_update(strategy)
            .build()
    }
    /// Returns a reference to the underlying HTTP client.
    ///
    /// Use this for custom requests that aren't covered by the generated methods,
    /// such as paginated endpoints that require query parameters.
    pub fn http_client(&self) -> &reqwest::Client {
        &self.client
    }
    /// Returns the base URL for this API client.
    pub fn api_base_url(&self) -> &str {
        &self.base_url
    }
    /// Returns the API key header name and value for authentication.
    ///
    /// Returns `None` if the authentication strategy is not `ApiKey`
    /// or if the API key environment variable is not set.
    pub fn api_key_header(&self) -> Option<(String, String)> {
        match &self.auth_strategy {
            schematic_define::AuthStrategy::ApiKey { header } => {
                for env_name in &self.env_auth {
                    if let Ok(value) = std::env::var(env_name) {
                        return Some((header.clone(), value));
                    }
                }
                None
            }
            _ => None,
        }
    }
}
impl Default for OpenAI {
    fn default() -> Self {
        Self::new()
    }
}
/// Builder for creating customized variants of the API client.
///
/// Use [`#struct_name::variant()`] to create a builder, then chain
/// configuration methods and call [`build()`](Self::build) to create
/// the variant client.
pub struct OpenAIVariantBuilder<'a> {
    base: &'a OpenAI,
    base_url: Option<String>,
    env_auth: Option<Vec<String>>,
    auth_update: schematic_define::UpdateStrategy,
    headers: Option<Vec<(String, String)>>,
    pre_response_json: Option<std::sync::Arc<crate::shared::PreResponseJsonHook>>,
    response_mutators: std::collections::HashMap<
        &'static str,
        std::sync::Arc<dyn crate::shared::AnyResponseMutator>,
    >,
}
impl<'a> OpenAIVariantBuilder<'a> {
    /// Creates a new variant builder from the base API client.
    fn new(base: &'a OpenAI) -> Self {
        Self {
            base,
            base_url: None,
            env_auth: None,
            auth_update: schematic_define::UpdateStrategy::NoChange,
            headers: None,
            pre_response_json: None,
            response_mutators: std::collections::HashMap::new(),
        }
    }
    /// Sets the base URL for the variant.
    ///
    /// If not set, the original client's base URL is used.
    #[must_use]
    pub fn base_url(mut self, url: impl Into<String>) -> Self {
        self.base_url = Some(url.into());
        self
    }
    /// Sets the environment variable names for authentication.
    ///
    /// If not set, the original client's env_auth is used.
    #[must_use]
    pub fn env_auth(mut self, env_auth: Vec<String>) -> Self {
        self.env_auth = Some(env_auth);
        self
    }
    /// Sets how the authentication strategy should be updated.
    ///
    /// - `UpdateStrategy::NoChange` - Keep current auth strategy (default)
    /// - `UpdateStrategy::ChangeTo(auth)` - Use specified auth strategy
    #[must_use]
    pub fn auth_update(mut self, strategy: schematic_define::UpdateStrategy) -> Self {
        self.auth_update = strategy;
        self
    }
    /// Sets custom headers for the variant.
    ///
    /// If not set, the original client's headers are used.
    #[must_use]
    pub fn headers(mut self, headers: Vec<(String, String)>) -> Self {
        self.headers = Some(headers);
        self
    }
    /// Sets a pre-response JSON transformation hook.
    ///
    /// This hook runs after receiving an HTTP response but before
    /// deserializing to the response type. Use it to reshape JSON
    /// payloads to match expected structures.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// // Unwrap a { data: ... } envelope
    /// variant.pre_response_json(|ctx, json| {
    ///     Ok(json.get("data").cloned().unwrap_or(json))
    /// })
    /// ```
    #[must_use]
    pub fn pre_response_json<F>(mut self, hook: F) -> Self
    where
        F: Fn(
                &crate::shared::ResponseContext,
                serde_json::Value,
            ) -> Result<serde_json::Value, crate::shared::SchematicError> + Send + Sync
            + 'static,
    {
        self.pre_response_json = Some(std::sync::Arc::new(hook));
        self
    }
    /// Registers a response mutation hook for a specific endpoint.
    ///
    /// This hook runs after deserializing the response and can mutate
    /// the response object in place. The endpoint is identified by its
    /// request type.
    ///
    /// ## Examples
    ///
    /// ```ignore
    /// variant.mutate_response::<ListModelsRequest>(|ctx, response| {
    ///     response.data.retain(|m| !m.id.contains("deprecated"));
    ///     Ok(())
    /// })
    /// ```
    #[must_use]
    pub fn mutate_response<R, F>(mut self, hook: F) -> Self
    where
        R: crate::shared::EndpointSpec,
        R::Response: Send + Sync + 'static,
        F: Fn(
                &crate::shared::ResponseContext,
                &mut R::Response,
            ) -> Result<(), crate::shared::SchematicError> + Send + Sync + 'static,
    {
        self.response_mutators
            .insert(
                R::ENDPOINT_ID,
                std::sync::Arc::new(crate::shared::TypedMutator::new(hook)),
            );
        self
    }
    /// Builds the variant API client with the configured options.
    ///
    /// Options not explicitly set will inherit from the base client.
    #[must_use]
    pub fn build(self) -> OpenAI {
        let auth_strategy = match self.auth_update {
            schematic_define::UpdateStrategy::NoChange => self.base.auth_strategy.clone(),
            schematic_define::UpdateStrategy::ChangeTo(auth) => auth,
            _ => self.base.auth_strategy.clone(),
        };
        OpenAI {
            client: self.base.client.clone(),
            base_url: self.base_url.unwrap_or_else(|| self.base.base_url.clone()),
            env_auth: self.env_auth.unwrap_or_else(|| self.base.env_auth.clone()),
            auth_strategy,
            env_username: self.base.env_username.clone(),
            headers: self.headers.unwrap_or_else(|| self.base.headers.clone()),
            variant_hooks: crate::shared::VariantHooks {
                pre_response_json: self.pre_response_json,
                response_mutators: self.response_mutators,
            },
        }
    }
}
impl OpenAI {
    /// Builds and sends an HTTP request, returning the raw response plus context.
    ///
    /// This is an internal helper method used by the public request methods.
    /// Returns both the response and the context needed for hook processing.
    async fn build_and_send_request(
        &self,
        request: impl Into<OpenAIRequest>,
    ) -> Result<(reqwest::Response, crate::shared::ResponseContext), SchematicError> {
        let request = request.into();
        let endpoint_id = request.endpoint_id();
        let (method, path, body, endpoint_headers) = request.into_parts()?;
        let url = format!("{}{}", self.base_url, path);
        let mut req_builder = match method {
            "GET" => self.client.get(&url),
            "POST" => self.client.post(&url),
            "PUT" => self.client.put(&url),
            "PATCH" => self.client.patch(&url),
            "DELETE" => self.client.delete(&url),
            "HEAD" => self.client.head(&url),
            "OPTIONS" => self.client.request(reqwest::Method::OPTIONS, &url),
            _ => return Err(SchematicError::UnsupportedMethod(method.to_string())),
        };
        match &self.auth_strategy {
            schematic_define::AuthStrategy::None => {}
            schematic_define::AuthStrategy::BearerToken { header } => {
                let header_name = header.as_deref().unwrap_or("Authorization");
                let token = self
                    .env_auth
                    .iter()
                    .find_map(|var| std::env::var(var).ok())
                    .ok_or_else(|| SchematicError::MissingCredential {
                        env_vars: self.env_auth.clone(),
                    })?;
                req_builder = req_builder
                    .header(header_name, format!("Bearer {}", token));
            }
            schematic_define::AuthStrategy::ApiKey { header } => {
                let key = self
                    .env_auth
                    .iter()
                    .find_map(|var| std::env::var(var).ok())
                    .ok_or_else(|| SchematicError::MissingCredential {
                        env_vars: self.env_auth.clone(),
                    })?;
                req_builder = req_builder.header(header.as_str(), key);
            }
            schematic_define::AuthStrategy::Basic => {
                let username_env = self.env_username.as_deref().unwrap_or("USERNAME");
                let password_env = self
                    .env_auth
                    .first()
                    .map(String::as_str)
                    .unwrap_or("PASSWORD");
                let username = std::env::var(username_env)
                    .map_err(|_| SchematicError::MissingCredential {
                        env_vars: vec![username_env.to_string()],
                    })?;
                let password = std::env::var(password_env)
                    .map_err(|_| SchematicError::MissingCredential {
                        env_vars: vec![password_env.to_string()],
                    })?;
                req_builder = req_builder.basic_auth(username, Some(password));
            }
            _ => {}
        }
        let merged_headers = Self::merge_headers(&self.headers, &endpoint_headers);
        for (key, value) in merged_headers {
            req_builder = req_builder.header(key.as_str(), value.as_str());
        }
        if let Some(body) = body {
            req_builder = req_builder
                .header("Content-Type", "application/json")
                .body(body);
        }
        let response = req_builder.send().await?;
        if !response.status().is_success() {
            let status = response.status().as_u16();
            let body_text = response.text().await.unwrap_or_default();
            return Err(SchematicError::ApiError {
                status,
                body: body_text,
            });
        }
        let status = response.status().as_u16();
        let headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();
        let ctx = crate::shared::ResponseContext::new(
            endpoint_id,
            method,
            path.clone(),
            url,
            status,
            headers,
        );
        Ok((response, ctx))
    }
    /// Merges API-level and endpoint-level headers.
    ///
    /// Endpoint headers override API headers for matching keys (case-insensitive).
    /// Returns a new Vec with the merged headers.
    fn merge_headers(
        api_headers: &[(String, String)],
        endpoint_headers: &[(String, String)],
    ) -> Vec<(String, String)> {
        let mut result: Vec<(String, String)> = Vec::new();
        for (api_key, api_value) in api_headers {
            let has_override = endpoint_headers
                .iter()
                .any(|(k, _)| k.eq_ignore_ascii_case(api_key));
            if !has_override {
                result.push((api_key.clone(), api_value.clone()));
            }
        }
        for (key, value) in endpoint_headers {
            result.push((key.clone(), value.clone()));
        }
        result
    }
    /// Executes an API request expecting a JSON response.
    ///
    /// Takes any request type that can be converted into the request enum
    /// and returns the deserialized response. If response hooks are configured
    /// via the variant builder, they will be applied.
    ///
    /// ## Hooks
    ///
    /// If configured via `variant()`:
    /// - `pre_response_json` - Transforms JSON before deserialization
    /// - `mutate_response` - Mutates the response after deserialization
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The HTTP request fails (network error, timeout, etc.)
    /// - The response indicates a non-success status code
    /// - The response body cannot be deserialized as JSON
    /// - A hook returns an error
    #[must_use = "this returns a Future that must be awaited"]
    pub async fn request<T: serde::de::DeserializeOwned + Send + Sync + 'static>(
        &self,
        request: impl Into<OpenAIRequest>,
    ) -> Result<T, SchematicError> {
        let (response, ctx) = self.build_and_send_request(request).await?;
        let has_pre_hook = self.variant_hooks.pre_response_json.is_some();
        let has_mutator = self
            .variant_hooks
            .response_mutators
            .contains_key(ctx.endpoint_id);
        if has_pre_hook || has_mutator {
            let bytes = response.bytes().await?;
            let mut json_value: serde_json::Value = serde_json::from_slice(&bytes)?;
            if let Some(ref hook) = self.variant_hooks.pre_response_json {
                json_value = hook(&ctx, json_value)?;
            }
            let mut result: T = serde_json::from_value(json_value)?;
            if let Some(mutator) = self
                .variant_hooks
                .response_mutators
                .get(ctx.endpoint_id)
            {
                mutator.mutate(&ctx, &mut result)?;
            }
            Ok(result)
        } else {
            let result = response.json::<T>().await?;
            Ok(result)
        }
    }
}
