// This code was automatically generated by schematic-gen. Do not edit manually.

//! Generated WebSocket API definition helper for Unfolded Circle Core WS.
//!
//! This module currently exposes the typed `WebSocketApi` definition
//! and related model types from `schematic-definitions`.
//!
//! WebSocket runtime client code generation is not yet implemented in `schematic-gen`.
pub use schematic_definitions::unfolded_circle::core_ws::*;
use schematic_define::websocket::WebSocketApi;
/// Builds the Unfolded Circle Core WebSocket API definition.
#[must_use]
pub fn define_api() -> WebSocketApi {
    schematic_definitions::define_unfolded_circle_core_ws_api()
}
