[package]
name = "biscuit-location-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "where"
path = "src/main.rs"

[dependencies]
biscuit-location = { path = "../lib" }
clap = { version = "4.5", features = ["derive", "wrap_help"] }
color-eyre = "0.6"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
