set dotenv-load
set positional-arguments

default:
    @echo
    @echo "Shared Library"
    @echo "--------------"
    @echo ""
    @just --list | grep -v 'default'
    @echo

# build the shared library
build *args="":
    @echo ""
    @echo "Build Shared Library"
    @echo "--------------------"
    @echo ""
    @cargo build -p shared {{args}}

# run tests for the shared library
test *args="":
    @echo ""
    @echo "Testing Shared Library"
    @echo "----------------------"
    @echo ""
    @cargo test -p shared {{args}}
