//! Shell completion script rendering for `claudine completions <shell>`.
//!
//! Bash, zsh, and fish are served by shell-specific scripts that shell out
//! to the hidden `claudine __complete` subcommand on every `<TAB>`. Routing
//! inside `__complete` flows through [`super::engine::run`], which
//! classifies the cursor slot (root menu, composition positional, setter
//! value) and dispatches to a slot-specific completer.
//!
//! `powershell` and `elvish` retain the legacy `COMPLETE`-based bootstrap
//! snippet; those shells fall back to whatever `clap_complete` derives
//! from the [`crate::args::Cli`] command tree. The legacy `CompleteEnv`
//! path in [`super::maybe_complete`] continues to serve them.
//!
//! ## Installation
//!
//! Bash:
//!
//! ```sh
//! claudine completions bash > ~/.local/share/bash-completion/completions/claudine
//! ```
//!
//! Zsh:
//!
//! ```sh
//! claudine completions zsh > "${fpath[1]}/_claudine"
//! ```
//!
//! Fish:
//!
//! ```sh
//! claudine completions fish > ~/.config/fish/completions/claudine.fish
//! ```
//!
//! The scripts work the same way on every shell: on each `<TAB>`, the
//! registered callback invokes `claudine __complete --current <INDEX> --
//! <argv>`. The engine classifies the cursor position, applies the
//! slot-specific rules, and prints one candidate per line on stdout. The
//! shell then presents those candidates to the user. When `__complete`
//! returns no candidates, each shell falls back to its default file
//! completion so non-targeted argument positions still behave as if
//! completion were unset.

use clap_complete::Shell;

/// Render the completion script for `shell`.
///
/// Returned string includes a trailing newline so it prints cleanly as a
/// CLI subcommand output. Redirect the output into the shell's completion
/// file; the scripts are idempotent on reload.
pub(crate) fn render(shell: Shell) -> String {
    match shell {
        Shell::Bash => BASH_SCRIPT.to_string(),
        Shell::Zsh => ZSH_SCRIPT.to_string(),
        Shell::Fish => FISH_SCRIPT.to_string(),
        Shell::PowerShell => legacy_bootstrap(Shell::PowerShell),
        Shell::Elvish => legacy_bootstrap(Shell::Elvish),
        // `clap_complete::Shell` is `#[non_exhaustive]`; any future shell
        // that clap adds falls back to the bash-style script. That is the
        // closest documented shape for POSIX-like shells.
        _ => BASH_SCRIPT.to_string(),
    }
}

/// Legacy `COMPLETE=<shell> claudine` one-liner retained for shells the
/// new engine does not target (powershell, elvish). The `CompleteEnv`
/// runtime path in [`super::maybe_complete`] continues to serve these
/// callers.
fn legacy_bootstrap(shell: Shell) -> String {
    match shell {
        Shell::PowerShell => {
            "& { $env:COMPLETE=\"powershell\"; claudine } | Out-String | Invoke-Expression\n"
                .to_string()
        }
        Shell::Elvish => "eval (E:COMPLETE=elvish claudine | slurp)\n".to_string(),
        _ => "source <(COMPLETE=bash claudine)\n".to_string(),
    }
}

/// Bash completion script.
///
/// Registers `_claudine_complete` as the completion function for the
/// `claudine` command. On every `<TAB>`, the function shells out to
/// `claudine __complete --current $COMP_CWORD -- "${COMP_WORDS[@]}"` and
/// treats each line of stdout as a candidate. If the call fails or returns
/// no candidates, bash falls back to default file completion (`bashdefault`
/// + `default`).
///
/// `-o nosort` preserves the order the engine emits (currently alphabetical
/// from a `BTreeSet`, but the contract reserves the right to change this).
/// The `-o nospace` option is intentionally NOT set: bash's default trailing
/// space after a unique match is correct for every engine candidate (files,
/// not directories).
const BASH_SCRIPT: &str = r#"# Claudine shell completions (bash)
# Generated by `claudine completions bash`.
#
# The `__complete` subcommand is the Claudine completion engine. It
# classifies the cursor position and prints one candidate per line on
# stdout. When it has no candidates (non-targeted positions, errors) the
# script lets bash fall back to its default file completion.

_claudine_complete() {
    local IFS=$'\n'
    local candidates
    candidates=( $(command claudine __complete --current "$COMP_CWORD" -- "${COMP_WORDS[@]}" 2>/dev/null) )
    if [ ${#candidates[@]} -gt 0 ] && [ -n "${candidates[0]}" ]; then
        COMPREPLY=( "${candidates[@]}" )
        return 0
    fi
    COMPREPLY=()
    return 0
}

complete -o nosort -o bashdefault -o default -F _claudine_complete claudine
"#;

/// Zsh completion script.
///
/// Uses the `#compdef claudine` directive so the file can be dropped under
/// any directory in `$fpath` and be autoloaded. The main function splits
/// `__complete`'s stdout on newlines (`(@f)` flag), then feeds the resulting
/// array to `compadd`. When the engine emits nothing, the script falls back
/// to `_files` for default file completion.
///
/// When sourced directly (e.g. `source <(claudine completions zsh)`) before
/// `compinit` has run, `compdef` is not yet defined. The guard at the bottom
/// autoloads and initializes `compinit` on demand so `compdef _claudine
/// claudine` always registers, regardless of rc-file ordering.
const ZSH_SCRIPT: &str = r#"#compdef claudine
# Claudine shell completions (zsh)
# Generated by `claudine completions zsh`.
#
# The `__complete` subcommand is the Claudine completion engine. It
# classifies the cursor position and prints one candidate per line on
# stdout. When it has no candidates (non-targeted positions, errors) the
# function falls back to `_files` so default file completion still fires.

_claudine() {
    local -a candidates
    local current=$((CURRENT - 1))
    candidates=("${(@f)$(command claudine __complete --current $current -- "${words[@]}" 2>/dev/null)}")
    if (( ${#candidates[@]} > 0 )) && [[ -n "${candidates[1]}" ]]; then
        # Engine candidates may be fuzzy/substring matches, so they often
        # share no common prefix with what the user typed. Without the
        # guards below, zsh computes an empty unambiguous prefix and
        # silently erases the typed text.
        #
        # - `-U` suppresses compadd's default prefix-match filter so the
        #   candidates survive at all.
        # - `-Q` skips quoting of special characters (paths are already in
        #   their final shell form).
        # - `compstate[insert]=menu` forces menu-completion mode so the
        #   engine's substring matches are presented as choices instead of
        #   being collapsed into a non-existent common prefix.
        # - `-S ''` suppresses the trailing space compadd appends after a
        #   unique match; path candidates already have their terminator.
        compstate[insert]=menu
        compadd -U -Q -S '' -- "${candidates[@]}"
        return 0
    fi
    _files
}

# When this script is sourced before `compinit` has run, `compdef` is not
# yet defined. Autoload and initialize the completion system on demand so
# the registration below always succeeds.
if ! (( $+functions[compdef] )); then
    autoload -Uz compinit
    compinit -u 2>/dev/null
fi
compdef _claudine claudine
"#;

/// Fish completion script.
///
/// Fish's completion model merges every `complete -c claudine ...` command
/// into one candidate set, so the script registers a single completion that
/// delegates entirely to `__complete`. The `-f` flag disables the default
/// file-completion fallback; the engine itself decides when to emit file
/// candidates (and emits none otherwise, in which case fish simply shows
/// nothing).
const FISH_SCRIPT: &str = r#"# Claudine shell completions (fish)
# Generated by `claudine completions fish`.
#
# The `__complete` subcommand is the Claudine completion engine. It
# classifies the cursor position and prints one candidate per line on
# stdout. When it has no candidates (non-targeted positions, errors) fish
# falls back to default file completion via the `--force-files` retry.

function __claudine_complete
    set -l tokens (commandline -opc)
    set -l current_partial (commandline -ct)
    set -l argv_all claudine $tokens[2..] $current_partial
    set -l idx (math (count $argv_all) - 1)
    command claudine __complete --current $idx -- $argv_all 2>/dev/null
end

complete -c claudine -f -a '(__claudine_complete)'
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bash_script_registers_complete_callback() {
        let out = render(Shell::Bash);
        assert!(out.contains("_claudine_complete()"));
        assert!(out.contains("claudine __complete --current"));
        assert!(out.contains("complete"));
        assert!(out.contains("-F _claudine_complete claudine"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn bash_script_forwards_full_argv_to_engine() {
        let out = render(Shell::Bash);
        // The engine needs the full argv (binary + subcommand + flags +
        // partial token) to classify; the bash adapter must pass all of
        // `COMP_WORDS` as the trailing positional.
        assert!(out.contains("\"${COMP_WORDS[@]}\""));
        assert!(out.contains("$COMP_CWORD"));
    }

    #[test]
    fn bash_script_falls_back_to_default_completion() {
        let out = render(Shell::Bash);
        // `-o bashdefault -o default` lets bash attempt its native
        // completion (usually filenames) when our function leaves
        // COMPREPLY empty. This is how non-targeted argument positions
        // keep behaving as if completion were unset.
        assert!(out.contains("-o bashdefault"));
        assert!(out.contains("-o default"));
    }

    #[test]
    fn zsh_script_registers_compdef_directive() {
        let out = render(Shell::Zsh);
        assert!(out.starts_with("#compdef claudine"));
        assert!(out.contains("_claudine()"));
        assert!(out.contains("claudine __complete --current"));
        assert!(out.contains("compdef _claudine claudine"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn zsh_script_forwards_words_and_current_to_engine() {
        let out = render(Shell::Zsh);
        assert!(out.contains("\"${words[@]}\""));
        assert!(out.contains("$((CURRENT - 1))"));
    }

    #[test]
    fn zsh_script_suppresses_compadd_prefix_filter() {
        let out = render(Shell::Zsh);
        // The engine returns fuzzy/substring matches (e.g. `plan` matches
        // `prompts/plan.md`). Without `-U`, compadd drops any candidate
        // whose string doesn't start with what the user typed, silently
        // erasing the whole point of substring completion.
        assert!(
            out.contains("compadd -U"),
            "zsh script must pass `-U` to compadd so fuzzy matches survive: {out}"
        );
    }

    #[test]
    fn zsh_script_forces_menu_mode_for_substring_matches() {
        let out = render(Shell::Zsh);
        // When substring candidates have no common prefix with what the
        // user typed, zsh's default behavior is to insert the unambiguous
        // common prefix — which is empty — effectively erasing the typed
        // text. Forcing menu mode shows the candidates as a selectable
        // list instead.
        assert!(
            out.contains("compstate[insert]=menu"),
            "zsh script must force menu completion so the typed text is not \
             erased by an empty common-prefix insert: {out}"
        );
    }

    #[test]
    fn zsh_script_autoloads_compinit_when_compdef_missing() {
        let out = render(Shell::Zsh);
        // Users frequently `source <(claudine completions zsh)` from rc
        // files that run before `compinit`. The script must cope with that
        // by autoloading the completion system on demand; without the
        // guard, `compdef _claudine claudine` silently fails and the
        // user's TAB presses fall through to generic command-name /
        // filename completion.
        assert!(
            out.contains("$+functions[compdef]"),
            "zsh script must guard `compdef` availability before calling it: {out}"
        );
        assert!(
            out.contains("autoload -Uz compinit"),
            "zsh script must autoload compinit when compdef is missing: {out}"
        );
    }

    #[test]
    fn zsh_script_falls_back_to_files_on_empty_candidates() {
        let out = render(Shell::Zsh);
        assert!(
            out.contains("_files"),
            "zsh script must fall back to `_files` when the engine emits \
             no candidates: {out}"
        );
    }

    #[test]
    fn fish_script_registers_complete_function() {
        let out = render(Shell::Fish);
        assert!(out.contains("function __claudine_complete"));
        assert!(out.contains("claudine __complete --current"));
        assert!(out.contains("complete -c claudine"));
        assert!(out.contains("-a '(__claudine_complete)'"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn fish_script_computes_argv_from_commandline() {
        let out = render(Shell::Fish);
        // commandline -opc gives prior tokens, -ct gives the current
        // partial — the adapter has to reassemble a full argv from both.
        assert!(out.contains("commandline -opc"));
        assert!(out.contains("commandline -ct"));
    }

    #[test]
    fn powershell_script_retains_legacy_bootstrap() {
        let out = render(Shell::PowerShell);
        // The new engine targets bash/zsh/fish only, so powershell keeps
        // the legacy one-liner that activates the `CompleteEnv` runtime
        // path. Its completion surface is whatever `clap_complete`
        // derives from the command tree.
        assert!(out.contains("Invoke-Expression"));
        assert!(out.contains("claudine"));
        assert!(out.contains("$env:COMPLETE"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn elvish_script_retains_legacy_bootstrap() {
        let out = render(Shell::Elvish);
        assert_eq!(
            out, "eval (E:COMPLETE=elvish claudine | slurp)\n",
            "elvish must retain the legacy COMPLETE bootstrap — the new \
             engine targets bash/zsh/fish only"
        );
    }

    #[test]
    fn every_script_ends_with_a_newline() {
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::PowerShell,
            Shell::Elvish,
        ] {
            assert!(
                render(shell).ends_with('\n'),
                "script for {shell:?} missing trailing newline",
            );
        }
    }

    #[test]
    fn primary_shells_invoke_the_hidden_complete_subcommand() {
        // bash/zsh/fish must not rely on `COMPLETE=<shell> claudine`;
        // they shell out to `claudine __complete` directly so every
        // `<TAB>` reaches the current engine.
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let out = render(shell);
            assert!(
                out.contains("claudine __complete --current"),
                "{shell:?} script must invoke the hidden `__complete` \
                 subcommand; output was: {out}"
            );
            assert!(
                !out.contains("COMPLETE="),
                "{shell:?} script must not use the legacy `COMPLETE=<shell>` \
                 bootstrap path; output was: {out}"
            );
        }
    }
}
