//! Shell completion script rendering for `claudine completions <shell>`.
//!
//! Bash, zsh, and fish are served by shell-specific scripts that shell out
//! to the hidden `claudine __complete` subcommand on every `<TAB>`. Routing
//! inside `__complete` flows through [`super::engine::run`], which
//! classifies the cursor slot (root menu, composition positional, setter
//! value) and dispatches to a slot-specific completer.
//!
//! `powershell` and `elvish` retain the legacy `COMPLETE`-based bootstrap
//! snippet; those shells fall back to whatever `clap_complete` derives
//! from the [`crate::args::Cli`] command tree. The legacy `CompleteEnv`
//! path in [`super::maybe_complete`] continues to serve them.
//!
//! ## Installation
//!
//! Bash:
//!
//! ```sh
//! claudine completions bash > ~/.local/share/bash-completion/completions/claudine
//! ```
//!
//! Zsh:
//!
//! ```sh
//! claudine completions zsh > "${fpath[1]}/_claudine"
//! ```
//!
//! Fish:
//!
//! ```sh
//! claudine completions fish > ~/.config/fish/completions/claudine.fish
//! ```
//!
//! The scripts work the same way on every shell: on each `<TAB>`, the
//! registered callback invokes `claudine __complete --current <INDEX> --
//! <argv>`. The engine classifies the cursor position, applies the
//! slot-specific rules, and prints one candidate per line on stdout. The
//! shell then presents those candidates to the user. When `__complete`
//! returns no candidates, the shell script falls back to its default file
//! completion so non-targeted argument positions still behave as if
//! completion were unset.

use clap_complete::Shell;

/// Render the completion script for `shell`.
///
/// Returned string includes a trailing newline so it prints cleanly as a
/// CLI subcommand output. Redirect the output into the shell's completion
/// file; the scripts are idempotent on reload.
pub(crate) fn render(shell: Shell) -> String {
    match shell {
        Shell::Bash => BASH_SCRIPT.to_string(),
        Shell::Zsh => ZSH_SCRIPT.to_string(),
        Shell::Fish => FISH_SCRIPT.to_string(),
        Shell::PowerShell => legacy_bootstrap(Shell::PowerShell),
        Shell::Elvish => legacy_bootstrap(Shell::Elvish),
        // `clap_complete::Shell` is `#[non_exhaustive]`; any future shell
        // that clap adds falls back to the bash-style script. That is the
        // closest documented shape for POSIX-like shells.
        _ => BASH_SCRIPT.to_string(),
    }
}

/// Legacy `COMPLETE=<shell> claudine` one-liner retained for shells the
/// new engine does not target (powershell, elvish). The `CompleteEnv`
/// runtime path in [`super::maybe_complete`] continues to serve these
/// callers.
fn legacy_bootstrap(shell: Shell) -> String {
    match shell {
        Shell::PowerShell => {
            "& { $env:COMPLETE=\"powershell\"; claudine } | Out-String | Invoke-Expression\n"
                .to_string()
        }
        Shell::Elvish => "eval (E:COMPLETE=elvish claudine | slurp)\n".to_string(),
        _ => "source <(COMPLETE=bash claudine)\n".to_string(),
    }
}

/// Bash completion script.
///
/// Registers `_claudine_complete` as the completion function for the
/// `claudine` command. On every `<TAB>`, the function shells out to
/// `claudine __complete --current $COMP_CWORD -- "${COMP_WORDS[@]}"` and
/// treats each line of stdout as a candidate. If the call fails or returns
/// no candidates, bash falls back to default file completion (`bashdefault`
/// + `default`).
///
/// `-o nosort` preserves the order the engine emits (currently alphabetical
/// from a `BTreeSet`, but the contract reserves the right to change this).
/// The `-o nospace` option is intentionally NOT set: bash's default trailing
/// space after a unique match is correct for every engine candidate (files,
/// not directories).
///
/// Setting `CLAUDINE_COMPLETION_DEBUG=1` in the user's shell environment
/// exposes engine stderr at the next `<TAB>` press; without it, stderr is
/// swallowed so transient panics do not corrupt the user's prompt. This is
/// an operational-visibility flag, not a feature flag — the completion
/// engine itself ignores the variable.
const BASH_SCRIPT: &str = r#"# Claudine shell completions (bash)
# Generated by `claudine completions bash`.
#
# The `__complete` subcommand is the Claudine completion engine. It
# classifies the cursor position and prints one candidate per line on
# stdout. When it has no candidates (non-targeted positions, errors) the
# script lets bash fall back to its default file completion.
#
# Set CLAUDINE_COMPLETION_DEBUG=1 to surface engine stderr at the next
# <TAB> press; the default swallows stderr so transient engine panics do
# not corrupt the user's prompt.

_claudine_complete() {
    local IFS=$'\n'
    local candidates
    if [ -n "${CLAUDINE_COMPLETION_DEBUG:-}" ]; then
        candidates=( $(command claudine __complete --current "$COMP_CWORD" -- "${COMP_WORDS[@]}") )
    else
        candidates=( $(command claudine __complete --current "$COMP_CWORD" -- "${COMP_WORDS[@]}" 2>/dev/null) )
    fi
    if [ ${#candidates[@]} -gt 0 ] && [ -n "${candidates[0]}" ]; then
        COMPREPLY=( "${candidates[@]}" )
        return 0
    fi
    COMPREPLY=()
    return 0
}

complete -o nosort -o bashdefault -o default -F _claudine_complete claudine
"#;

/// Zsh completion script.
///
/// Uses the `#compdef claudine` directive so the file can be dropped under
/// any directory in `$fpath` and be autoloaded. The main function splits
/// `__complete`'s stdout on newlines (`(@f)` flag), then feeds the resulting
/// array to `compadd`. When the engine emits nothing, the script falls back
/// to `_files` for default file completion.
///
/// When sourced directly (e.g. `source <(claudine completions zsh)`) before
/// `compinit` has run, `compdef` is not yet defined. The guard at the bottom
/// autoloads and initializes `compinit` on demand so `compdef _claudine
/// claudine` always registers, regardless of rc-file ordering.
///
/// Setting `CLAUDINE_COMPLETION_DEBUG=1` in the user's shell environment
/// exposes engine stderr at the next `<TAB>` press; without it, stderr is
/// swallowed so transient panics do not corrupt the user's prompt. This is
/// an operational-visibility flag, not a feature flag — the completion
/// engine itself ignores the variable.
const ZSH_SCRIPT: &str = r#"#compdef claudine
# Claudine shell completions (zsh)
# Generated by `claudine completions zsh`.
#
# The `__complete` subcommand is the Claudine completion engine. It
# classifies the cursor position and prints one candidate per line on
# stdout. When it has no candidates (non-targeted positions, errors) the
# function falls back to `_files` so default file completion still fires.
#
# Set CLAUDINE_COMPLETION_DEBUG=1 to surface engine stderr at the next
# <TAB> press; the default swallows stderr so transient engine panics do
# not corrupt the user's prompt.

_claudine() {
    local -a candidates
    local current=$((CURRENT - 1))
    if [ -n "${CLAUDINE_COMPLETION_DEBUG:-}" ]; then
        candidates=("${(@f)$(command claudine __complete --current $current -- "${words[@]}")}")
    else
        candidates=("${(@f)$(command claudine __complete --current $current -- "${words[@]}" 2>/dev/null)}")
    fi
    if (( ${#candidates[@]} > 0 )) && [[ -n "${candidates[1]}" ]]; then
        # Engine candidates may be fuzzy/substring matches, so they often
        # share no common prefix with what the user typed. Without the
        # guards below, zsh computes an empty unambiguous prefix and
        # silently erases the typed text.
        #
        # - `-U` suppresses compadd's default prefix-match filter so the
        #   candidates survive at all.
        # - `-Q` skips quoting of special characters (paths are already in
        #   their final shell form).
        # - `compstate[insert]=menu` forces menu-completion mode so the
        #   engine's substring matches are presented as choices instead of
        #   being collapsed into a non-existent common prefix.
        # - `-S ''` suppresses the trailing space compadd appends after a
        #   unique match; path candidates already have their terminator.
        compstate[insert]=menu
        compadd -U -Q -S '' -- "${candidates[@]}"
        return 0
    fi
    _files
}

# When this script is sourced before `compinit` has run, `compdef` is not
# yet defined. Autoload and initialize the completion system on demand so
# the registration below always succeeds.
if ! (( $+functions[compdef] )); then
    autoload -Uz compinit
    compinit -u 2>/dev/null
fi
compdef _claudine claudine
"#;

/// Fish completion script.
///
/// Fish's completion model merges every `complete -c claudine ...` command
/// into one candidate set, so the script registers a single completion that
/// delegates entirely to `__complete`. The `-f` registration keeps fish from
/// mixing default file candidates into curated Claudine-owned slots; when the
/// engine returns nothing, the function explicitly calls
/// `__fish_complete_path` so non-targeted positions still get native file
/// completion.
///
/// Setting `CLAUDINE_COMPLETION_DEBUG=1` in the user's shell environment
/// exposes engine stderr at the next `<TAB>` press; without it, stderr is
/// swallowed so transient panics do not corrupt the user's prompt. This is
/// an operational-visibility flag, not a feature flag — the completion
/// engine itself ignores the variable.
const FISH_SCRIPT: &str = r#"# Claudine shell completions (fish)
# Generated by `claudine completions fish`.
#
# The `__complete` subcommand is the Claudine completion engine. It
# classifies the cursor position and prints one candidate per line on
# stdout. When it has no candidates (non-targeted positions, errors) this
# function falls back to fish's path completer.
#
# Set CLAUDINE_COMPLETION_DEBUG=1 to surface engine stderr at the next
# <TAB> press; the default swallows stderr so transient engine panics do
# not corrupt the user's prompt.

function __claudine_complete
    set -l tokens (commandline -opc)
    set -l current_partial (commandline -ct)
    set -l argv_all claudine $tokens[2..] $current_partial
    set -l idx (math (count $argv_all) - 1)
    set -l candidates
    if set -q CLAUDINE_COMPLETION_DEBUG
        set candidates (command claudine __complete --current $idx -- $argv_all)
    else
        set candidates (command claudine __complete --current $idx -- $argv_all 2>/dev/null)
    end
    if test (count $candidates) -gt 0
        printf '%s\n' $candidates
    else
        __fish_complete_path $current_partial
    end
end

complete -c claudine -f -a '(__claudine_complete)'
"#;

#[cfg(test)]
mod tests;
