// This code was automatically generated by schematic-gen. Do not edit manually.

use serde::{Deserialize, Serialize};
use crate::shared::{RequestParts, SchematicError};
use super::responses::*;
/// Request for `ListModels` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListModelsRequest;
///
/// let request = ListModelsRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelsRequest {}
impl ListModelsRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/models".to_string();
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListModelsRequest {
    type Response = Vec<ModelInfo>;
    const ENDPOINT_ID: &'static str = "ListModels";
}
/// Request for `GetModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetModelRequest;
///
/// let request = GetModelRequest::new("repo_id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetModelRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
}
impl GetModelRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>) -> Self {
        Self { repo_id: repo_id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/models/{}", & self.repo_id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetModelRequest {
    fn from(param: &str) -> Self {
        Self { repo_id: param.to_string() }
    }
}
impl From<String> for GetModelRequest {
    fn from(param: String) -> Self {
        Self { repo_id: param }
    }
}
impl crate::shared::EndpointSpec for GetModelRequest {
    type Response = ModelInfo;
    const ENDPOINT_ID: &'static str = "GetModel";
}
/// Request for `ListModelFiles` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListModelFilesRequest;
///
/// let request = ListModelFilesRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelFilesRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl ListModelFilesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/models/{}/tree/{}", & self.repo_id, urlencoding::encode(& self.revision
            .to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListModelFilesRequest {
    type Response = Vec<RepoFile>;
    const ENDPOINT_ID: &'static str = "ListModelFiles";
}
/// Request for `GetModelFile` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetModelFileRequest;
///
/// let request = GetModelFileRequest::new("repo_id_value", "revision_value", "path_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetModelFileRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
    /// Path parameter: path
    pub path: String,
}
impl GetModelFileRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        repo_id: impl Into<String>,
        revision: impl Into<String>,
        path: impl Into<String>,
    ) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
            path: path.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/models/{}/blob/{}/{}", & self.repo_id, urlencoding::encode(& self.revision
            .to_string()), & self.path
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetModelFileRequest {
    type Response = FileMetadata;
    const ENDPOINT_ID: &'static str = "GetModelFile";
}
/// Request for `ListModelCommits` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListModelCommitsRequest;
///
/// let request = ListModelCommitsRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelCommitsRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl ListModelCommitsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/models/{}/commits/{}", & self.repo_id, urlencoding::encode(& self.revision
            .to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListModelCommitsRequest {
    type Response = Vec<Commit>;
    const ENDPOINT_ID: &'static str = "ListModelCommits";
}
/// Request for `GetModelReadme` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetModelReadmeRequest;
///
/// let request = GetModelReadmeRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetModelReadmeRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl GetModelReadmeRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/models/{}/resolve/{}/README.md", & self.repo_id, urlencoding::encode(& self
            .revision.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetModelReadmeRequest {
    type Response = String;
    const ENDPOINT_ID: &'static str = "GetModelReadme";
}
/// Request for `ListModelDiscussions` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListModelDiscussionsRequest;
///
/// let request = ListModelDiscussionsRequest::new("repo_id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelDiscussionsRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
}
impl ListModelDiscussionsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>) -> Self {
        Self { repo_id: repo_id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/models/{}/discussions", & self.repo_id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListModelDiscussionsRequest {
    fn from(param: &str) -> Self {
        Self { repo_id: param.to_string() }
    }
}
impl From<String> for ListModelDiscussionsRequest {
    fn from(param: String) -> Self {
        Self { repo_id: param }
    }
}
impl crate::shared::EndpointSpec for ListModelDiscussionsRequest {
    type Response = DiscussionList;
    const ENDPOINT_ID: &'static str = "ListModelDiscussions";
}
/// Request for `GetModelCard` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetModelCardRequest;
///
/// let request = GetModelCardRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetModelCardRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl GetModelCardRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/models/{}/resolve/{}/model_card.md", & self.repo_id, urlencoding::encode(&
            self.revision.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetModelCardRequest {
    type Response = String;
    const ENDPOINT_ID: &'static str = "GetModelCard";
}
/// Request for `ListDatasets` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListDatasetsRequest;
///
/// let request = ListDatasetsRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListDatasetsRequest {}
impl ListDatasetsRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/datasets".to_string();
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListDatasetsRequest {
    type Response = Vec<DatasetInfo>;
    const ENDPOINT_ID: &'static str = "ListDatasets";
}
/// Request for `GetDataset` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetDatasetRequest;
///
/// let request = GetDatasetRequest::new("repo_id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetDatasetRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
}
impl GetDatasetRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>) -> Self {
        Self { repo_id: repo_id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/datasets/{}", & self.repo_id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetDatasetRequest {
    fn from(param: &str) -> Self {
        Self { repo_id: param.to_string() }
    }
}
impl From<String> for GetDatasetRequest {
    fn from(param: String) -> Self {
        Self { repo_id: param }
    }
}
impl crate::shared::EndpointSpec for GetDatasetRequest {
    type Response = DatasetInfo;
    const ENDPOINT_ID: &'static str = "GetDataset";
}
/// Request for `ListDatasetFiles` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListDatasetFilesRequest;
///
/// let request = ListDatasetFilesRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListDatasetFilesRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl ListDatasetFilesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/datasets/{}/tree/{}", & self.repo_id, urlencoding::encode(& self.revision
            .to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListDatasetFilesRequest {
    type Response = Vec<RepoFile>;
    const ENDPOINT_ID: &'static str = "ListDatasetFiles";
}
/// Request for `GetDatasetFile` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetDatasetFileRequest;
///
/// let request = GetDatasetFileRequest::new("repo_id_value", "revision_value", "path_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetDatasetFileRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
    /// Path parameter: path
    pub path: String,
}
impl GetDatasetFileRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        repo_id: impl Into<String>,
        revision: impl Into<String>,
        path: impl Into<String>,
    ) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
            path: path.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/datasets/{}/blob/{}/{}", & self.repo_id, urlencoding::encode(& self
            .revision.to_string()), & self.path
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetDatasetFileRequest {
    type Response = FileMetadata;
    const ENDPOINT_ID: &'static str = "GetDatasetFile";
}
/// Request for `ListDatasetCommits` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListDatasetCommitsRequest;
///
/// let request = ListDatasetCommitsRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListDatasetCommitsRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl ListDatasetCommitsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/datasets/{}/commits/{}", & self.repo_id, urlencoding::encode(& self
            .revision.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListDatasetCommitsRequest {
    type Response = Vec<Commit>;
    const ENDPOINT_ID: &'static str = "ListDatasetCommits";
}
/// Request for `GetDatasetReadme` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetDatasetReadmeRequest;
///
/// let request = GetDatasetReadmeRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetDatasetReadmeRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl GetDatasetReadmeRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/datasets/{}/resolve/{}/README.md", & self.repo_id, urlencoding::encode(&
            self.revision.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetDatasetReadmeRequest {
    type Response = String;
    const ENDPOINT_ID: &'static str = "GetDatasetReadme";
}
/// Request for `ListSpaces` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListSpacesRequest;
///
/// let request = ListSpacesRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListSpacesRequest {}
impl ListSpacesRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/spaces".to_string();
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListSpacesRequest {
    type Response = Vec<SpaceInfo>;
    const ENDPOINT_ID: &'static str = "ListSpaces";
}
/// Request for `GetSpace` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetSpaceRequest;
///
/// let request = GetSpaceRequest::new("repo_id_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetSpaceRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
}
impl GetSpaceRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>) -> Self {
        Self { repo_id: repo_id.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!("/spaces/{}", & self.repo_id);
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetSpaceRequest {
    fn from(param: &str) -> Self {
        Self { repo_id: param.to_string() }
    }
}
impl From<String> for GetSpaceRequest {
    fn from(param: String) -> Self {
        Self { repo_id: param }
    }
}
impl crate::shared::EndpointSpec for GetSpaceRequest {
    type Response = SpaceInfo;
    const ENDPOINT_ID: &'static str = "GetSpace";
}
/// Request for `ListSpaceFiles` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListSpaceFilesRequest;
///
/// let request = ListSpaceFilesRequest::new("repo_id_value", "revision_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListSpaceFilesRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
}
impl ListSpaceFilesRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(repo_id: impl Into<String>, revision: impl Into<String>) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/spaces/{}/tree/{}", & self.repo_id, urlencoding::encode(& self.revision
            .to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListSpaceFilesRequest {
    type Response = Vec<RepoFile>;
    const ENDPOINT_ID: &'static str = "ListSpaceFiles";
}
/// Request for `GetSpaceFile` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetSpaceFileRequest;
///
/// let request = GetSpaceFileRequest::new("repo_id_value", "revision_value", "path_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetSpaceFileRequest {
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Path parameter: revision
    pub revision: String,
    /// Path parameter: path
    pub path: String,
}
impl GetSpaceFileRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(
        repo_id: impl Into<String>,
        revision: impl Into<String>,
        path: impl Into<String>,
    ) -> Self {
        Self {
            repo_id: repo_id.into(),
            revision: revision.into(),
            path: path.into(),
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/spaces/{}/blob/{}/{}", & self.repo_id, urlencoding::encode(& self.revision
            .to_string()), & self.path
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for GetSpaceFileRequest {
    type Response = FileMetadata;
    const ENDPOINT_ID: &'static str = "GetSpaceFile";
}
/// Request for `CreateRepo` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::{CreateRepoRequest, CreateRepoBody};
///
/// let body = CreateRepoBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = CreateRepoRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateRepoRequest {
    /// Request body
    pub body: CreateRepoBody,
}
impl CreateRepoRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: CreateRepoBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/repos/create".to_string();
        Ok((
            "POST",
            path,
            Some(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<CreateRepoBody> for CreateRepoRequest {
    fn from(body: CreateRepoBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for CreateRepoRequest {
    type Response = RepoUrl;
    const ENDPOINT_ID: &'static str = "CreateRepo";
}
/// Request for `DeleteRepo` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::{DeleteRepoRequest, DeleteRepoBody};
///
/// let body = DeleteRepoBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = DeleteRepoRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteRepoRequest {
    /// Request body
    pub body: DeleteRepoBody,
}
impl DeleteRepoRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: DeleteRepoBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/repos/delete".to_string();
        Ok((
            "DELETE",
            path,
            Some(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<DeleteRepoBody> for DeleteRepoRequest {
    fn from(body: DeleteRepoBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for DeleteRepoRequest {
    type Response = StatusResponse;
    const ENDPOINT_ID: &'static str = "DeleteRepo";
}
/// Request for `UpdateRepoSettings` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::{UpdateRepoSettingsRequest, UpdateRepoSettingsBody};
///
/// let body = UpdateRepoSettingsBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = UpdateRepoSettingsRequest::new("repo_type_value", "repo_id_value", body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateRepoSettingsRequest {
    /// Path parameter: repo_type
    pub repo_type: String,
    /// Path parameter: repo_id
    pub repo_id: String,
    /// Request body
    pub body: UpdateRepoSettingsBody,
}
impl UpdateRepoSettingsRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(
        repo_type: impl Into<String>,
        repo_id: impl Into<String>,
        body: UpdateRepoSettingsBody,
    ) -> Self {
        Self {
            repo_type: repo_type.into(),
            repo_id: repo_id.into(),
            body,
        }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/repos/{}/{}/settings", urlencoding::encode(& self.repo_type.to_string()), &
            self.repo_id
        );
        Ok((
            "PUT",
            path,
            Some(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl crate::shared::EndpointSpec for UpdateRepoSettingsRequest {
    type Response = StatusResponse;
    const ENDPOINT_ID: &'static str = "UpdateRepoSettings";
}
/// Request for `MoveRepo` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::{MoveRepoRequest, MoveRepoBody};
///
/// let body = MoveRepoBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = MoveRepoRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MoveRepoRequest {
    /// Request body
    pub body: MoveRepoBody,
}
impl MoveRepoRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: MoveRepoBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/repos/move".to_string();
        Ok((
            "POST",
            path,
            Some(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<MoveRepoBody> for MoveRepoRequest {
    fn from(body: MoveRepoBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for MoveRepoRequest {
    type Response = StatusResponse;
    const ENDPOINT_ID: &'static str = "MoveRepo";
}
/// Request for `WhoAmI` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::WhoAmIRequest;
///
/// let request = WhoAmIRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WhoAmIRequest {}
impl WhoAmIRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/whoami-v2".to_string();
        Ok(("GET", path, None, vec![]))
    }
}
impl crate::shared::EndpointSpec for WhoAmIRequest {
    type Response = UserInfo;
    const ENDPOINT_ID: &'static str = "WhoAmI";
}
/// Request for `GetUser` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetUserRequest;
///
/// let request = GetUserRequest::new("username_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetUserRequest {
    /// Path parameter: username
    pub username: String,
}
impl GetUserRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(username: impl Into<String>) -> Self {
        Self { username: username.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/users/{}", urlencoding::encode(& self.username.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetUserRequest {
    fn from(param: &str) -> Self {
        Self {
            username: param.to_string(),
        }
    }
}
impl From<String> for GetUserRequest {
    fn from(param: String) -> Self {
        Self { username: param }
    }
}
impl crate::shared::EndpointSpec for GetUserRequest {
    type Response = UserInfo;
    const ENDPOINT_ID: &'static str = "GetUser";
}
/// Request for `ListUserRepos` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::ListUserReposRequest;
///
/// let request = ListUserReposRequest::new("username_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListUserReposRequest {
    /// Path parameter: username
    pub username: String,
}
impl ListUserReposRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(username: impl Into<String>) -> Self {
        Self { username: username.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/users/{}/repos", urlencoding::encode(& self.username.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for ListUserReposRequest {
    fn from(param: &str) -> Self {
        Self {
            username: param.to_string(),
        }
    }
}
impl From<String> for ListUserReposRequest {
    fn from(param: String) -> Self {
        Self { username: param }
    }
}
impl crate::shared::EndpointSpec for ListUserReposRequest {
    type Response = Vec<RepoInfo>;
    const ENDPOINT_ID: &'static str = "ListUserRepos";
}
/// Request for `GetUserCollections` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::huggingface::GetUserCollectionsRequest;
///
/// let request = GetUserCollectionsRequest::new("username_value")
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GetUserCollectionsRequest {
    /// Path parameter: username
    pub username: String,
}
impl GetUserCollectionsRequest {
    /// Creates a new request with the required path parameters.
    pub fn new(username: impl Into<String>) -> Self {
        Self { username: username.into() }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - Optional JSON body string
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = format!(
            "/users/{}/collections", urlencoding::encode(& self.username.to_string())
        );
        Ok(("GET", path, None, vec![]))
    }
}
impl From<&str> for GetUserCollectionsRequest {
    fn from(param: &str) -> Self {
        Self {
            username: param.to_string(),
        }
    }
}
impl From<String> for GetUserCollectionsRequest {
    fn from(param: String) -> Self {
        Self { username: param }
    }
}
impl crate::shared::EndpointSpec for GetUserCollectionsRequest {
    type Response = Vec<Collection>;
    const ENDPOINT_ID: &'static str = "GetUserCollections";
}
/// Request enum for HuggingFaceHub API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum HuggingFaceHubRequest {
    /// Lists models with optional filtering. Query params: search, author, filter, sort, direction, limit, full, config
    ListModels(ListModelsRequest),
    /// Gets detailed information about a specific model
    GetModel(GetModelRequest),
    /// Lists files in a model repository at a specific revision
    ListModelFiles(ListModelFilesRequest),
    /// Gets file metadata for a specific file in a model repository
    GetModelFile(GetModelFileRequest),
    /// Lists commits for a model repository
    ListModelCommits(ListModelCommitsRequest),
    /// Gets the README file content for a model
    GetModelReadme(GetModelReadmeRequest),
    /// Lists discussions for a model repository
    ListModelDiscussions(ListModelDiscussionsRequest),
    /// Gets the model card file content
    GetModelCard(GetModelCardRequest),
    /// Lists datasets with optional filtering. Query params: search, author, filter, sort, direction, limit, full
    ListDatasets(ListDatasetsRequest),
    /// Gets detailed information about a specific dataset
    GetDataset(GetDatasetRequest),
    /// Lists files in a dataset repository at a specific revision
    ListDatasetFiles(ListDatasetFilesRequest),
    /// Gets file metadata for a specific file in a dataset repository
    GetDatasetFile(GetDatasetFileRequest),
    /// Lists commits for a dataset repository
    ListDatasetCommits(ListDatasetCommitsRequest),
    /// Gets the README file content for a dataset
    GetDatasetReadme(GetDatasetReadmeRequest),
    /// Lists spaces with optional filtering. Query params: search, author, filter, sort, direction, limit
    ListSpaces(ListSpacesRequest),
    /// Gets detailed information about a specific space
    GetSpace(GetSpaceRequest),
    /// Lists files in a space repository at a specific revision
    ListSpaceFiles(ListSpaceFilesRequest),
    /// Gets file metadata for a specific file in a space repository
    GetSpaceFile(GetSpaceFileRequest),
    /// Creates a new repository (model, dataset, or space)
    CreateRepo(CreateRepoRequest),
    /// Deletes a repository
    DeleteRepo(DeleteRepoRequest),
    /// Updates repository settings (visibility, gated access, etc.)
    UpdateRepoSettings(UpdateRepoSettingsRequest),
    /// Moves/renames a repository
    MoveRepo(MoveRepoRequest),
    /// Gets information about the authenticated user
    WhoAmI(WhoAmIRequest),
    /// Gets public information about a user
    GetUser(GetUserRequest),
    /// Lists repositories owned by a user
    ListUserRepos(ListUserReposRequest),
    /// Gets collections created by a user
    GetUserCollections(GetUserCollectionsRequest),
}
impl HuggingFaceHubRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::ListModels(req) => req.into_parts(),
            Self::GetModel(req) => req.into_parts(),
            Self::ListModelFiles(req) => req.into_parts(),
            Self::GetModelFile(req) => req.into_parts(),
            Self::ListModelCommits(req) => req.into_parts(),
            Self::GetModelReadme(req) => req.into_parts(),
            Self::ListModelDiscussions(req) => req.into_parts(),
            Self::GetModelCard(req) => req.into_parts(),
            Self::ListDatasets(req) => req.into_parts(),
            Self::GetDataset(req) => req.into_parts(),
            Self::ListDatasetFiles(req) => req.into_parts(),
            Self::GetDatasetFile(req) => req.into_parts(),
            Self::ListDatasetCommits(req) => req.into_parts(),
            Self::GetDatasetReadme(req) => req.into_parts(),
            Self::ListSpaces(req) => req.into_parts(),
            Self::GetSpace(req) => req.into_parts(),
            Self::ListSpaceFiles(req) => req.into_parts(),
            Self::GetSpaceFile(req) => req.into_parts(),
            Self::CreateRepo(req) => req.into_parts(),
            Self::DeleteRepo(req) => req.into_parts(),
            Self::UpdateRepoSettings(req) => req.into_parts(),
            Self::MoveRepo(req) => req.into_parts(),
            Self::WhoAmI(req) => req.into_parts(),
            Self::GetUser(req) => req.into_parts(),
            Self::ListUserRepos(req) => req.into_parts(),
            Self::GetUserCollections(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::ListModels(_) => {
                <ListModelsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetModel(_) => {
                <GetModelRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListModelFiles(_) => {
                <ListModelFilesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetModelFile(_) => {
                <GetModelFileRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListModelCommits(_) => {
                <ListModelCommitsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetModelReadme(_) => {
                <GetModelReadmeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListModelDiscussions(_) => {
                <ListModelDiscussionsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetModelCard(_) => {
                <GetModelCardRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListDatasets(_) => {
                <ListDatasetsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetDataset(_) => {
                <GetDatasetRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListDatasetFiles(_) => {
                <ListDatasetFilesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetDatasetFile(_) => {
                <GetDatasetFileRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListDatasetCommits(_) => {
                <ListDatasetCommitsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetDatasetReadme(_) => {
                <GetDatasetReadmeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListSpaces(_) => {
                <ListSpacesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetSpace(_) => {
                <GetSpaceRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListSpaceFiles(_) => {
                <ListSpaceFilesRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetSpaceFile(_) => {
                <GetSpaceFileRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::CreateRepo(_) => {
                <CreateRepoRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::DeleteRepo(_) => {
                <DeleteRepoRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::UpdateRepoSettings(_) => {
                <UpdateRepoSettingsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::MoveRepo(_) => {
                <MoveRepoRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::WhoAmI(_) => {
                <WhoAmIRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetUser(_) => {
                <GetUserRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListUserRepos(_) => {
                <ListUserReposRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::GetUserCollections(_) => {
                <GetUserCollectionsRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
    /// Returns how this endpoint's response body is decoded.
    ///
    /// The generic `request::<T>()` decodes JSON; it consults this to
    /// reject text, binary, and empty endpoints up front.
    #[must_use]
    pub fn response_kind(&self) -> crate::shared::ResponseKind {
        match self {
            Self::ListModels(_) => crate::shared::ResponseKind::Json,
            Self::GetModel(_) => crate::shared::ResponseKind::Json,
            Self::ListModelFiles(_) => crate::shared::ResponseKind::Json,
            Self::GetModelFile(_) => crate::shared::ResponseKind::Json,
            Self::ListModelCommits(_) => crate::shared::ResponseKind::Json,
            Self::GetModelReadme(_) => crate::shared::ResponseKind::Text,
            Self::ListModelDiscussions(_) => crate::shared::ResponseKind::Json,
            Self::GetModelCard(_) => crate::shared::ResponseKind::Text,
            Self::ListDatasets(_) => crate::shared::ResponseKind::Json,
            Self::GetDataset(_) => crate::shared::ResponseKind::Json,
            Self::ListDatasetFiles(_) => crate::shared::ResponseKind::Json,
            Self::GetDatasetFile(_) => crate::shared::ResponseKind::Json,
            Self::ListDatasetCommits(_) => crate::shared::ResponseKind::Json,
            Self::GetDatasetReadme(_) => crate::shared::ResponseKind::Text,
            Self::ListSpaces(_) => crate::shared::ResponseKind::Json,
            Self::GetSpace(_) => crate::shared::ResponseKind::Json,
            Self::ListSpaceFiles(_) => crate::shared::ResponseKind::Json,
            Self::GetSpaceFile(_) => crate::shared::ResponseKind::Json,
            Self::CreateRepo(_) => crate::shared::ResponseKind::Json,
            Self::DeleteRepo(_) => crate::shared::ResponseKind::Json,
            Self::UpdateRepoSettings(_) => crate::shared::ResponseKind::Json,
            Self::MoveRepo(_) => crate::shared::ResponseKind::Json,
            Self::WhoAmI(_) => crate::shared::ResponseKind::Json,
            Self::GetUser(_) => crate::shared::ResponseKind::Json,
            Self::ListUserRepos(_) => crate::shared::ResponseKind::Json,
            Self::GetUserCollections(_) => crate::shared::ResponseKind::Json,
        }
    }
}
impl From<ListModelsRequest> for HuggingFaceHubRequest {
    fn from(req: ListModelsRequest) -> Self {
        Self::ListModels(req)
    }
}
impl From<GetModelRequest> for HuggingFaceHubRequest {
    fn from(req: GetModelRequest) -> Self {
        Self::GetModel(req)
    }
}
impl From<ListModelFilesRequest> for HuggingFaceHubRequest {
    fn from(req: ListModelFilesRequest) -> Self {
        Self::ListModelFiles(req)
    }
}
impl From<GetModelFileRequest> for HuggingFaceHubRequest {
    fn from(req: GetModelFileRequest) -> Self {
        Self::GetModelFile(req)
    }
}
impl From<ListModelCommitsRequest> for HuggingFaceHubRequest {
    fn from(req: ListModelCommitsRequest) -> Self {
        Self::ListModelCommits(req)
    }
}
impl From<GetModelReadmeRequest> for HuggingFaceHubRequest {
    fn from(req: GetModelReadmeRequest) -> Self {
        Self::GetModelReadme(req)
    }
}
impl From<ListModelDiscussionsRequest> for HuggingFaceHubRequest {
    fn from(req: ListModelDiscussionsRequest) -> Self {
        Self::ListModelDiscussions(req)
    }
}
impl From<GetModelCardRequest> for HuggingFaceHubRequest {
    fn from(req: GetModelCardRequest) -> Self {
        Self::GetModelCard(req)
    }
}
impl From<ListDatasetsRequest> for HuggingFaceHubRequest {
    fn from(req: ListDatasetsRequest) -> Self {
        Self::ListDatasets(req)
    }
}
impl From<GetDatasetRequest> for HuggingFaceHubRequest {
    fn from(req: GetDatasetRequest) -> Self {
        Self::GetDataset(req)
    }
}
impl From<ListDatasetFilesRequest> for HuggingFaceHubRequest {
    fn from(req: ListDatasetFilesRequest) -> Self {
        Self::ListDatasetFiles(req)
    }
}
impl From<GetDatasetFileRequest> for HuggingFaceHubRequest {
    fn from(req: GetDatasetFileRequest) -> Self {
        Self::GetDatasetFile(req)
    }
}
impl From<ListDatasetCommitsRequest> for HuggingFaceHubRequest {
    fn from(req: ListDatasetCommitsRequest) -> Self {
        Self::ListDatasetCommits(req)
    }
}
impl From<GetDatasetReadmeRequest> for HuggingFaceHubRequest {
    fn from(req: GetDatasetReadmeRequest) -> Self {
        Self::GetDatasetReadme(req)
    }
}
impl From<ListSpacesRequest> for HuggingFaceHubRequest {
    fn from(req: ListSpacesRequest) -> Self {
        Self::ListSpaces(req)
    }
}
impl From<GetSpaceRequest> for HuggingFaceHubRequest {
    fn from(req: GetSpaceRequest) -> Self {
        Self::GetSpace(req)
    }
}
impl From<ListSpaceFilesRequest> for HuggingFaceHubRequest {
    fn from(req: ListSpaceFilesRequest) -> Self {
        Self::ListSpaceFiles(req)
    }
}
impl From<GetSpaceFileRequest> for HuggingFaceHubRequest {
    fn from(req: GetSpaceFileRequest) -> Self {
        Self::GetSpaceFile(req)
    }
}
impl From<CreateRepoRequest> for HuggingFaceHubRequest {
    fn from(req: CreateRepoRequest) -> Self {
        Self::CreateRepo(req)
    }
}
impl From<DeleteRepoRequest> for HuggingFaceHubRequest {
    fn from(req: DeleteRepoRequest) -> Self {
        Self::DeleteRepo(req)
    }
}
impl From<UpdateRepoSettingsRequest> for HuggingFaceHubRequest {
    fn from(req: UpdateRepoSettingsRequest) -> Self {
        Self::UpdateRepoSettings(req)
    }
}
impl From<MoveRepoRequest> for HuggingFaceHubRequest {
    fn from(req: MoveRepoRequest) -> Self {
        Self::MoveRepo(req)
    }
}
impl From<WhoAmIRequest> for HuggingFaceHubRequest {
    fn from(req: WhoAmIRequest) -> Self {
        Self::WhoAmI(req)
    }
}
impl From<GetUserRequest> for HuggingFaceHubRequest {
    fn from(req: GetUserRequest) -> Self {
        Self::GetUser(req)
    }
}
impl From<ListUserReposRequest> for HuggingFaceHubRequest {
    fn from(req: ListUserReposRequest) -> Self {
        Self::ListUserRepos(req)
    }
}
impl From<GetUserCollectionsRequest> for HuggingFaceHubRequest {
    fn from(req: GetUserCollectionsRequest) -> Self {
        Self::GetUserCollections(req)
    }
}
