BOLD := '\033[1m'
RESET := '\033[0m'

default:
    @echo "{{BOLD}}Tree Hugger{{RESET}} CLI and Library"
    @echo
    @just --list | grep -v 'default'

# build library and CLI
build *args="":
    @echo "Building ..."
    @echo
    @cargo build -p tree-hugger -- {{args}}
    @cargo build -p tree-hugger-cli -- {{args}}
    @echo

# test library and CLI
test *args="":
    @echo "Testing {{BOLD}}Library{{RESET}} code"
    @echo ""
    @cargo test -p tree-hugger -- {{args}}
    @echo ""
    @echo "Testing {{BOLD}}CLI{{RESET}} code"
    @echo ""
    @cargo test -p tree-hugger-cli -- {{args}}

# lint with clippy
lint *args="":
    @cargo clippy -p tree-hugger -p tree-hugger-cli -- {{args}}

# install latest release version of CLI
install *args="":
    @echo ""
    @echo "{{BOLD}}Build Tree Hugger Library{{RESET}}"
    @cargo build --release -p tree-hugger-cli
    @echo "{{BOLD}}{{YELLOW}}Installing Tree Hugger CLI{{RESET}}"
    @cargo install --path cli -- {{args}}
    @echo ""
    @echo "{{BOLD}}{{BLUE}}Tree Hugger CLI installed{{RESET}}"
    @echo ""

# build and show the docs for the library code
docs:
    @echo "Building and then showing latest docs for the library code"
    @echo ""
    @cargo doc -p tree-hugger --open

# build and show the docs for the tree-hugger CLI
cli_docs:
    @echo "Building and then showing latest docs for the tree-hugger CLI"
    @echo ""
    @cargo doc -p tree-hugger --open

# run the latest debug build of the CLI
hug *args="":
    @cargo run -p tree-hugger-cli -- {{args}}
