[package]
name = "sniff-cli"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[[bin]]
name = "sniff"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive", "wrap_help"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
futures = "0.3"
inquire = "0.9"
git2 = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
biscuit-terminal = { path = "../../biscuit-terminal/lib" }
darkmatter = { path = "../../darkmatter/lib" }
sniff = { path = "../lib", features = ["network", "remote"] }
strum = { version = "0.28", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
assert_cmd = "2"
expectrl = "0.8"
insta = { version = "1", features = ["json"] }
predicates = "3"
