[package]
name = "biscuit-icon-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "icon"
path = "src/main.rs"

[features]
default = []
image = ["biscuit-icon/image"]

[dependencies]
biscuit-icon = { path = "../lib" }
biscuit-terminal = { path = "../../biscuit-terminal/lib" }
clap = { version = "4.5", features = ["derive", "env", "unstable-ext", "wrap_help"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
color-eyre = "0.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2"
biscuit-test-harness = { path = "../../biscuit-test-harness" }
predicates = "3"
serial_test = "3"
tempfile = "3"
test-toolkit = { path = "../../tools/test-toolkit" }
unicode-width = "0.2"
