/**
 * Source-side test population, read with tree-sitter (`tree-sitter-rust`).
 *
 * This is *source discovery*, deliberately separate from runner discovery:
 * it says which functions carry a test attribute in the files on disk, under
 * which `cfg` gates, and in which module. The runner listing (`capture`) is
 * the authority on what is executable; the reconciler diffs the two and every
 * difference needs a declared exclusion. Nothing here claims completeness for
 * code a macro generates — those records are flagged and the diff reports
 * them as diagnostics rather than silently counting or dropping them.
 *
 * Two bounded macro forms are resolved because the repository uses them:
 *
 * - a `macro_rules!` template whose body contains a test attribute and
 *   `fn $ident` yields one identity per invocation, named by the invocation's
 *   corresponding argument (`fromMacro: true`, template `cfg` inherited);
 * - a macro invocation whose body carries literal test items — `proptest! {
 *   #[test] fn name(...) { ... } }` — yields one identity per such item
 *   (`fromMacro: true`), read from the token stream since the grammar does
 *   not parse macro bodies;
 * - `#[rstest]` with `#[case]`/`#[values]`, `test_case`, and
 *   `parameterized` mark `macroExpanded: true`: the runner lists derived names
 *   (`name::case_1`) that the source cannot enumerate.
 *
 * Known grammar gaps (tree-sitter-rust 0.24): `&raw`/`raw` as an ordinary
 * identifier and `unsafe extern` blocks produce local `ERROR` nodes. They are
 * reported as `parse-error` diagnostics; the surrounding items still parse,
 * and the Claudine compatibility test proves no test is lost to them.
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, sep } from "node:path";
import { Language, Parser, type Node as SyntaxNode } from "web-tree-sitter";

export type TargetKind = "lib" | "bin" | "integration" | "bench" | "example" | "unknown";

export interface SourceTest {
  pkg: string;
  /** Repository-relative path with `/` separators. */
  file: string;
  line: number;
  /** Function name (the identity's leaf). */
  name: string;
  /** Module path from the file layout plus inline `mod` nesting, root first. */
  modulePath: string[];
  /** `modulePath::name`, the shape nextest prints after the binary id. */
  identity: string;
  kind: TargetKind;
  /** Integration/bin/bench/example target stem; absent for the lib target. */
  target?: string;
  /** Attribute names in source order (`test`, `tokio::test`, `cfg`, `ignore`, ...). */
  attributes: string[];
  /** Platform/feature gates in force: file `#![cfg]`, enclosing `mod` cfgs, and the fn's own; `cfg(test)` excluded. */
  cfg: string[];
  ignored: boolean;
  ignoreReason?: string;
  /** Generated by a `macro_rules!` template at an invocation site. */
  fromMacro: boolean;
  /** Parameterized by an attribute macro; the runner derives the executable names. */
  macroExpanded: boolean;
}

export interface SourceDiagnostic {
  kind: "parse-error" | "macro-unresolved";
  file: string;
  line: number;
  detail: string;
}

export interface SourcePopulation {
  tests: SourceTest[];
  diagnostics: SourceDiagnostic[];
  filesScanned: number;
}

const TEST_ATTRIBUTES = new Set(["test", "tokio::test", "rstest", "bench", "async_std::test", "serial_test::serial"]);
const EXPANDING_ATTRIBUTES = new Set(["case", "values", "test_case", "proptest", "parameterized"]);

let parserPromise: Promise<Parser> | undefined;

function parser(): Promise<Parser> {
  parserPromise ??= (async () => {
    await Parser.init();
    const instance = new Parser();
    const require = createRequire(import.meta.url);
    const wasm = join(dirname(require.resolve("tree-sitter-rust/package.json")), "tree-sitter-rust.wasm");
    instance.setLanguage(await Language.load(wasm));
    return instance;
  })();
  return parserPromise;
}

interface Attribute {
  name: string;
  args: string;
  text: string;
}

/** `#[name(args)]` / `#[name = value]` / `#[name]`, by text: the grammar's inner shape varies by form. */
export function parseAttributeText(text: string): Attribute {
  const inner = text.replace(/^#!?\[/, "").replace(/\]$/, "").trim();
  const match = /^([A-Za-z_][\w:]*)\s*(.*)$/s.exec(inner);
  if (!match) return { name: inner, args: "", text };
  return { name: match[1]!, args: (match[2] ?? "").trim(), text };
}

function attributeRun(node: SyntaxNode): Attribute[] {
  const attributes: Attribute[] = [];
  let sibling = node.previousNamedSibling;
  while (sibling && sibling.type === "attribute_item") {
    attributes.unshift(parseAttributeText(sibling.text));
    sibling = sibling.previousNamedSibling;
  }
  return attributes;
}

function isTestGate(attribute: Attribute): boolean {
  return attribute.name === "cfg" && !/^\(\s*test\s*\)$/.test(attribute.args);
}

function fileCfg(root: SyntaxNode): string[] {
  return root.namedChildren
    .filter((child): child is SyntaxNode => child !== null && child.type === "inner_attribute_item")
    .map((child) => parseAttributeText(child.text))
    .filter(isTestGate)
    .map((attribute) => attribute.text.replace(/^#!\[/, "#["));
}

function moduleAncestors(node: SyntaxNode): SyntaxNode[] {
  const chain: SyntaxNode[] = [];
  let current = node.parent;
  while (current) {
    if (current.type === "mod_item") chain.unshift(current);
    current = current.parent;
  }
  return chain;
}

function nameOf(node: SyntaxNode): string | undefined {
  return node.childForFieldName("name")?.text;
}

export interface TargetLocation {
  kind: TargetKind;
  target?: string;
  modulePath: string[];
}

/** Map a repository-relative `.rs` path to its Cargo target and file-derived module path. */
export function locateTarget(file: string): TargetLocation {
  const segments = file.split("/");
  const at = (dir: string) => segments.lastIndexOf(dir);
  const mods = (parts: string[]): string[] => {
    const out = parts.map((p) => p.replace(/\.rs$/, ""));
    const last = out[out.length - 1];
    if (last === "mod" || last === "main" || last === "lib") out.pop();
    return out;
  };
  const tests = at("tests");
  if (tests >= 0 && tests < segments.length - 1) {
    const rest = segments.slice(tests + 1);
    const stem = rest[0]!.replace(/\.rs$/, "");
    return { kind: "integration", target: stem, modulePath: rest.length === 1 ? [] : mods(rest.slice(1)) };
  }
  const benches = at("benches");
  if (benches >= 0 && benches < segments.length - 1) {
    const rest = segments.slice(benches + 1);
    return { kind: "bench", target: rest[0]!.replace(/\.rs$/, ""), modulePath: rest.length === 1 ? [] : mods(rest.slice(1)) };
  }
  const examples = at("examples");
  if (examples >= 0 && examples < segments.length - 1) {
    const rest = segments.slice(examples + 1);
    return { kind: "example", target: rest[0]!.replace(/\.rs$/, ""), modulePath: rest.length === 1 ? [] : mods(rest.slice(1)) };
  }
  const src = at("src");
  if (src >= 0 && src < segments.length - 1) {
    const rest = segments.slice(src + 1);
    if (rest[0] === "bin" && rest.length >= 2) {
      const stem = rest[1]!.replace(/\.rs$/, "");
      return { kind: "bin", target: stem, modulePath: rest.length === 2 ? [] : mods(rest.slice(2)) };
    }
    if (rest.length === 1 && rest[0] === "main.rs") return { kind: "bin", modulePath: [] };
    return { kind: "lib", modulePath: mods(rest) };
  }
  return { kind: "unknown", modulePath: [] };
}

interface MacroTemplate {
  name: string;
  /** Index of the `$ident` parameter that names the generated function. */
  nameParam: number;
  cfg: string[];
  ignored: boolean;
  attributes: string[];
}

/** A `macro_rules!` whose body declares a test function named by one of its parameters. */
function testTemplate(definition: SyntaxNode): MacroTemplate | undefined {
  const name = nameOf(definition);
  if (!name) return undefined;
  const rule = definition.descendantsOfType("macro_rule")[0];
  if (!rule) return undefined;
  const matcher = rule.childForFieldName("left")?.text ?? "";
  const body = rule.childForFieldName("right")?.text ?? "";
  const params = [...matcher.matchAll(/\$([A-Za-z_]\w*)\s*:\s*(\w+)/g)].map((m) => ({ name: m[1]!, kind: m[2]! }));
  const fnParam = /\bfn\s+\$([A-Za-z_]\w*)/.exec(body)?.[1];
  if (!fnParam) return undefined;
  const attributes = [...body.matchAll(/#\[[^\]]*\]/g)].map((m) => parseAttributeText(m[0]));
  if (!attributes.some((a) => TEST_ATTRIBUTES.has(a.name))) return undefined;
  const nameParam = params.findIndex((p) => p.name === fnParam && p.kind === "ident");
  if (nameParam < 0) return undefined;
  return {
    name,
    nameParam,
    cfg: attributes.filter(isTestGate).map((a) => a.text),
    ignored: attributes.some((a) => a.name === "ignore"),
    attributes: attributes.map((a) => a.name),
  };
}

/** Top-level comma-separated arguments of an invocation's token tree, as text. */
function invocationArguments(tokenTree: SyntaxNode): string[] {
  const args: string[] = [];
  let current: string[] = [];
  for (const child of tokenTree.children) {
    if (!child) continue;
    if (child.type === "(" || child.type === ")" || child.type === "[" || child.type === "]" || child.type === "{" || child.type === "}") {
      if (child.startIndex === tokenTree.startIndex || child.endIndex === tokenTree.endIndex) continue;
    }
    if (child.type === ",") {
      args.push(current.join(" ").trim());
      current = [];
    } else {
      current.push(child.text);
    }
  }
  if (current.length > 0) args.push(current.join(" ").trim());
  return args;
}

/**
 * Literal `#[attr] fn name` sequences inside a macro body. Tokens arrive as
 * `#`, a `[...]` token tree, `fn`, and an identifier; attribute runs reset on
 * any other token so an attribute cannot bind across a statement.
 */
function literalTestItems(tokenTree: SyntaxNode): { node: SyntaxNode; name: string; attributes: Attribute[] }[] {
  const found: { node: SyntaxNode; name: string; attributes: Attribute[] }[] = [];
  const children = tokenTree.children.filter((c): c is SyntaxNode => c !== null);
  let run: Attribute[] = [];
  for (let i = 0; i < children.length; i += 1) {
    const token = children[i]!;
    const next = children[i + 1];
    if (token.type === "#" && next && next.type === "token_tree" && next.text.startsWith("[")) {
      run.push(parseAttributeText(`#${next.text}`));
      i += 1;
      continue;
    }
    if (token.type === "fn" && next && next.type === "identifier") {
      if (run.some((a) => TEST_ATTRIBUTES.has(a.name))) found.push({ node: next, name: next.text, attributes: run });
      run = [];
      i += 1;
      continue;
    }
    if (token.type === "token_tree" && token.text.startsWith("{")) found.push(...literalTestItems(token));
    run = [];
  }
  return found;
}

export interface FileScan {
  tests: SourceTest[];
  diagnostics: SourceDiagnostic[];
}

export async function scanRustSource(source: string, pkg: string, file: string): Promise<FileScan> {
  const tree = (await parser()).parse(source);
  if (!tree) return { tests: [], diagnostics: [{ kind: "parse-error", file, line: 0, detail: "parser returned no tree" }] };
  const root = tree.rootNode;
  const diagnostics: SourceDiagnostic[] = [];
  if (root.hasError) {
    for (const error of root.descendantsOfType(["ERROR", "MISSING"])) {
      if (!error) continue;
      diagnostics.push({ kind: "parse-error", file, line: error.startPosition.row + 1, detail: `unparsed syntax: ${error.text.slice(0, 60).replace(/\s+/g, " ")}` });
    }
  }
  const location = locateTarget(file);
  const gates = fileCfg(root);
  const tests: SourceTest[] = [];
  const modulePathOf = (node: SyntaxNode) => [...location.modulePath, ...moduleAncestors(node).map((m) => nameOf(m) ?? "?")];
  const moduleCfgOf = (node: SyntaxNode) => moduleAncestors(node).flatMap((m) => attributeRun(m).filter(isTestGate).map((a) => a.text));
  const record = (node: SyntaxNode, name: string, attributes: Attribute[], extra: Partial<SourceTest>): void => {
    const modulePath = modulePathOf(node);
    const ignore = attributes.find((a) => a.name === "ignore");
    const cfg = [...gates, ...moduleCfgOf(node), ...attributes.filter(isTestGate).map((a) => a.text)];
    const test: SourceTest = {
      pkg,
      file,
      line: node.startPosition.row + 1,
      name,
      modulePath,
      identity: [...modulePath, name].join("::"),
      kind: location.kind,
      attributes: attributes.map((a) => a.name),
      cfg: [...new Set(cfg)],
      ignored: ignore !== undefined,
      fromMacro: false,
      macroExpanded: attributes.some((a) => EXPANDING_ATTRIBUTES.has(a.name)),
      ...extra,
    };
    if (location.target !== undefined) test.target = location.target;
    const reason = /=\s*"([^"]*)"/.exec(ignore?.args ?? "")?.[1];
    if (reason !== undefined) test.ignoreReason = reason;
    tests.push(test);
  };

  for (const fn of root.descendantsOfType("function_item")) {
    if (!fn) continue;
    const attributes = attributeRun(fn);
    if (!attributes.some((a) => TEST_ATTRIBUTES.has(a.name))) continue;
    const name = nameOf(fn);
    if (!name) continue;
    record(fn, name, attributes, {});
  }

  const templates = new Map<string, MacroTemplate>();
  for (const definition of root.descendantsOfType("macro_definition")) {
    if (!definition) continue;
    const template = testTemplate(definition);
    if (template) templates.set(template.name, template);
  }
  for (const invocation of root.descendantsOfType("macro_invocation")) {
    if (!invocation) continue;
    const macro = invocation.childForFieldName("macro")?.text;
    const template = macro ? templates.get(macro) : undefined;
    const tokenTree = invocation.namedChildren.find((c): c is SyntaxNode => c !== null && c.type === "token_tree");
    if (!template) {
      if (!tokenTree || invocation.parent?.type === "macro_definition") continue;
      for (const item of literalTestItems(tokenTree)) {
        record(item.node, item.name, item.attributes, { fromMacro: true });
      }
      continue;
    }
    {
      const args = tokenTree ? invocationArguments(tokenTree) : [];
      const name = args[template.nameParam];
      if (!name || !/^[A-Za-z_]\w*$/.test(name)) {
        diagnostics.push({ kind: "macro-unresolved", file, line: invocation.startPosition.row + 1, detail: `${macro}! generates a test but argument ${template.nameParam} is not an identifier` });
        continue;
      }
      const attributes = template.attributes.map((n) => ({ name: n, args: "", text: `#[${n}]` }));
      record(invocation, name, attributes, { fromMacro: true, ignored: template.ignored, cfg: [...new Set([...gates, ...moduleCfgOf(invocation), ...template.cfg])] });
    }
  }
  tests.sort((a, b) => a.line - b.line);
  return { tests, diagnostics };
}

/** Convenience for callers that only want the records; diagnostics are dropped. */
export async function scanRustTests(source: string, pkg: string, file: string): Promise<SourceTest[]> {
  return (await scanRustSource(source, pkg, file)).tests;
}

function rustFilesUnder(dir: string, exclude: string[]): string[] {
  if (!existsSync(dir) || !statSync(dir).isDirectory()) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    const portable = `/${path.split(sep).join("/")}/`;
    if (exclude.some((fragment) => portable.includes(fragment))) continue;
    if (entry.isDirectory()) out.push(...rustFilesUnder(path, exclude));
    else if (entry.name.endsWith(".rs")) out.push(path);
  }
  return out.sort();
}

/**
 * Scan every `.rs` file under the given roots. A root that is a Cargo package
 * directory (holds `Cargo.toml`) contributes its `src`, `tests`, `benches`,
 * and `examples`; any other root is scanned as-is.
 */
export async function scanSourcePopulation(
  repoRoot: string,
  roots: { package: string; roots: string[] }[],
  exclude: string[],
): Promise<SourcePopulation> {
  const population: SourcePopulation = { tests: [], diagnostics: [], filesScanned: 0 };
  for (const { package: pkg, roots: packageRoots } of roots) {
    for (const root of packageRoots) {
      const dirs = existsSync(join(root, "Cargo.toml"))
        ? ["src", "tests", "benches", "examples"].map((d) => join(root, d))
        : [root];
      for (const dir of dirs) {
        for (const file of rustFilesUnder(dir, exclude)) {
          const rel = relative(repoRoot, file).split(sep).join("/");
          const scan = await scanRustSource(readFileSync(file, "utf8"), pkg, rel);
          population.tests.push(...scan.tests);
          population.diagnostics.push(...scan.diagnostics);
          population.filesScanned += 1;
        }
      }
    }
  }
  return population;
}
