import { readFileSync } from "node:fs";

import { parseArgv, requireString, optionalString, hasFlag } from "../args.ts";
import type { Command, CommandIo } from "../command.ts";
import { loadConfig } from "../config.ts";
import { EXIT } from "../errors.ts";
import { versionBanner } from "../version.ts";
import { scanSourcePopulation } from "./sources.ts";

const USAGE = `usage: test-audit sources --config <audit.config.json> [--json|--markdown]

Scan Rust source files for test attributes and report the source-side test
population. This is half of the reconciliation: the other half is the runner
universe from nextest captures.

Options:
  --config <path>   Audit configuration file (required)
  --json            Output as JSON (default)
  --markdown        Output as a markdown table
`;

export const sourcesCommand: Command = {
  name: "sources",
  summary: "scan Rust sources for test attributes (source-side population)",
  usage: USAGE,
  async run(argv: string[], io: CommandIo): Promise<number> {
    const parsed = parseArgv(argv, ["json", "markdown"]);
    const configPath = requireString(parsed, "config", USAGE);
    const config = loadConfig(configPath);

    const population = await scanSourcePopulation(config.repoRoot, config.sourceRoots, config.sourceScan.exclude);
    const tests = population.tests;

    const markdown = hasFlag(parsed, "markdown");
    if (markdown) {
      io.out(`# Source test population — ${config.area}`);
      io.out("");
      io.out(`<!-- ${versionBanner()} -->`);
      io.out("");
      const byPackage = new Map<string, number>();
      for (const t of tests) byPackage.set(t.pkg, (byPackage.get(t.pkg) ?? 0) + 1);
      io.out("| Package | Source attributes |");
      io.out("|---|---:|");
      let total = 0;
      for (const pkg of [...byPackage.keys()].sort()) {
        const count = byPackage.get(pkg) ?? 0;
        total += count;
        io.out(`| \`${pkg}\` | ${count} |`);
      }
      io.out(`| **total** | **${total}** |`);
      const expanded = tests.filter((t) => t.macroExpanded).length;
      const generated = tests.filter((t) => t.fromMacro).length;
      const ignored = tests.filter((t) => t.ignored).length;
      const gated = tests.filter((t) => t.cfg.length > 0).length;
      io.out("");
      io.out(`${population.filesScanned} files scanned; ${gated} cfg-gated, ${ignored} ignored, ${generated} generated by macro_rules templates, ${expanded} parameterized by attribute macros (runner listing is the authority for their executable names).`);
      if (population.diagnostics.length > 0) {
        io.out("");
        io.out("Diagnostics:");
        for (const d of population.diagnostics) io.out(`- [${d.kind}] ${d.file}:${d.line} — ${d.detail}`);
      }
    } else {
      io.out(JSON.stringify({ tool: versionBanner(), area: config.area, filesScanned: population.filesScanned, tests, diagnostics: population.diagnostics }, null, 2));
    }

    return EXIT.clean;
  },
};
