set dotenv-load
set positional-arguments

BOLD := '\033[1m'
ITALIC := '\033[3m'
RESET := '\033[0m'
YELLOW2 := '\033[38;5;3m'
BLACK := '\033[30m'
RED := '\033[31m'
GREEN := '\033[32m'
YELLOW := '\033[33m'
BLUE := '\033[34m'
MAGENTA := '\033[35m'
CYAN := '\033[36m'
WHITE := '\033[37m'

default:
    @echo
    @echo "so-you-say"
    @echo "------------------------------------"
    @echo ""
    @just --list | grep -v 'default'
    @echo

# build research modules (cli, lib)
build *args="":
    @echo ""
    @echo "Build so-you-say CLI"
    @echo "--------------------"
    @echo ""
    @cargo build -p so-you-say {{args}}

# run tests across research modules
test *args="":
    @echo ""
    @echo "Testing so-you-say CLI"
    @echo "----------------------"
    @echo ""
    @cargo test -p so-you-say {{args}}

lint *args="":
    @echo ""
    @echo "Linting so-you-say CLI"
    @echo "----------------------"
    @echo ""
    @cargo clippy {{args}}

# install the `speak` binary into the executable path
install:
    @echo ""
    @echo "{{BOLD}}Building Sniff Library{{RESET}}"
    @cargo build --release -p so-you-say
    @echo ""
    @echo "{{BOLD}}{{YELLOW}}Installing Sniff CLI{{RESET}}"
    @cargo install --path "." --locked

# run the debug release of the so-you-say CLI
cli *args="":
    @cargo run -p so-you-say -- {{args}}

# Use GPT 5.2 to commit staged changes
commit:
    @echo "Using Opencode with {{BOLD}}gpt-5.2-codex{{RESET}} to {{BOLD}}commit{{RESET}} staged changes"
    @echo
    @cd .. && opencode run "/commit -f ; remember you must use 'conventional commits' naming conventions and that unless all staged files are strongly related to the same thing be sure to make multiple commits by package or related activity." --model "openai/gpt-5.2-codex"
    @if command -v so-you-say >/dev/null 2>&1; then \
        so-you-say "git commits completed in rusty-biscuit monorepo"; \
    fi
