[package]
name = "darkmatter-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.darkmatter]
path = ".."

[[bin]]
name = "markdown_parser"
path = "fuzz_targets/markdown_parser.rs"
test = false
doc = false
