//! Language-specific builtin symbol lists.
//!
//! This module provides lists of "always defined" symbols for each supported
//! programming language. These are used by semantic lint rules to avoid false
//! positives for undefined-symbol checks on language builtins, standard library
//! symbols, and globally available identifiers.

use crate::shared::ProgrammingLanguage;

/// Checks if a symbol name is a builtin for the given language.
///
/// Builtins include:
/// - Language keywords that appear as identifiers (e.g., `None`, `True` in Python)
/// - Standard library symbols (e.g., `println!` in Rust, `console` in JS)
/// - Primitive types (e.g., `int`, `string`)
/// - Global values (e.g., `null`, `undefined`)
pub fn is_builtin(language: ProgrammingLanguage, name: &str) -> bool {
    match language {
        ProgrammingLanguage::Rust => RUST_BUILTINS.contains(&name),
        ProgrammingLanguage::JavaScript => JS_BUILTINS.contains(&name),
        ProgrammingLanguage::TypeScript => TS_BUILTINS.contains(&name),
        ProgrammingLanguage::Go => GO_BUILTINS.contains(&name),
        ProgrammingLanguage::Python => PYTHON_BUILTINS.contains(&name),
        ProgrammingLanguage::Java => JAVA_BUILTINS.contains(&name),
        ProgrammingLanguage::CSharp => CSHARP_BUILTINS.contains(&name),
        ProgrammingLanguage::C => C_BUILTINS.contains(&name),
        ProgrammingLanguage::Cpp => CPP_BUILTINS.contains(&name),
        ProgrammingLanguage::Swift => SWIFT_BUILTINS.contains(&name),
        ProgrammingLanguage::Scala => SCALA_BUILTINS.contains(&name),
        ProgrammingLanguage::Php => PHP_BUILTINS.contains(&name),
        ProgrammingLanguage::Perl => PERL_BUILTINS.contains(&name),
        ProgrammingLanguage::Bash => BASH_BUILTINS.contains(&name),
        ProgrammingLanguage::Zsh => ZSH_BUILTINS.contains(&name),
        ProgrammingLanguage::Lua => LUA_BUILTINS.contains(&name),
    }
}

/// Rust prelude, primitives, and common macros.
const RUST_BUILTINS: &[&str] = &[
    // Prelude types
    "Option",
    "Some",
    "None",
    "Result",
    "Ok",
    "Err",
    "Vec",
    "String",
    "Box",
    "Rc",
    "Arc",
    "Cell",
    "RefCell",
    "Mutex",
    "RwLock",
    "Cow",
    "Pin",
    // Prelude traits
    "Copy",
    "Clone",
    "Eq",
    "PartialEq",
    "Ord",
    "PartialOrd",
    "Hash",
    "Default",
    "Debug",
    "Display",
    "Iterator",
    "IntoIterator",
    "From",
    "Into",
    "TryFrom",
    "TryInto",
    "AsRef",
    "AsMut",
    "Deref",
    "DerefMut",
    "Drop",
    "Fn",
    "FnMut",
    "FnOnce",
    "Send",
    "Sync",
    "Sized",
    "Unpin",
    // Common macros
    "println",
    "print",
    "eprintln",
    "eprint",
    "format",
    "panic",
    "assert",
    "assert_eq",
    "assert_ne",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "unreachable",
    "unimplemented",
    "todo",
    "vec",
    "dbg",
    "cfg",
    "include",
    "include_str",
    "include_bytes",
    "env",
    "option_env",
    "concat",
    "stringify",
    "file",
    "line",
    "column",
    "module_path",
    "matches",
    "write",
    "writeln",
    // Primitive types
    "bool",
    "char",
    "str",
    "i8",
    "i16",
    "i32",
    "i64",
    "i128",
    "isize",
    "u8",
    "u16",
    "u32",
    "u64",
    "u128",
    "usize",
    "f32",
    "f64",
    // Common std modules
    "std",
    "core",
    "alloc",
    "Self",
    "self",
    "super",
    "crate",
];

/// JavaScript global objects, constructors, and values.
const JS_BUILTINS: &[&str] = &[
    // Global values
    "undefined",
    "null",
    "NaN",
    "Infinity",
    "globalThis",
    // Constructors/classes
    "Object",
    "Array",
    "String",
    "Number",
    "Boolean",
    "Symbol",
    "BigInt",
    "Function",
    "Date",
    "RegExp",
    "Error",
    "TypeError",
    "RangeError",
    "SyntaxError",
    "ReferenceError",
    "EvalError",
    "URIError",
    "AggregateError",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "WeakRef",
    "Promise",
    "Proxy",
    "Reflect",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "DataView",
    "Int8Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "Int16Array",
    "Uint16Array",
    "Int32Array",
    "Uint32Array",
    "Float32Array",
    "Float64Array",
    "BigInt64Array",
    "BigUint64Array",
    "JSON",
    "Math",
    "Intl",
    "Atomics",
    "FinalizationRegistry",
    // Global functions
    "eval",
    "isFinite",
    "isNaN",
    "parseFloat",
    "parseInt",
    "decodeURI",
    "decodeURIComponent",
    "encodeURI",
    "encodeURIComponent",
    "escape",
    "unescape",
    // Console and timers
    "console",
    "setTimeout",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "setImmediate",
    "clearImmediate",
    "queueMicrotask",
    // Browser globals (commonly available)
    "window",
    "document",
    "navigator",
    "location",
    "history",
    "localStorage",
    "sessionStorage",
    "fetch",
    "Request",
    "Response",
    "Headers",
    "URL",
    "URLSearchParams",
    "FormData",
    "Blob",
    "File",
    "FileReader",
    "AbortController",
    "AbortSignal",
    "Event",
    "EventTarget",
    "CustomEvent",
    "XMLHttpRequest",
    "WebSocket",
    "Worker",
    "MessageChannel",
    "MessagePort",
    "BroadcastChannel",
    "TextEncoder",
    "TextDecoder",
    "atob",
    "btoa",
    "crypto",
    "performance",
    // Node.js globals
    "process",
    "Buffer",
    "global",
    "__dirname",
    "__filename",
    "require",
    "module",
    "exports",
    // Special
    "arguments",
    "this",
];

/// TypeScript includes JavaScript builtins plus type-related globals.
const TS_BUILTINS: &[&str] = &[
    // All JavaScript builtins
    "undefined",
    "null",
    "NaN",
    "Infinity",
    "globalThis",
    "Object",
    "Array",
    "String",
    "Number",
    "Boolean",
    "Symbol",
    "BigInt",
    "Function",
    "Date",
    "RegExp",
    "Error",
    "TypeError",
    "RangeError",
    "SyntaxError",
    "ReferenceError",
    "EvalError",
    "URIError",
    "AggregateError",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "WeakRef",
    "Promise",
    "Proxy",
    "Reflect",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "DataView",
    "Int8Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "Int16Array",
    "Uint16Array",
    "Int32Array",
    "Uint32Array",
    "Float32Array",
    "Float64Array",
    "BigInt64Array",
    "BigUint64Array",
    "JSON",
    "Math",
    "Intl",
    "Atomics",
    "FinalizationRegistry",
    "eval",
    "isFinite",
    "isNaN",
    "parseFloat",
    "parseInt",
    "decodeURI",
    "decodeURIComponent",
    "encodeURI",
    "encodeURIComponent",
    "console",
    "setTimeout",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "queueMicrotask",
    "window",
    "document",
    "navigator",
    "location",
    "fetch",
    "Request",
    "Response",
    "Headers",
    "URL",
    "URLSearchParams",
    "FormData",
    "Blob",
    "File",
    "AbortController",
    "Event",
    "EventTarget",
    "TextEncoder",
    "TextDecoder",
    "crypto",
    "performance",
    "process",
    "Buffer",
    "global",
    "__dirname",
    "__filename",
    "require",
    "module",
    "exports",
    "arguments",
    "this",
    // TypeScript-specific type utilities
    "Partial",
    "Required",
    "Readonly",
    "Record",
    "Pick",
    "Omit",
    "Exclude",
    "Extract",
    "NonNullable",
    "Parameters",
    "ConstructorParameters",
    "ReturnType",
    "InstanceType",
    "ThisParameterType",
    "OmitThisParameter",
    "ThisType",
    "Uppercase",
    "Lowercase",
    "Capitalize",
    "Uncapitalize",
    "Awaited",
    "NoInfer",
    // TypeScript keywords as values
    "never",
    "unknown",
    "any",
    "void",
    "keyof",
    "typeof",
    "infer",
    "as",
    "is",
    "asserts",
];

/// Go builtin functions, types, and values.
const GO_BUILTINS: &[&str] = &[
    // Builtin functions
    "append",
    "cap",
    "clear",
    "close",
    "complex",
    "copy",
    "delete",
    "imag",
    "len",
    "make",
    "max",
    "min",
    "new",
    "panic",
    "print",
    "println",
    "real",
    "recover",
    // Builtin types
    "bool",
    "byte",
    "complex64",
    "complex128",
    "error",
    "float32",
    "float64",
    "int",
    "int8",
    "int16",
    "int32",
    "int64",
    "rune",
    "string",
    "uint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "uintptr",
    "any",
    "comparable",
    // Builtin values
    "nil",
    "true",
    "false",
    "iota",
];

/// Python builtin functions, types, constants, and exceptions.
const PYTHON_BUILTINS: &[&str] = &[
    // Builtin functions
    "abs",
    "aiter",
    "all",
    "anext",
    "any",
    "ascii",
    "bin",
    "bool",
    "breakpoint",
    "bytearray",
    "bytes",
    "callable",
    "chr",
    "classmethod",
    "compile",
    "complex",
    "delattr",
    "dict",
    "dir",
    "divmod",
    "enumerate",
    "eval",
    "exec",
    "filter",
    "float",
    "format",
    "frozenset",
    "getattr",
    "globals",
    "hasattr",
    "hash",
    "help",
    "hex",
    "id",
    "input",
    "int",
    "isinstance",
    "issubclass",
    "iter",
    "len",
    "list",
    "locals",
    "map",
    "max",
    "memoryview",
    "min",
    "next",
    "object",
    "oct",
    "open",
    "ord",
    "pow",
    "print",
    "property",
    "range",
    "repr",
    "reversed",
    "round",
    "set",
    "setattr",
    "slice",
    "sorted",
    "staticmethod",
    "str",
    "sum",
    "super",
    "tuple",
    "type",
    "vars",
    "zip",
    "__import__",
    // Builtin constants
    "True",
    "False",
    "None",
    "Ellipsis",
    "NotImplemented",
    "__debug__",
    "__name__",
    "__doc__",
    "__package__",
    "__loader__",
    "__spec__",
    "__annotations__",
    "__builtins__",
    "__file__",
    "__cached__",
    // Builtin exceptions
    "BaseException",
    "Exception",
    "ArithmeticError",
    "AssertionError",
    "AttributeError",
    "BlockingIOError",
    "BrokenPipeError",
    "BufferError",
    "BytesWarning",
    "ChildProcessError",
    "ConnectionAbortedError",
    "ConnectionError",
    "ConnectionRefusedError",
    "ConnectionResetError",
    "DeprecationWarning",
    "EOFError",
    "EnvironmentError",
    "FileExistsError",
    "FileNotFoundError",
    "FloatingPointError",
    "FutureWarning",
    "GeneratorExit",
    "IOError",
    "ImportError",
    "ImportWarning",
    "IndentationError",
    "IndexError",
    "InterruptedError",
    "IsADirectoryError",
    "KeyError",
    "KeyboardInterrupt",
    "LookupError",
    "MemoryError",
    "ModuleNotFoundError",
    "NameError",
    "NotADirectoryError",
    "NotImplementedError",
    "OSError",
    "OverflowError",
    "PendingDeprecationWarning",
    "PermissionError",
    "ProcessLookupError",
    "RecursionError",
    "ReferenceError",
    "ResourceWarning",
    "RuntimeError",
    "RuntimeWarning",
    "StopAsyncIteration",
    "StopIteration",
    "SyntaxError",
    "SyntaxWarning",
    "SystemError",
    "SystemExit",
    "TabError",
    "TimeoutError",
    "TypeError",
    "UnboundLocalError",
    "UnicodeDecodeError",
    "UnicodeEncodeError",
    "UnicodeError",
    "UnicodeTranslateError",
    "UnicodeWarning",
    "UserWarning",
    "ValueError",
    "Warning",
    "ZeroDivisionError",
    // Special
    "self",
    "cls",
];

/// Java common types and System class.
const JAVA_BUILTINS: &[&str] = &[
    // Primitive types
    "boolean",
    "byte",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "void",
    // Wrapper classes
    "Boolean",
    "Byte",
    "Character",
    "Short",
    "Integer",
    "Long",
    "Float",
    "Double",
    "Void",
    // Core classes
    "Object",
    "String",
    "Class",
    "System",
    "Runtime",
    "Thread",
    "Runnable",
    "Throwable",
    "Exception",
    "RuntimeException",
    "Error",
    "Math",
    "StringBuilder",
    "StringBuffer",
    // Collections
    "Iterable",
    "Iterator",
    "Collection",
    "List",
    "Set",
    "Map",
    "Queue",
    "Deque",
    "ArrayList",
    "LinkedList",
    "HashSet",
    "TreeSet",
    "HashMap",
    "TreeMap",
    "LinkedHashMap",
    "LinkedHashSet",
    "Arrays",
    "Collections",
    // Common exceptions
    "NullPointerException",
    "IndexOutOfBoundsException",
    "ArrayIndexOutOfBoundsException",
    "StringIndexOutOfBoundsException",
    "IllegalArgumentException",
    "IllegalStateException",
    "UnsupportedOperationException",
    "ClassCastException",
    "NumberFormatException",
    "IOException",
    "FileNotFoundException",
    // IO
    "InputStream",
    "OutputStream",
    "Reader",
    "Writer",
    "PrintStream",
    "PrintWriter",
    "BufferedReader",
    "BufferedWriter",
    "File",
    // Annotations
    "Override",
    "Deprecated",
    "SuppressWarnings",
    "FunctionalInterface",
    // Keywords as identifiers
    "this",
    "super",
    "null",
    "true",
    "false",
];

/// C# common types and System namespace.
const CSHARP_BUILTINS: &[&str] = &[
    // Primitive types
    "bool",
    "byte",
    "sbyte",
    "char",
    "decimal",
    "double",
    "float",
    "int",
    "uint",
    "long",
    "ulong",
    "short",
    "ushort",
    "object",
    "string",
    "void",
    "dynamic",
    "var",
    // System types
    "Boolean",
    "Byte",
    "SByte",
    "Char",
    "Decimal",
    "Double",
    "Single",
    "Int16",
    "Int32",
    "Int64",
    "UInt16",
    "UInt32",
    "UInt64",
    "Object",
    "String",
    "Void",
    // Core classes
    "Console",
    "Math",
    "Environment",
    "Type",
    "Attribute",
    "Exception",
    "Array",
    "Enum",
    "Delegate",
    "EventHandler",
    "Action",
    "Func",
    "Predicate",
    "Comparison",
    "Nullable",
    "Tuple",
    "ValueTuple",
    "Task",
    "ValueTask",
    // Collections
    "IEnumerable",
    "IEnumerator",
    "ICollection",
    "IList",
    "IDictionary",
    "List",
    "Dictionary",
    "HashSet",
    "Queue",
    "Stack",
    "LinkedList",
    // LINQ
    "Enumerable",
    "Queryable",
    // Common exceptions
    "ArgumentException",
    "ArgumentNullException",
    "ArgumentOutOfRangeException",
    "InvalidOperationException",
    "NotSupportedException",
    "NotImplementedException",
    "NullReferenceException",
    "IndexOutOfRangeException",
    "FormatException",
    "IOException",
    // Keywords as identifiers
    "this",
    "base",
    "null",
    "true",
    "false",
    "nameof",
    "typeof",
    "sizeof",
    "default",
];

/// C standard library functions and macros.
const C_BUILTINS: &[&str] = &[
    // Standard I/O
    "printf",
    "fprintf",
    "sprintf",
    "snprintf",
    "scanf",
    "fscanf",
    "sscanf",
    "puts",
    "fputs",
    "putchar",
    "getchar",
    "fopen",
    "fclose",
    "fread",
    "fwrite",
    "fgets",
    "fflush",
    "fseek",
    "ftell",
    "rewind",
    "feof",
    "ferror",
    "perror",
    // Memory
    "malloc",
    "calloc",
    "realloc",
    "free",
    "memset",
    "memcpy",
    "memmove",
    "memcmp",
    // String
    "strlen",
    "strcpy",
    "strncpy",
    "strcat",
    "strncat",
    "strcmp",
    "strncmp",
    "strchr",
    "strrchr",
    "strstr",
    "strtok",
    "strdup",
    // Conversions
    "atoi",
    "atol",
    "atof",
    "strtol",
    "strtoul",
    "strtod",
    // Character
    "isalpha",
    "isdigit",
    "isalnum",
    "isspace",
    "isupper",
    "islower",
    "toupper",
    "tolower",
    // Math
    "abs",
    "labs",
    "fabs",
    "sqrt",
    "pow",
    "sin",
    "cos",
    "tan",
    "log",
    "exp",
    "ceil",
    "floor",
    "round",
    // Utility
    "exit",
    "abort",
    "atexit",
    "system",
    "getenv",
    "rand",
    "srand",
    "qsort",
    "bsearch",
    // Types and macros
    "NULL",
    "EOF",
    "stdin",
    "stdout",
    "stderr",
    "size_t",
    "ptrdiff_t",
    "FILE",
    "sizeof",
    "offsetof",
    "assert",
    "errno",
    "true",
    "false",
];

/// C++ includes C builtins plus STL.
const CPP_BUILTINS: &[&str] = &[
    // C builtins
    "printf",
    "fprintf",
    "sprintf",
    "scanf",
    "puts",
    "malloc",
    "calloc",
    "realloc",
    "free",
    "memset",
    "memcpy",
    "strlen",
    "strcpy",
    "strcmp",
    "NULL",
    "EOF",
    "stdin",
    "stdout",
    "stderr",
    "size_t",
    "sizeof",
    "assert",
    "errno",
    "true",
    "false",
    // C++ specific
    "nullptr",
    "this",
    // std namespace
    "std",
    "cout",
    "cin",
    "cerr",
    "clog",
    "endl",
    "string",
    "vector",
    "array",
    "list",
    "deque",
    "forward_list",
    "set",
    "map",
    "unordered_set",
    "unordered_map",
    "multiset",
    "multimap",
    "stack",
    "queue",
    "priority_queue",
    "pair",
    "tuple",
    "optional",
    "variant",
    "any",
    "unique_ptr",
    "shared_ptr",
    "weak_ptr",
    "make_unique",
    "make_shared",
    "move",
    "forward",
    "swap",
    "begin",
    "end",
    "cbegin",
    "cend",
    "rbegin",
    "rend",
    "sort",
    "find",
    "find_if",
    "copy",
    "transform",
    "accumulate",
    "min",
    "max",
    "abs",
    "floor",
    "ceil",
    "round",
    "sqrt",
    "pow",
    "sin",
    "cos",
    // Exceptions
    "exception",
    "runtime_error",
    "logic_error",
    "invalid_argument",
    "out_of_range",
    "bad_alloc",
    // Type traits
    "is_same",
    "is_base_of",
    "enable_if",
    "conditional",
    "decay",
    "remove_reference",
    // Stream
    "ifstream",
    "ofstream",
    "fstream",
    "stringstream",
    "ostringstream",
    "istringstream",
];

/// Swift common types and functions.
const SWIFT_BUILTINS: &[&str] = &[
    // Print and debugging
    "print",
    "debugPrint",
    "dump",
    "fatalError",
    "precondition",
    "preconditionFailure",
    "assert",
    "assertionFailure",
    // Types
    "Bool",
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "UInt",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "Float",
    "Double",
    "String",
    "Character",
    "Array",
    "Dictionary",
    "Set",
    "Optional",
    "Result",
    "Void",
    "Never",
    "Any",
    "AnyObject",
    "AnyClass",
    // Collections
    "Sequence",
    "Collection",
    "RandomAccessCollection",
    "BidirectionalCollection",
    "MutableCollection",
    // Optionals
    "nil",
    "some",
    "none",
    // Functions
    "min",
    "max",
    "abs",
    "stride",
    "zip",
    "enumerate",
    "type",
    "unsafeBitCast",
    "withUnsafePointer",
    "withUnsafeMutablePointer",
    // Special
    "self",
    "Self",
    "super",
    "true",
    "false",
];

/// Scala common types and predef.
const SCALA_BUILTINS: &[&str] = &[
    // Primitives
    "Boolean",
    "Byte",
    "Short",
    "Int",
    "Long",
    "Float",
    "Double",
    "Char",
    "Unit",
    "Null",
    "Nothing",
    "Any",
    "AnyRef",
    "AnyVal",
    // Collections
    "List",
    "Vector",
    "Array",
    "Map",
    "Set",
    "Seq",
    "IndexedSeq",
    "Iterable",
    "Iterator",
    "Option",
    "Some",
    "None",
    "Either",
    "Left",
    "Right",
    "Try",
    "Success",
    "Failure",
    "Future",
    "Promise",
    "Tuple1",
    "Tuple2",
    "Tuple3",
    // Predef
    "println",
    "print",
    "printf",
    "readLine",
    "assert",
    "assume",
    "require",
    "identity",
    "implicitly",
    "locally",
    "classOf",
    "manifest",
    "optManifest",
    "typeOf",
    // Keywords as values
    "true",
    "false",
    "null",
    "this",
    "super",
    // Range
    "Range",
    "BigInt",
    "BigDecimal",
    "String",
    "StringContext",
];

/// PHP superglobals and common functions.
const PHP_BUILTINS: &[&str] = &[
    // Superglobals
    "_GET",
    "_POST",
    "_REQUEST",
    "_SESSION",
    "_COOKIE",
    "_SERVER",
    "_ENV",
    "_FILES",
    "GLOBALS",
    // Output
    "echo",
    "print",
    "print_r",
    "var_dump",
    "var_export",
    "printf",
    "sprintf",
    // String functions
    "strlen",
    "substr",
    "strpos",
    "str_replace",
    "strtolower",
    "strtoupper",
    "trim",
    "ltrim",
    "rtrim",
    "explode",
    "implode",
    "join",
    // Array functions
    "count",
    "array",
    "array_push",
    "array_pop",
    "array_shift",
    "array_unshift",
    "array_merge",
    "array_keys",
    "array_values",
    "array_map",
    "array_filter",
    "array_reduce",
    "in_array",
    "array_search",
    "sort",
    "rsort",
    "asort",
    "ksort",
    "usort",
    // Type functions
    "isset",
    "empty",
    "is_null",
    "is_array",
    "is_string",
    "is_int",
    "is_float",
    "is_bool",
    "is_object",
    "is_numeric",
    "gettype",
    "settype",
    "intval",
    "floatval",
    "strval",
    "boolval",
    // File functions
    "file_get_contents",
    "file_put_contents",
    "file_exists",
    "fopen",
    "fclose",
    "fread",
    "fwrite",
    "fgets",
    // Misc
    "die",
    "exit",
    "include",
    "include_once",
    "require",
    "require_once",
    "date",
    "time",
    "json_encode",
    "json_decode",
    "header",
    "session_start",
    // Constants
    "true",
    "false",
    "null",
    "PHP_EOL",
    "PHP_VERSION",
    "DIRECTORY_SEPARATOR",
    // Magic constants
    "__FILE__",
    "__DIR__",
    "__LINE__",
    "__CLASS__",
    "__METHOD__",
    "__FUNCTION__",
    "__NAMESPACE__",
    // Special
    "self",
    "parent",
    "static",
    "this",
];

/// Perl built-in functions and special variables.
const PERL_BUILTINS: &[&str] = &[
    // Output
    "print",
    "say",
    "printf",
    "sprintf",
    "warn",
    "die",
    // String
    "length",
    "substr",
    "index",
    "rindex",
    "lc",
    "uc",
    "lcfirst",
    "ucfirst",
    "chomp",
    "chop",
    "split",
    "join",
    "reverse",
    // Array
    "push",
    "pop",
    "shift",
    "unshift",
    "splice",
    "sort",
    "reverse",
    "grep",
    "map",
    "scalar",
    "wantarray",
    // Hash
    "keys",
    "values",
    "each",
    "exists",
    "delete",
    // File
    "open",
    "close",
    "read",
    "write",
    "seek",
    "tell",
    "eof",
    "stat",
    "lstat",
    "readdir",
    "opendir",
    "closedir",
    // Misc
    "defined",
    "undef",
    "ref",
    "bless",
    "tie",
    "untie",
    "local",
    "my",
    "our",
    "use",
    "require",
    "package",
    "sub",
    "return",
    "last",
    "next",
    "redo",
    "goto",
    "caller",
    "eval",
    "exec",
    "system",
    "exit",
    // Regex
    "qr",
    "quotemeta",
    // Special variables
    "_",
    "ARGV",
    "ENV",
    "INC",
    "SIG",
    "STDIN",
    "STDOUT",
    "STDERR",
];

/// Bash built-in commands and special variables.
const BASH_BUILTINS: &[&str] = &[
    // Builtins
    "echo",
    "printf",
    "read",
    "cd",
    "pwd",
    "pushd",
    "popd",
    "dirs",
    "export",
    "unset",
    "local",
    "declare",
    "typeset",
    "readonly",
    "let",
    "eval",
    "exec",
    "source",
    "alias",
    "unalias",
    "set",
    "shopt",
    "shift",
    "exit",
    "return",
    "break",
    "continue",
    "trap",
    "wait",
    "kill",
    "jobs",
    "fg",
    "bg",
    "suspend",
    "times",
    "ulimit",
    "umask",
    "getopts",
    "hash",
    "help",
    "history",
    "fc",
    "bind",
    "builtin",
    "caller",
    "command",
    "compgen",
    "complete",
    "compopt",
    "coproc",
    "disown",
    "enable",
    "logout",
    "mapfile",
    "readarray",
    "test",
    "true",
    "false",
    "type",
    // Common commands
    "ls",
    "cat",
    "grep",
    "sed",
    "awk",
    "find",
    "xargs",
    "sort",
    "uniq",
    "wc",
    "head",
    "tail",
    "cut",
    "tr",
    "tee",
    "mkdir",
    "rm",
    "cp",
    "mv",
    "touch",
    "chmod",
    "chown",
    "date",
    "basename",
    "dirname",
    // Special variables
    "HOME",
    "PATH",
    "PWD",
    "OLDPWD",
    "USER",
    "SHELL",
    "TERM",
    "LANG",
    "IFS",
    "PS1",
    "PS2",
    "RANDOM",
    "SECONDS",
    "LINENO",
    "FUNCNAME",
    "BASH_SOURCE",
    "BASH_LINENO",
    "PIPESTATUS",
];

/// Zsh includes Bash builtins plus zsh-specific features.
const ZSH_BUILTINS: &[&str] = &[
    // All bash builtins
    "echo",
    "printf",
    "read",
    "cd",
    "pwd",
    "pushd",
    "popd",
    "dirs",
    "export",
    "unset",
    "local",
    "declare",
    "typeset",
    "readonly",
    "let",
    "eval",
    "exec",
    "source",
    "alias",
    "unalias",
    "set",
    "shift",
    "exit",
    "return",
    "break",
    "continue",
    "trap",
    "wait",
    "kill",
    "jobs",
    "fg",
    "bg",
    "test",
    "true",
    "false",
    "type",
    // Zsh-specific
    "setopt",
    "unsetopt",
    "autoload",
    "zmodload",
    "zstyle",
    "compdef",
    "compadd",
    "compctl",
    "bindkey",
    "zle",
    "vared",
    "whence",
    "where",
    "which",
    "print",
    "zparseopts",
    "zformat",
    "zstat",
    "zcompile",
    "functions",
    "integer",
    "float",
    // Common commands
    "ls",
    "cat",
    "grep",
    "sed",
    "awk",
    "find",
    "sort",
    "uniq",
    // Special variables
    "HOME",
    "PATH",
    "PWD",
    "OLDPWD",
    "USER",
    "SHELL",
    "TERM",
    "ZSH_VERSION",
    "ZDOTDIR",
    "FPATH",
    "fpath",
    "path",
    "cdpath",
    "PROMPT",
    "RPROMPT",
];

/// Lua standard library functions and values.
const LUA_BUILTINS: &[&str] = &[
    // Global functions
    "assert",
    "collectgarbage",
    "dofile",
    "error",
    "getmetatable",
    "ipairs",
    "load",
    "loadfile",
    "next",
    "pairs",
    "pcall",
    "print",
    "rawequal",
    "rawget",
    "rawlen",
    "rawset",
    "require",
    "select",
    "setmetatable",
    "tonumber",
    "tostring",
    "type",
    "xpcall",
    "warn",
    // Values
    "_G",
    "_VERSION",
    "nil",
    "true",
    "false",
    // Standard libraries
    "coroutine",
    "debug",
    "io",
    "math",
    "os",
    "package",
    "string",
    "table",
    "utf8",
    // Common table functions
    "table.concat",
    "table.insert",
    "table.move",
    "table.pack",
    "table.remove",
    "table.sort",
    "table.unpack",
    // Common string functions
    "string.byte",
    "string.char",
    "string.find",
    "string.format",
    "string.gmatch",
    "string.gsub",
    "string.len",
    "string.lower",
    "string.match",
    "string.rep",
    "string.reverse",
    "string.sub",
    "string.upper",
    // Common math functions
    "math.abs",
    "math.ceil",
    "math.floor",
    "math.max",
    "math.min",
    "math.random",
    "math.randomseed",
    "math.sqrt",
    // Common io functions
    "io.open",
    "io.close",
    "io.read",
    "io.write",
    "io.input",
    "io.output",
    "io.flush",
    "io.lines",
    // Common os functions
    "os.clock",
    "os.date",
    "os.time",
    "os.exit",
    "os.getenv",
    "os.execute",
    "os.remove",
    "os.rename",
    // Special
    "self",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_builtins_detected() {
        assert!(is_builtin(ProgrammingLanguage::Rust, "Option"));
        assert!(is_builtin(ProgrammingLanguage::Rust, "println"));
        assert!(is_builtin(ProgrammingLanguage::Rust, "Vec"));
        assert!(!is_builtin(ProgrammingLanguage::Rust, "my_custom_type"));
    }

    #[test]
    fn js_builtins_detected() {
        assert!(is_builtin(ProgrammingLanguage::JavaScript, "console"));
        assert!(is_builtin(ProgrammingLanguage::JavaScript, "Array"));
        assert!(is_builtin(ProgrammingLanguage::JavaScript, "undefined"));
        assert!(!is_builtin(ProgrammingLanguage::JavaScript, "myFunction"));
    }

    #[test]
    fn python_builtins_detected() {
        assert!(is_builtin(ProgrammingLanguage::Python, "print"));
        assert!(is_builtin(ProgrammingLanguage::Python, "len"));
        assert!(is_builtin(ProgrammingLanguage::Python, "True"));
        assert!(is_builtin(ProgrammingLanguage::Python, "None"));
        assert!(!is_builtin(ProgrammingLanguage::Python, "my_variable"));
    }

    #[test]
    fn go_builtins_detected() {
        assert!(is_builtin(ProgrammingLanguage::Go, "make"));
        assert!(is_builtin(ProgrammingLanguage::Go, "len"));
        assert!(is_builtin(ProgrammingLanguage::Go, "nil"));
        assert!(!is_builtin(ProgrammingLanguage::Go, "myFunc"));
    }

    #[test]
    fn all_languages_have_builtins() {
        // Each language should have at least some builtins
        let languages = [
            ProgrammingLanguage::Rust,
            ProgrammingLanguage::JavaScript,
            ProgrammingLanguage::TypeScript,
            ProgrammingLanguage::Go,
            ProgrammingLanguage::Python,
            ProgrammingLanguage::Java,
            ProgrammingLanguage::CSharp,
            ProgrammingLanguage::C,
            ProgrammingLanguage::Cpp,
            ProgrammingLanguage::Swift,
            ProgrammingLanguage::Scala,
            ProgrammingLanguage::Php,
            ProgrammingLanguage::Perl,
            ProgrammingLanguage::Bash,
            ProgrammingLanguage::Zsh,
            ProgrammingLanguage::Lua,
        ];

        for lang in languages {
            // Check that at least one common builtin is detected
            let has_some_builtin = match lang {
                ProgrammingLanguage::Rust => is_builtin(lang, "Option"),
                ProgrammingLanguage::JavaScript => is_builtin(lang, "console"),
                ProgrammingLanguage::TypeScript => is_builtin(lang, "console"),
                ProgrammingLanguage::Go => is_builtin(lang, "make"),
                ProgrammingLanguage::Python => is_builtin(lang, "print"),
                ProgrammingLanguage::Java => is_builtin(lang, "System"),
                ProgrammingLanguage::CSharp => is_builtin(lang, "Console"),
                ProgrammingLanguage::C => is_builtin(lang, "printf"),
                ProgrammingLanguage::Cpp => is_builtin(lang, "std"),
                ProgrammingLanguage::Swift => is_builtin(lang, "print"),
                ProgrammingLanguage::Scala => is_builtin(lang, "println"),
                ProgrammingLanguage::Php => is_builtin(lang, "echo"),
                ProgrammingLanguage::Perl => is_builtin(lang, "print"),
                ProgrammingLanguage::Bash => is_builtin(lang, "echo"),
                ProgrammingLanguage::Zsh => is_builtin(lang, "echo"),
                ProgrammingLanguage::Lua => is_builtin(lang, "print"),
            };
            assert!(has_some_builtin, "Language {:?} should have builtins", lang);
        }
    }
}
