"""Render `attribution-2026-09-21.md` from the JSON reports in this directory.

Run from the repository root:
    python3 fixes/2026-09-21-ci-build-feature-divergence/attribution-data/render-attribution.py
"""

import json
import statistics
from pathlib import Path

A = Path(__file__).resolve().parent
OUT = A.parent / "attribution-2026-09-21.md"

lin = json.loads((A / "attribution-linux.json").read_text())
mac = json.loads((A / "attribution-macos-timed.json").read_text())

# Linux seconds are estimated: each configuration weighs the median macOS
# seconds of that crate's configurations.
per = {}
for c in mac["crates"]:
    secs = [x["seconds"] for x in c["configurations"] if x["seconds"]]
    per[c["crate"]] = statistics.median(secs) if secs else 0.0


def est(report):
    first = divergent = 0.0
    for c in report["crates"]:
        s = per.get(c["crate"], 0.0)
        first += s
        divergent += s * (len(c["configurations"]) - 1)
    return first, divergent


def flag(x):
    parts = ["+" + f for f in x["added"]] + ["-" + f for f in x["removed"]]
    side = " (host)" if x["host"] else ""
    return f"{x['crate']} {' '.join(parts) if parts else 'dependency set'}{side}"


L = []
w = L.append
w("""---
title: Feature attribution for the ten-package owner selection
created: 2026-09-23
spec: 2026-09-21-ci-build-feature-divergence
---

# Feature attribution — ten-package owner selection

The Phase 1 table the spec's part 1 asks for (Task 1.8). It lists every
`(workspace crate, configuration)` the environment owner builds for the
analyzed selection. Each configuration beyond a crate's first names the root
of its difference, and each is charged the compile seconds a local timed pass
measured for it. Generated by `attribution-data/render-attribution.py`.

## Selection, tree, and method

- **Selection:** `biscuit-file`, `claudine`, `claudine-cli`, `claudine-gen`,
  `darkmatter`, `darkmatter-cli`, `dmls`, `repo-deps`, `sniff`, `sniff-cli`,
  each with the `features` and `sidecars` of its
  `[package.metadata.ci.tests]`. They are modeled in the producer's order
  (sorted by package name), one archive invocation each, followed by that
  package's sidecar builds.
- **Tree:** `6c9ee2e60` (`fix/ci-build-feature-divergence`, equal to the
  merge of pull request 96), toolchain 1.98.1, 2026-09-23.
- **Configurations:** `feature-attribution` (`scripts/feature-attribution.rs`,
  package `repo-deps`, feature `local-tools`) resolves each invocation with
  `cargo tree --target <triple>` and interns each unit's identity: its own
  features, its host or target side, and its dependencies' identities.
  Nothing is compiled. The **CI-faithful table uses
  `--target x86_64-unknown-linux-gnu`**, which is what the `ubuntu-latest` owner
  passes.
- **Seconds:** one local timed pass (`timed-pass.sh` in this directory's
  parent) on the macOS host (`aarch64-apple-darwin`, 16 cores). A warm build
  first compiles every third-party artifact. Then every workspace crate's
  fingerprint, output, and incremental state is purged, as a fresh CI
  checkout with a restored dependency cache finds them. The measured pass then
  builds each owner's archive compile (`cargo test --no-run --profile test
  --target <host>`, which is what `cargo nextest archive` runs) and its
  sidecars, with `CARGO_INCREMENTAL=0`. Every rustc invocation is timed by the
  `ci-build` wrapper, the same event mechanism CI measures with. Only library
  and build-script units are charged. Test harnesses and binaries belong to
  the owner itself.
  - Fidelity caveat: the timings are macOS seconds per rustc process under
    Cargo's normal parallelism, not Linux runner seconds. The CI job summed
    1,674 s of owner build time; this host's measured pass took 389 s of wall
    time. **Linux seconds below are estimates**: each Linux configuration is
    weighted with the median macOS seconds of that crate's configurations.
  - The join is complete. Against the macOS model the timed pass compiled
    nothing the model did not predict (`unexplained_compiles` is empty).
- **Cause rule:** a configuration is compared with the *nearest* earlier
  configuration of the same crate, the one with the fewest root causes. A
  root cause is the deepest crate whose own features (or dependency set)
  differ. Seconds of a configuration with several causes are split evenly
  (**split**). **Sole** counts only configurations where the cause is the only
  one, which is what removing that cause alone is certain to save.
  **Involved** counts every configuration the cause takes part in.
- **Raw data:** `attribution-data/` holds `attribution-linux.json`,
  `attribution-macos-timed.json`, the measured pass's events
  (`timed-pass-events.json`), per-owner wall seconds for the warm and measured
  passes, and the `--align` what-if reports.

Reproduce:

```sh
cargo run -p repo-deps --bin feature-attribution -- \\
  --owners biscuit-file,claudine,claudine-cli,claudine-gen,darkmatter,darkmatter-cli,dmls,repo-deps,sniff,sniff-cli \\
  --target x86_64-unknown-linux-gnu --json attribution-linux.json
fixes/2026-09-21-ci-build-feature-divergence/timed-pass.sh target/feature-attribution-timing-out
cargo run -p repo-deps --bin feature-attribution -- --owners <same> \\
  --target aarch64-apple-darwin --events target/feature-attribution-timing-out/events \\
  [--align libc,proc-macro2,serde_core]
```
""")

lt, mt = lin["totals"], mac["totals"]
lf, ld = est(lin)
w("## Totals\n")
w("| Measure | Linux (CI-faithful) | macOS (timed) |\n|---|---|---|")
w(f"| Workspace crates built | {lt['workspace_crates']} | {mt['workspace_crates']} |")
w(f"| Configurations | {lt['configurations']} | {mt['configurations']} |")
w(f"| Configurations beyond a crate's first | {lt['divergent_configurations']} | {mt['divergent_configurations']} |")
for origin, label in (
    ("third-party", "… whose causes are all third-party"),
    ("workspace-own", "… whose causes are all workspace-own"),
    ("mixed", "… with both kinds of cause"),
):
    w(f"| {label} | {lt['divergent_by_origin'].get(origin, 0)} | {mt['divergent_by_origin'].get(origin, 0)} |")
w(f"| Seconds, first configurations | ≈{lf:.0f} s (estimate) | {mt['seconds_first']:.1f} s |")
w(f"| Seconds, divergent configurations | ≈{ld:.0f} s (estimate) | {mt['seconds_divergent']:.1f} s |")
w("")
w("The analyzed CI job compiled 28 distinct workspace crates 89 times at an "
  "earlier tree. The model at this tree predicts 27 crates in 92 "
  "configurations on Linux.\n")

cat = {}
for c in lin["crates"]:
    s = per.get(c["crate"], 0.0)
    for x in c["configurations"][1:]:
        for cause in x["causes"]:
            cat[cause["category"]] = cat.get(cause["category"], 0) + s / len(x["causes"])
ms = mt["seconds_by_category"]
tot_m, tot_l = sum(ms.values()), sum(cat.values())
tp_m, wo_m = ms.get("third-party", 0), ms.get("own", 0) + ms.get("workspace-dependency", 0)
tp_l, wo_l = cat.get("third-party", 0), cat.get("own", 0) + cat.get("workspace-dependency", 0)
w("## Split: third-party-inherited versus workspace-own divergence\n")
w("| Origin | macOS timed seconds | Share | Linux estimate | Share |\n|---|---|---|---|---|")
w(f"| Third-party-inherited | {tp_m:.1f} s | {100 * tp_m / tot_m:.0f}% | ≈{tp_l:.0f} s | {100 * tp_l / tot_l:.0f}% |")
w(f"| Workspace-own (own features {ms.get('own', 0):.1f} s + a workspace "
  f"dependency's {ms.get('workspace-dependency', 0):.1f} s on macOS) | {wo_m:.1f} s | "
  f"{100 * wo_m / tot_m:.0f}% | ≈{wo_l:.0f} s | {100 * wo_l / tot_l:.0f}% |")
w("")
w("Seconds are split evenly between a configuration's causes, so the rows "
  "sum to the divergent total.\n")

w("## Where the divergent seconds land (macOS timed)\n")
w("| Workspace crate | Configurations | First configuration | Divergent seconds | Share |\n|---|---|---|---|---|")
rows = []
for c in mac["crates"]:
    cf = c["configurations"]
    rows.append((sum(x["seconds"] or 0 for x in cf[1:]), c["crate"], len(cf), cf[0]["seconds"] or 0))
for s, n, k, f in sorted(rows, reverse=True):
    if s >= 0.05:
        w(f"| `{n}` | {k} | {f:.1f} s | {s:.1f} s | {100 * s / mt['seconds_divergent']:.1f}% |")
w("")

w("## Ranked causes (macOS timed, top 30 by involved seconds)\n")
w("| Cause | Category | Configs | Split | Sole | Involved | Crates |\n|---|---|---|---|---|---|---|")
for c in sorted(mac["causes"], key=lambda c: (-c["involved_seconds"], -c["seconds"]))[:30]:
    w(f"| `{flag(c)}` | {c['category']} | {c['configurations']} | {c['seconds']:.1f} s | "
      f"{c['sole_seconds']:.1f} s | {c['involved_seconds']:.1f} s | {len(c['crates'])} |")
w(f"\nThe full ranking ({len(mac['causes'])} causes on macOS, {len(lin['causes'])} on "
  "Linux) is in the JSON reports.\n")

w("## What alignment would remove (`--align` what-if)\n")
w("Each scenario models every owner resolving the named third-party crates "
  "identically, as a reviewed alignment entry enabling their union would. "
  "The tool refuses workspace crates. The \"default no\" set is ruling 4's: "
  "`time`, `hyper`, `hyper-util`, `tower`, `crossterm`, `mio`, "
  "`tokio-stream`, `clap`, `clap_builder`.\n")
w("| Scenario | Crates aligned | Linux configs (divergent) | Linux est. seconds removed "
  "| macOS configs (divergent) | macOS timed seconds removed |\n|---|---|---|---|---|---|")
scenarios = [
    ("None (as built)", "–", "attribution-linux", "attribution-macos-timed"),
    ("`libc` only", "`libc`", "whatif-linux-libc", None),
    ("Spec's eligible trio", "`libc`, `proc-macro2`, `serde_core`", "whatif-linux-trio", "whatif-macos-timed-trio"),
    ("Trio + `mio`", "trio, `mio`", "whatif-linux-trio-mio", None),
    ("Trio + `errno`, `mio`", "trio, `errno`, `mio`", None, "whatif-macos-timed-trio-errno-mio"),
    ("Every third-party crate outside the \"default no\" set", None,
     "whatif-linux-all-but-default-no", "whatif-macos-timed-all-but-default-no"),
    ("Every divergent third-party crate (hakari-like)", None,
     "whatif-linux-all-third-party", "whatif-macos-timed-all-third-party"),
]
for name, crates, lname, mname in scenarios:
    lc = ls = mc = msr = "–"
    counts = []
    if lname:
        r = json.loads((A / f"{lname}.json").read_text())
        _, dv = est(r)
        lc = f"{r['totals']['configurations']} ({r['totals']['divergent_configurations']})"
        ls = f"≈{ld - dv:.0f} s"
        if r["aligned"]:
            counts.append(f"{len(r['aligned'])} on Linux")
    if mname:
        r = json.loads((A / f"{mname}.json").read_text())
        mc = f"{r['totals']['configurations']} ({r['totals']['divergent_configurations']})"
        msr = f"{(r['totals']['seconds_removed'] or 0):.1f} s" if r["aligned"] else "0 s"
        if r["aligned"]:
            counts.append(f"{len(r['aligned'])} on macOS")
    w(f"| {name} | {crates or ', '.join(counts)} | {lc} | {ls} | {mc} | {msr} |")
w("")

w("## The spec's thirteen rows, accounted for\n")
w("Re-derived at this tree (S1): `claudine` and `claudine-cli` diverge on "
  "exactly the spec's thirteen rows when `claudine-cli` resolves with **no** "
  "features. With its CI features they diverge on 24. Of those, 21 appear "
  "below as third-party roots and `darkmatter +effects-instrumentation` as a "
  "workspace-dependency root. The other two re-identify no workspace crate. "
  "`cast +std` sits under `duckdb`, which only `rendezvous-daemon` links, and "
  "only `claudine-cli` builds that crate, so no crate is built both with and "
  "without it. `flate2 +zlib-rs` is on the host-side copy under "
  "`libduckdb-sys`'s build dependencies, and the S1 method merged it with the "
  "target-side copy. Taken one side at a time, every owner resolves it "
  "identically. "
  "`proc-macro2 +span-locations` reaches only the **target-side** "
  "`proc-macro2`. Under the owner's explicit `--target`, the host-side copy "
  "under every derive macro is `default,proc-macro` for every owner.\n")
w(f"Third-party `(crate, version, side)` rows the ten-package selection "
  f"resolves with more than one feature set: {len(lin['third_party_divergence'])} "
  "on Linux (`third_party_divergence` in `attribution-linux.json`).\n")

w("## Every configuration (Linux, CI-faithful)\n")
w("`vs` is the earlier configuration each one is compared with. Category "
  "abbreviations: `own` means the crate's own features, `ws dep` a workspace "
  "dependency's features, and `3p` a third-party dependency's features.\n")
w("| Crate | # | Side | First owner | Also used by | vs | Causes |\n|---|---|---|---|---|---|---|")
short = {"own": "own", "workspace-dependency": "ws dep", "third-party": "3p"}
for c in lin["crates"]:
    for i, x in enumerate(c["configurations"]):
        also = ", ".join(o for o in x["owners"] if o != x["first_owner"]) or "–"
        if i == 0:
            causes = "first configuration"
        else:
            causes = "; ".join(f"`{flag(k)}` ({short[k['category']]})" for k in x["causes"])
        vs = "–" if x["compared_with"] is None else x["compared_with"] + 1
        side = "host" if x["host"] else "target"
        w(f"| `{c['crate']}` | {i + 1} | {side} | {x['first_owner']} | {also} | {vs} | {causes} |")

OUT.write_text("\n".join(L) + "\n")
print(f"wrote {OUT}")
