// This code was automatically generated by schematic-gen. Do not edit manually.

use serde::{Deserialize, Serialize};
use crate::shared::{RequestParts, SchematicError};
use super::responses::*;
/// Request for `Generate` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{GenerateNativeRequest, GenerateBody};
///
/// let body = GenerateBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = GenerateNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GenerateNativeRequest {
    /// Request body
    pub body: GenerateBody,
}
impl GenerateNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: GenerateBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/generate".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<GenerateBody> for GenerateNativeRequest {
    fn from(body: GenerateBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for GenerateNativeRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "Generate";
}
/// Request for `Chat` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{ChatNativeRequest, ChatBody};
///
/// let body = ChatBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = ChatNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatNativeRequest {
    /// Request body
    pub body: ChatBody,
}
impl ChatNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: ChatBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/chat".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<ChatBody> for ChatNativeRequest {
    fn from(body: ChatBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for ChatNativeRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "Chat";
}
/// Request for `Embeddings` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{EmbeddingsNativeRequest, EmbeddingsBody};
///
/// let body = EmbeddingsBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = EmbeddingsNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingsNativeRequest {
    /// Request body
    pub body: EmbeddingsBody,
}
impl EmbeddingsNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: EmbeddingsBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/embeddings".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<EmbeddingsBody> for EmbeddingsNativeRequest {
    fn from(body: EmbeddingsBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for EmbeddingsNativeRequest {
    type Response = EmbeddingsResponse;
    const ENDPOINT_ID: &'static str = "Embeddings";
}
/// Request for `ListModels` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::ListModelsNativeRequest;
///
/// let request = ListModelsNativeRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelsNativeRequest {}
impl ListModelsNativeRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/tags".to_string();
        Ok(("GET", path, crate::shared::RequestBody::Empty, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListModelsNativeRequest {
    type Response = ListModelsResponse;
    const ENDPOINT_ID: &'static str = "ListModels";
}
/// Request for `ShowModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{ShowModelNativeRequest, ShowModelBody};
///
/// let body = ShowModelBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = ShowModelNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ShowModelNativeRequest {
    /// Request body
    pub body: ShowModelBody,
}
impl ShowModelNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: ShowModelBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/show".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<ShowModelBody> for ShowModelNativeRequest {
    fn from(body: ShowModelBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for ShowModelNativeRequest {
    type Response = ShowModelResponse;
    const ENDPOINT_ID: &'static str = "ShowModel";
}
/// Request for `PullModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{PullModelNativeRequest, PullModelBody};
///
/// let body = PullModelBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = PullModelNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PullModelNativeRequest {
    /// Request body
    pub body: PullModelBody,
}
impl PullModelNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: PullModelBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/pull".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<PullModelBody> for PullModelNativeRequest {
    fn from(body: PullModelBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for PullModelNativeRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "PullModel";
}
/// Request for `PushModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{PushModelNativeRequest, PushModelBody};
///
/// let body = PushModelBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = PushModelNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PushModelNativeRequest {
    /// Request body
    pub body: PushModelBody,
}
impl PushModelNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: PushModelBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/push".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<PushModelBody> for PushModelNativeRequest {
    fn from(body: PushModelBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for PushModelNativeRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "PushModel";
}
/// Request for `CopyModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{CopyModelNativeRequest, CopyModelBody};
///
/// let body = CopyModelBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = CopyModelNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CopyModelNativeRequest {
    /// Request body
    pub body: CopyModelBody,
}
impl CopyModelNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: CopyModelBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/copy".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<CopyModelBody> for CopyModelNativeRequest {
    fn from(body: CopyModelBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for CopyModelNativeRequest {
    type Response = ();
    const ENDPOINT_ID: &'static str = "CopyModel";
}
/// Request for `DeleteModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{DeleteModelNativeRequest, DeleteModelBody};
///
/// let body = DeleteModelBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = DeleteModelNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DeleteModelNativeRequest {
    /// Request body
    pub body: DeleteModelBody,
}
impl DeleteModelNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: DeleteModelBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/delete".to_string();
        Ok((
            "DELETE",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<DeleteModelBody> for DeleteModelNativeRequest {
    fn from(body: DeleteModelBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for DeleteModelNativeRequest {
    type Response = ();
    const ENDPOINT_ID: &'static str = "DeleteModel";
}
/// Request for `CreateModel` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{CreateModelNativeRequest, CreateModelBody};
///
/// let body = CreateModelBody {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = CreateModelNativeRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateModelNativeRequest {
    /// Request body
    pub body: CreateModelBody,
}
impl CreateModelNativeRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: CreateModelBody) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/create".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<CreateModelBody> for CreateModelNativeRequest {
    fn from(body: CreateModelBody) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for CreateModelNativeRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "CreateModel";
}
/// Request for `ListRunningModels` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::ListRunningModelsNativeRequest;
///
/// let request = ListRunningModelsNativeRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListRunningModelsNativeRequest {}
impl ListRunningModelsNativeRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/api/ps".to_string();
        Ok(("GET", path, crate::shared::RequestBody::Empty, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListRunningModelsNativeRequest {
    type Response = ListRunningModelsResponse;
    const ENDPOINT_ID: &'static str = "ListRunningModels";
}
/// Request for `ChatCompletions` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{ChatCompletionsOaiRequest, OpenAIChatCompletionRequest};
///
/// let body = OpenAIChatCompletionRequest {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = ChatCompletionsOaiRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatCompletionsOaiRequest {
    /// Request body
    pub body: OpenAIChatCompletionRequest,
}
impl ChatCompletionsOaiRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: OpenAIChatCompletionRequest) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/v1/chat/completions".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<OpenAIChatCompletionRequest> for ChatCompletionsOaiRequest {
    fn from(body: OpenAIChatCompletionRequest) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for ChatCompletionsOaiRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "ChatCompletions";
}
/// Request for `Completions` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{CompletionsOaiRequest, OpenAICompletionRequest};
///
/// let body = OpenAICompletionRequest {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = CompletionsOaiRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CompletionsOaiRequest {
    /// Request body
    pub body: OpenAICompletionRequest,
}
impl CompletionsOaiRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: OpenAICompletionRequest) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/v1/completions".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<OpenAICompletionRequest> for CompletionsOaiRequest {
    fn from(body: OpenAICompletionRequest) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for CompletionsOaiRequest {
    type Response = bytes::Bytes;
    const ENDPOINT_ID: &'static str = "Completions";
}
/// Request for `Embeddings` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::{EmbeddingsOaiRequest, OpenAIEmbeddingRequest};
///
/// let body = OpenAIEmbeddingRequest {
///     // ... set required fields ...
///     ..Default::default()
/// };
/// let request = EmbeddingsOaiRequest::new(body)
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingsOaiRequest {
    /// Request body
    pub body: OpenAIEmbeddingRequest,
}
impl EmbeddingsOaiRequest {
    /// Creates a new request with the required path parameters and body.
    pub fn new(body: OpenAIEmbeddingRequest) -> Self {
        Self { body }
    }
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/v1/embeddings".to_string();
        Ok((
            "POST",
            path,
            crate::shared::RequestBody::Json(
                serde_json::to_string(&self.body)
                    .map_err(|e| { SchematicError::SerializationError(e.to_string()) })?,
            ),
            vec![],
        ))
    }
}
impl From<OpenAIEmbeddingRequest> for EmbeddingsOaiRequest {
    fn from(body: OpenAIEmbeddingRequest) -> Self {
        Self { body }
    }
}
impl crate::shared::EndpointSpec for EmbeddingsOaiRequest {
    type Response = OpenAIEmbeddingResponse;
    const ENDPOINT_ID: &'static str = "Embeddings";
}
/// Request for `ListModels` endpoint.
///
/// ## Example
///
/// ```text
/// use schematic_schema::ollama::ListModelsOaiRequest;
///
/// let request = ListModelsOaiRequest::default()
///;
/// ```
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListModelsOaiRequest {}
impl ListModelsOaiRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// ## Returns
    ///
    /// A tuple of:
    /// - HTTP method as a static string (e.g., "GET", "POST")
    /// - Fully substituted path string with query parameters
    /// - The request body as a `RequestBody`
    /// - Endpoint-specific headers as key-value pairs
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if a JSON request body
    /// fails to serialize.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        let path = "/v1/models".to_string();
        Ok(("GET", path, crate::shared::RequestBody::Empty, vec![]))
    }
}
impl crate::shared::EndpointSpec for ListModelsOaiRequest {
    type Response = OpenAIListModelsResponse;
    const ENDPOINT_ID: &'static str = "ListModels";
}
/// Request enum for OllamaNative API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum OllamaNativeRequest {
    /// Generate text completion from a prompt (streaming NDJSON by default)
    Generate(GenerateNativeRequest),
    /// Generate chat completion from messages (streaming NDJSON by default)
    Chat(ChatNativeRequest),
    /// Generate embeddings for text
    Embeddings(EmbeddingsNativeRequest),
    /// List locally available models
    ListModels(ListModelsNativeRequest),
    /// Show detailed information about a model
    ShowModel(ShowModelNativeRequest),
    /// Pull a model from the Ollama registry (streaming progress by default)
    PullModel(PullModelNativeRequest),
    /// Push a model to the Ollama registry (streaming progress by default)
    PushModel(PushModelNativeRequest),
    /// Copy a model to a new name
    CopyModel(CopyModelNativeRequest),
    /// Delete a model
    DeleteModel(DeleteModelNativeRequest),
    /// Create a model from a Modelfile (streaming progress by default)
    CreateModel(CreateModelNativeRequest),
    /// List models currently loaded in memory
    ListRunningModels(ListRunningModelsNativeRequest),
}
impl OllamaNativeRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::Generate(req) => req.into_parts(),
            Self::Chat(req) => req.into_parts(),
            Self::Embeddings(req) => req.into_parts(),
            Self::ListModels(req) => req.into_parts(),
            Self::ShowModel(req) => req.into_parts(),
            Self::PullModel(req) => req.into_parts(),
            Self::PushModel(req) => req.into_parts(),
            Self::CopyModel(req) => req.into_parts(),
            Self::DeleteModel(req) => req.into_parts(),
            Self::CreateModel(req) => req.into_parts(),
            Self::ListRunningModels(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::Generate(_) => {
                <GenerateNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::Chat(_) => {
                <ChatNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::Embeddings(_) => {
                <EmbeddingsNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListModels(_) => {
                <ListModelsNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ShowModel(_) => {
                <ShowModelNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::PullModel(_) => {
                <PullModelNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::PushModel(_) => {
                <PushModelNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::CopyModel(_) => {
                <CopyModelNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::DeleteModel(_) => {
                <DeleteModelNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::CreateModel(_) => {
                <CreateModelNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListRunningModels(_) => {
                <ListRunningModelsNativeRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
    /// Returns how this endpoint's response body is decoded.
    ///
    /// The generic `request::<T>()` decodes JSON; it consults this to
    /// reject text, binary, and empty endpoints up front.
    #[must_use]
    pub fn response_kind(&self) -> crate::shared::ResponseKind {
        match self {
            Self::Generate(_) => crate::shared::ResponseKind::Binary,
            Self::Chat(_) => crate::shared::ResponseKind::Binary,
            Self::Embeddings(_) => crate::shared::ResponseKind::Json,
            Self::ListModels(_) => crate::shared::ResponseKind::Json,
            Self::ShowModel(_) => crate::shared::ResponseKind::Json,
            Self::PullModel(_) => crate::shared::ResponseKind::Binary,
            Self::PushModel(_) => crate::shared::ResponseKind::Binary,
            Self::CopyModel(_) => crate::shared::ResponseKind::Empty,
            Self::DeleteModel(_) => crate::shared::ResponseKind::Empty,
            Self::CreateModel(_) => crate::shared::ResponseKind::Binary,
            Self::ListRunningModels(_) => crate::shared::ResponseKind::Json,
        }
    }
}
impl From<GenerateNativeRequest> for OllamaNativeRequest {
    fn from(req: GenerateNativeRequest) -> Self {
        Self::Generate(req)
    }
}
impl From<ChatNativeRequest> for OllamaNativeRequest {
    fn from(req: ChatNativeRequest) -> Self {
        Self::Chat(req)
    }
}
impl From<EmbeddingsNativeRequest> for OllamaNativeRequest {
    fn from(req: EmbeddingsNativeRequest) -> Self {
        Self::Embeddings(req)
    }
}
impl From<ListModelsNativeRequest> for OllamaNativeRequest {
    fn from(req: ListModelsNativeRequest) -> Self {
        Self::ListModels(req)
    }
}
impl From<ShowModelNativeRequest> for OllamaNativeRequest {
    fn from(req: ShowModelNativeRequest) -> Self {
        Self::ShowModel(req)
    }
}
impl From<PullModelNativeRequest> for OllamaNativeRequest {
    fn from(req: PullModelNativeRequest) -> Self {
        Self::PullModel(req)
    }
}
impl From<PushModelNativeRequest> for OllamaNativeRequest {
    fn from(req: PushModelNativeRequest) -> Self {
        Self::PushModel(req)
    }
}
impl From<CopyModelNativeRequest> for OllamaNativeRequest {
    fn from(req: CopyModelNativeRequest) -> Self {
        Self::CopyModel(req)
    }
}
impl From<DeleteModelNativeRequest> for OllamaNativeRequest {
    fn from(req: DeleteModelNativeRequest) -> Self {
        Self::DeleteModel(req)
    }
}
impl From<CreateModelNativeRequest> for OllamaNativeRequest {
    fn from(req: CreateModelNativeRequest) -> Self {
        Self::CreateModel(req)
    }
}
impl From<ListRunningModelsNativeRequest> for OllamaNativeRequest {
    fn from(req: ListRunningModelsNativeRequest) -> Self {
        Self::ListRunningModels(req)
    }
}
/// Request enum for OllamaOpenAI API.
///
/// Each variant wraps a strongly-typed request struct.
pub enum OllamaOpenAIRequest {
    /// Create chat completion (SSE streaming when stream=true)
    ChatCompletions(ChatCompletionsOaiRequest),
    /// Create text completion (SSE streaming when stream=true)
    Completions(CompletionsOaiRequest),
    /// Generate embeddings for text
    Embeddings(EmbeddingsOaiRequest),
    /// List available models in OpenAI format
    ListModels(ListModelsOaiRequest),
}
impl OllamaOpenAIRequest {
    /// Converts the request into (method, path, body, headers) parts.
    ///
    /// Delegates to the inner request struct's `into_parts()` method.
    ///
    /// ## Errors
    ///
    /// Returns `SchematicError::SerializationError` if the request body
    /// fails to serialize to JSON.
    pub fn into_parts(self) -> Result<RequestParts, SchematicError> {
        match self {
            Self::ChatCompletions(req) => req.into_parts(),
            Self::Completions(req) => req.into_parts(),
            Self::Embeddings(req) => req.into_parts(),
            Self::ListModels(req) => req.into_parts(),
        }
    }
    /// Returns the endpoint identifier for this request.
    ///
    /// This is used internally for response hook lookup.
    #[must_use]
    pub fn endpoint_id(&self) -> &'static str {
        match self {
            Self::ChatCompletions(_) => {
                <ChatCompletionsOaiRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::Completions(_) => {
                <CompletionsOaiRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::Embeddings(_) => {
                <EmbeddingsOaiRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
            Self::ListModels(_) => {
                <ListModelsOaiRequest as crate::shared::EndpointSpec>::ENDPOINT_ID
            }
        }
    }
    /// Returns how this endpoint's response body is decoded.
    ///
    /// The generic `request::<T>()` decodes JSON; it consults this to
    /// reject text, binary, and empty endpoints up front.
    #[must_use]
    pub fn response_kind(&self) -> crate::shared::ResponseKind {
        match self {
            Self::ChatCompletions(_) => crate::shared::ResponseKind::Binary,
            Self::Completions(_) => crate::shared::ResponseKind::Binary,
            Self::Embeddings(_) => crate::shared::ResponseKind::Json,
            Self::ListModels(_) => crate::shared::ResponseKind::Json,
        }
    }
}
impl From<ChatCompletionsOaiRequest> for OllamaOpenAIRequest {
    fn from(req: ChatCompletionsOaiRequest) -> Self {
        Self::ChatCompletions(req)
    }
}
impl From<CompletionsOaiRequest> for OllamaOpenAIRequest {
    fn from(req: CompletionsOaiRequest) -> Self {
        Self::Completions(req)
    }
}
impl From<EmbeddingsOaiRequest> for OllamaOpenAIRequest {
    fn from(req: EmbeddingsOaiRequest) -> Self {
        Self::Embeddings(req)
    }
}
impl From<ListModelsOaiRequest> for OllamaOpenAIRequest {
    fn from(req: ListModelsOaiRequest) -> Self {
        Self::ListModels(req)
    }
}
