//! Source provenance tracking for render nodes.
//!
//! Every [`RenderNode`] carries a [`SourceSpan`] describing where the node
//! came from. Concrete source origins are stored once in a
//! [`SourceRegistry`] and referenced by a small copyable [`SourceId`].
//!
//! [`RenderNode`]: crate::tree::RenderNode

use std::ops::Range;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// A lightweight handle identifying a registered source.
///
/// Values are produced by [`SourceRegistry::register`] and resolved back to
/// a [`SourceDescriptor`] via [`SourceRegistry::resolve`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceId(pub u32);

/// A concrete origin from which content was drawn.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceDescriptor {
    /// A file on disk; the path is typically workspace-relative.
    File {
        /// The path to the source file.
        path: PathBuf,
    },
    /// A named in-memory source that has no file backing.
    Virtual {
        /// A human-readable name for the source.
        name: String,
    },
    /// A named component that produced content programmatically.
    Component {
        /// The name of the component.
        name: String,
    },
}

/// The single store of source origins for a document.
///
/// Descriptors are stored in a `Vec` and indexed by [`SourceId`]. The
/// [`Default`] value is an empty registry.
///
/// ## Examples
///
/// ```
/// use renderable::tree::{SourceDescriptor, SourceRegistry};
///
/// let mut registry = SourceRegistry::default();
/// let id = registry.register(SourceDescriptor::Virtual { name: "doc".into() });
/// assert!(registry.resolve(id).is_some());
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceRegistry {
    descriptors: Vec<SourceDescriptor>,
}

impl SourceRegistry {
    /// Creates an empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers a descriptor and returns its [`SourceId`].
    pub fn register(&mut self, descriptor: SourceDescriptor) -> SourceId {
        let id = SourceId(
            u32::try_from(self.descriptors.len())
                .expect("source registry exceeded u32::MAX entries"),
        );
        self.descriptors.push(descriptor);
        id
    }

    /// Resolves a [`SourceId`] back to its descriptor.
    ///
    /// ## Returns
    ///
    /// `None` if the identifier was not produced by this registry.
    #[must_use]
    pub fn resolve(&self, id: SourceId) -> Option<&SourceDescriptor> {
        self.descriptors.get(id.0 as usize)
    }

    /// Returns the number of registered descriptors.
    #[must_use]
    pub fn len(&self) -> usize {
        self.descriptors.len()
    }

    /// Returns `true` if no descriptors are registered.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.descriptors.is_empty()
    }
}

/// Describes how a node came to exist.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Provenance {
    /// The node was parsed directly from source text.
    Parsed,
    /// The node was created by a builder and has no source backing.
    Synthetic,
    /// The node was generated by a transformation step.
    Generated,
    /// The node was transcluded from another source.
    Transcluded {
        /// The source the content was transcluded from.
        origin: SourceId,
    },
}

/// A byte range within a registered source.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceLocation {
    /// The source the range refers to.
    pub source: SourceId,
    /// The byte range within the source.
    pub bytes: Range<usize>,
}

/// Provenance metadata attached to every [`RenderNode`].
///
/// [`location`] is `None` for synthetic or generated nodes that have no
/// concrete byte range in any source.
///
/// [`RenderNode`]: crate::tree::RenderNode
/// [`location`]: SourceSpan::location
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceSpan {
    /// How the node came to exist.
    pub provenance: Provenance,
    /// The byte range in a source, if one applies.
    pub location: Option<SourceLocation>,
}

impl SourceSpan {
    /// Creates a span for a synthetic node with no source location.
    #[must_use]
    pub fn synthetic() -> Self {
        Self {
            provenance: Provenance::Synthetic,
            location: None,
        }
    }
}
