[package]
name = "biscuit-visualized"
version = "0.1.0"
edition = "2021"

[lib]
name = "biscuit_visualized"
path = "src/lib.rs"

[features]
clap = ["dep:clap"]

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
biscuit-hash = { path = "../../biscuit-hash/lib" }
thiserror = "2.0"
tempfile = "3"
resvg = "0.45"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
mermaid-rs-renderer = "0.2"
layout-rs = "0.1"

[dev-dependencies]
serial_test = "3.0"
