build:
    cargo build -p darkmatter-cli

test:
    cargo test -p darkmatter-cli -p darkmatter-lib

lint:
    cargo clippy -p darkmatter-cli -p darkmatter-lib

install:
    cargo install --path . --bin md

cli *ARGS:
    cargo run -p darkmatter-cli -- {{ARGS}}
