use schematic_define::{ApiRequest, ApiResponse, Endpoint, FormField, RestMethod};

pub fn all() -> Vec<Endpoint> {
    vec![
        Endpoint {
            id: "ListVoices".to_string(),
            method: RestMethod::Get,
            path: "/v2/voices".to_string(),
            description: "Lists all available voices".to_string(),
            request: None,
            response: ApiResponse::json_type("ListVoicesResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetVoice".to_string(),
            method: RestMethod::Get,
            path: "/v1/voices/{voice_id}".to_string(),
            description: "Retrieves a voice by ID".to_string(),
            request: None,
            response: ApiResponse::json_type("VoiceResponseModel"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "DeleteVoice".to_string(),
            method: RestMethod::Delete,
            path: "/v1/voices/{voice_id}".to_string(),
            description: "Deletes a voice".to_string(),
            request: None,
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetDefaultVoiceSettings".to_string(),
            method: RestMethod::Get,
            path: "/v1/voices/settings/default".to_string(),
            description: "Gets default voice settings".to_string(),
            request: None,
            response: ApiResponse::json_type("VoiceSettings"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetVoiceSettings".to_string(),
            method: RestMethod::Get,
            path: "/v1/voices/{voice_id}/settings".to_string(),
            description: "Gets voice settings for a specific voice".to_string(),
            request: None,
            response: ApiResponse::json_type("VoiceSettings"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "UpdateVoiceSettings".to_string(),
            method: RestMethod::Post,
            path: "/v1/voices/{voice_id}/settings/edit".to_string(),
            description: "Updates voice settings".to_string(),
            request: Some(ApiRequest::json_type("VoiceSettings")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetVoiceSampleAudio".to_string(),
            method: RestMethod::Get,
            path: "/v1/voices/{voice_id}/samples/{sample_id}/audio".to_string(),
            description: "Gets audio for a voice sample".to_string(),
            request: None,
            response: ApiResponse::Binary,
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "DeleteVoiceSample".to_string(),
            method: RestMethod::Delete,
            path: "/v1/voices/{voice_id}/samples/{sample_id}".to_string(),
            description: "Deletes a voice sample".to_string(),
            request: None,
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "AddVoiceSample".to_string(),
            method: RestMethod::Post,
            path: "/v1/voices/{voice_id}/samples".to_string(),
            description: "Upload audio sample for voice cloning".to_string(),
            request: Some(ApiRequest::form_data(vec![
                FormField::file_accept("audio", vec!["audio/*".into()])
                    .with_description("Audio file (mp3, wav, ogg, m4a)"),
                FormField::text("name")
                    .optional()
                    .with_description("Name for the sample"),
            ])),
            response: ApiResponse::json_type("AddSampleResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "ListSharedVoices".to_string(),
            method: RestMethod::Get,
            path: "/v1/shared-voices".to_string(),
            description: "Lists voices from the public library".to_string(),
            request: None,
            response: ApiResponse::json_type("ListSharedVoicesResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "AddSharedVoice".to_string(),
            method: RestMethod::Post,
            path: "/v1/voices/add/{public_user_id}/{voice_id}".to_string(),
            description: "Adds a shared voice to your library".to_string(),
            request: Some(ApiRequest::json_type("AddSharedVoiceBody")),
            response: ApiResponse::json_type("AddSharedVoiceResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "CreatePvcVoice".to_string(),
            method: RestMethod::Post,
            path: "/v1/voices/pvc".to_string(),
            description: "Creates a professional voice clone".to_string(),
            request: Some(ApiRequest::json_type("CreatePvcVoiceBody")),
            response: ApiResponse::json_type("AddSharedVoiceResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "UpdatePvcVoice".to_string(),
            method: RestMethod::Post,
            path: "/v1/voices/pvc/{voice_id}".to_string(),
            description: "Updates a PVC voice".to_string(),
            request: Some(ApiRequest::json_type("CreatePvcVoiceBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "TrainPvcVoice".to_string(),
            method: RestMethod::Post,
            path: "/v1/voices/pvc/{voice_id}/train".to_string(),
            description: "Starts training a PVC voice".to_string(),
            request: Some(ApiRequest::json_type("TrainPvcVoiceBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
    ]
}
