use schematic_define::{ApiRequest, ApiResponse, Endpoint, RestMethod};

pub fn all() -> Vec<Endpoint> {
    vec![
        Endpoint {
            id: "GetUsageStats".to_string(),
            method: RestMethod::Get,
            path: "/v1/usage/character-stats".to_string(),
            description: "Gets usage statistics".to_string(),
            request: None,
            response: ApiResponse::json_type("UsageStatsResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetUser".to_string(),
            method: RestMethod::Get,
            path: "/v1/user".to_string(),
            description: "Gets current user information".to_string(),
            request: None,
            response: ApiResponse::json_type("UserResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetUserSubscription".to_string(),
            method: RestMethod::Get,
            path: "/v1/user/subscription".to_string(),
            description: "Gets user subscription information".to_string(),
            request: None,
            response: ApiResponse::json_type("SubscriptionModel"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "GetResource".to_string(),
            method: RestMethod::Get,
            path: "/v1/workspace/resources/{resource_id}".to_string(),
            description: "Gets resource information".to_string(),
            request: None,
            response: ApiResponse::json_type("ResourceResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "ShareResource".to_string(),
            method: RestMethod::Post,
            path: "/v1/workspace/resources/{resource_id}/share".to_string(),
            description: "Shares a resource".to_string(),
            request: Some(ApiRequest::json_type("ShareResourceBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "UnshareResource".to_string(),
            method: RestMethod::Post,
            path: "/v1/workspace/resources/{resource_id}/unshare".to_string(),
            description: "Removes sharing for a resource".to_string(),
            request: Some(ApiRequest::json_type("UnshareResourceBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "CopyResourceToWorkspace".to_string(),
            method: RestMethod::Post,
            path: "/v1/workspace/resources/{resource_id}/copy-to-workspace".to_string(),
            description: "Copies a resource to another workspace".to_string(),
            request: Some(ApiRequest::json_type("CopyResourceBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "ListServiceAccounts".to_string(),
            method: RestMethod::Get,
            path: "/v1/service-accounts".to_string(),
            description: "Lists service accounts".to_string(),
            request: None,
            response: ApiResponse::json_type("ListServiceAccountsResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "ListServiceAccountApiKeys".to_string(),
            method: RestMethod::Get,
            path: "/v1/service-accounts/{service_account_user_id}/api-keys".to_string(),
            description: "Lists API keys for a service account".to_string(),
            request: None,
            response: ApiResponse::json_type("ListApiKeysResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "CreateApiKey".to_string(),
            method: RestMethod::Post,
            path: "/v1/service-accounts/{service_account_user_id}/api-keys".to_string(),
            description: "Creates an API key for a service account".to_string(),
            request: Some(ApiRequest::json_type("CreateApiKeyBody")),
            response: ApiResponse::json_type("CreateApiKeyResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "UpdateApiKey".to_string(),
            method: RestMethod::Patch,
            path: "/v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}".to_string(),
            description: "Updates an API key".to_string(),
            request: Some(ApiRequest::json_type("UpdateApiKeyBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "DeleteApiKey".to_string(),
            method: RestMethod::Delete,
            path: "/v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}".to_string(),
            description: "Deletes an API key".to_string(),
            request: None,
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "ListWebhooks".to_string(),
            method: RestMethod::Get,
            path: "/v1/workspace/webhooks".to_string(),
            description: "Lists webhooks".to_string(),
            request: None,
            response: ApiResponse::json_type("ListWebhooksResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "CreateWebhook".to_string(),
            method: RestMethod::Post,
            path: "/v1/workspace/webhooks".to_string(),
            description: "Creates a webhook".to_string(),
            request: Some(ApiRequest::json_type("CreateWebhookBody")),
            response: ApiResponse::json_type("CreateWebhookResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "UpdateWebhook".to_string(),
            method: RestMethod::Patch,
            path: "/v1/workspace/webhooks/{webhook_id}".to_string(),
            description: "Updates a webhook".to_string(),
            request: Some(ApiRequest::json_type("UpdateWebhookBody")),
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
        Endpoint {
            id: "DeleteWebhook".to_string(),
            method: RestMethod::Delete,
            path: "/v1/workspace/webhooks/{webhook_id}".to_string(),
            description: "Deletes a webhook".to_string(),
            request: None,
            response: ApiResponse::json_type("StatusResponse"),
            headers: vec![],
            params: None,
            oauth_scopes: None,
        },
    ]
}
