// GENERATED by claudine-gen — DO NOT EDIT BY HAND.
//
// Inputs (field-source matrix, design/catalog-generation.md):
//   docs/providers.yaml — roster identity
//   docs/providers/facts/opencode.yaml — topic-less facts
//   docs/providers/overrides/opencode.yaml — human overrides (win over any source)
//   docs/research/<topic>/opencode.md — sidecar-validated research frontmatter
// Regenerate with `cargo run -p claudine-gen -- generate`; drift-check with
// `cargo run -p claudine-gen -- check` (the same code path as the drift test).

//! Typed static catalog data for the OpenCode provider (generated).

use std::path::PathBuf;
use std::sync::LazyLock;

use sniff::programs::AiCli;

use crate::events::AgenticEvent;
use crate::linking::capabilities::{ProviderCapabilities, ResourceFormat, ResourcePropertySchema, ResourceSupport, SkillFrontmatter, SupportLevel};
use crate::provider::{OutputFormatSelector, ProviderInfo};
use crate::provider::acp::{AcpServerMode, AcpSupport};
use crate::provider::cli_sensitivity::CliSensitiveAxes;
use crate::provider::event_mapping::{EventMapping, EventMappingTable, EventSupportLevel};
use crate::provider::identity::Provider;
use crate::provider::known_gap::{KnownGap, KnownGapArea};
use crate::provider::model_catalog_source::ModelCatalogSource;
use crate::provider::output_format::{EntrypointMode, EntrypointSpec, OutputFormat, OutputFormatSupport};
use crate::provider::path_template::PathTemplate;
use crate::provider::prompt_args::PromptArgConventions;
use crate::provider::reasoning::ReasoningSupport;
use crate::provider::system_prompt::{SystemPromptDelivery, SystemPromptDeliveryByMode, SystemPromptSpec};
use crate::provider::yolo::YoloSupport;
use crate::stream::StreamProtocol;

use super::behavior::OPENCODE_PROVIDER;
use super::legacy::agent_capabilities;

static OPENCODE_RESOURCE_SUPPORT: LazyLock<ProviderCapabilities> =
    LazyLock::new(build_resource_support);

fn resource_support() -> &'static ProviderCapabilities {
    &OPENCODE_RESOURCE_SUPPORT
}

pub(in crate::provider) static OPENCODE_INFO: ProviderInfo = ProviderInfo {
    provider: Provider::OpenCode,
    display_name: "OpenCode",
    slug: "opencode",
    short_name: "opencode",
    binary: "opencode",
    agent_offset: ".opencode",
    cli_aliases: &["opencode", "open_code", "open-code"],
    docs_url: "https://opencode.ai/docs",
    usage_dashboard_url: None,
    sniff_binding: AiCli::Opencode,
    supports_skills: true,
    stream_protocol: Some(StreamProtocol::Ndjson),
    event_mapping: &OPENCODE_EVENT_MAPPING,
    behavior: &OPENCODE_PROVIDER,
    mcp: &OPENCODE_PROVIDER,
    adapter: &OPENCODE_PROVIDER,
    configurator: &OPENCODE_PROVIDER,
    agent_capabilities_fn: agent_capabilities,
    resource_support_fn: resource_support,
    session_log_paths: &[],
    session_locations: &[],
    config_paths: &[
        PathTemplate::Static("~/.config/opencode/opencode.json"),
        PathTemplate::Static("~/.config/opencode/opencode.jsonc"),
        PathTemplate::Static("~/.config/opencode/tui.json"),
        PathTemplate::Static("opencode.json"),
        PathTemplate::Static("opencode.jsonc"),
        PathTemplate::Static("tui.json"),
        PathTemplate::Static(".opencode/"),
        PathTemplate::Static("~/.config/opencode/"),
        PathTemplate::Static("~/.local/share/opencode/auth.json"),
        PathTemplate::Static("~/.local/share/opencode/opencode.db"),
    ],
    memory_files: OPENCODE_MEMORY_FILES,
    output_formats: &[
        OutputFormatSupport {
            format: OutputFormat::Json,
            native_name: "json",
            cli_flag: Some("--format"),
            stdin_supported: false,
            selector: OutputFormatSelector::FlagValue {
                flag: "--format",
            },
        },
    ],
    entrypoints: &[
        EntrypointSpec {
            subcommand: Some("run"),
            required_flags: &[],
            mode: EntrypointMode::NonInteractive,
        },
    ],
    system_prompt: &SystemPromptSpec {
        append: SystemPromptDeliveryByMode {
            interactive: SystemPromptDelivery::Unsupported,
            non_interactive: SystemPromptDelivery::Unsupported,
        },
        replace: SystemPromptDeliveryByMode {
            interactive: SystemPromptDelivery::Unsupported,
            non_interactive: SystemPromptDelivery::Unsupported,
        },
        memory_files: OPENCODE_MEMORY_FILES,
    },
    yolo: YoloSupport::NonInteractiveOnly {
        non_interactive_flag: "--dangerously-skip-permissions",
    },
    reasoning: ReasoningSupport::NotDocumented,
    known_gaps: &[
        KnownGap {
            area: KnownGapArea::Other,
            note: "Populate claudine/docs/agent-cli/opencode.md",
            tracker: Some("claudine/docs/agent-cli/opencode.md"),
        },
    ],
    acp: AcpSupport {
        server_mode: AcpServerMode::NotSupported,
        client_supported: false,
        events_via_acp: &[],
    },
    prompt_arg_conventions: PromptArgConventions {
        prompt_flags: &[],
        entrypoint: Some("run"),
    },
    static_models: &[
        "opencode/big-pickle",
        "opencode/claude-fable-5",
        "opencode/claude-haiku-4-5",
        "opencode/claude-opus-4-1",
        "opencode/claude-opus-4-5",
        "opencode/claude-opus-4-6",
        "opencode/claude-opus-4-7",
        "opencode/claude-opus-4-8",
        "opencode/claude-sonnet-4",
        "opencode/claude-sonnet-4-5",
        "opencode/claude-sonnet-4-6",
        "opencode/claude-sonnet-5",
        "opencode/deepseek-v4-flash",
        "opencode/deepseek-v4-flash-free",
        "opencode/deepseek-v4-pro",
        "opencode/gemini-3-flash",
        "opencode/gemini-3.1-pro",
        "opencode/gemini-3.5-flash",
        "opencode/glm-5",
        "opencode/glm-5.1",
        "opencode/glm-5.2",
        "opencode/gpt-5",
        "opencode/gpt-5-codex",
        "opencode/gpt-5-nano",
        "opencode/gpt-5.1",
        "opencode/gpt-5.1-codex",
        "opencode/gpt-5.1-codex-max",
        "opencode/gpt-5.1-codex-mini",
        "opencode/gpt-5.2",
        "opencode/gpt-5.2-codex",
        "opencode/gpt-5.3-codex",
        "opencode/gpt-5.3-codex-spark",
        "opencode/gpt-5.4",
        "opencode/gpt-5.4-mini",
        "opencode/gpt-5.4-nano",
        "opencode/gpt-5.4-pro",
        "opencode/gpt-5.5",
        "opencode/gpt-5.5-pro",
        "opencode/grok-build-0.1",
        "opencode/kimi-k2.5",
        "opencode/kimi-k2.6",
        "opencode/kimi-k2.7-code",
        "opencode/mimo-v2.5-free",
        "opencode/minimax-m2.5",
        "opencode/minimax-m2.7",
        "opencode/minimax-m3",
        "opencode/nemotron-3-ultra-free",
        "opencode/north-mini-code-free",
        "opencode/qwen3.5-plus",
        "opencode/qwen3.6-plus",
    ],
    model_catalog_source: ModelCatalogSource::ShellCommand {
        program: "opencode",
        args: &["models"],
    },
    model_env_vars: &["OPENCODE_MODEL"],
    cli_sensitive_axes: CliSensitiveAxes {
        read_path: false,
        write_path: false,
        traverse_path: false,
        execute_command: false,
        access_domain: false,
        use_mcp_server: false,
        use_mcp_tool: false,
        spawn_subagent: false,
        switch_mode: false,
        modify_provider_config: true,
    },
    repo_home_root_files: &[],
};

/// Event-mapping table (also referenced directly by behavior modules).
pub(in crate::provider) static OPENCODE_EVENT_MAPPING: EventMappingTable = EventMappingTable {
    mappings: &[
        EventMapping {
            event: AgenticEvent::SessionStart,
            support_level: EventSupportLevel::Hook {
                native_name: "session.created",
            },
            parse_aliases: &["session.created"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::SessionEnd,
            support_level: EventSupportLevel::Hook {
                native_name: "session.deleted",
            },
            parse_aliases: &["session.deleted"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::BeforePrompt,
            support_level: EventSupportLevel::Hook {
                native_name: "chat.message",
            },
            parse_aliases: &["chat.message"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::BeforeTool,
            support_level: EventSupportLevel::Hook {
                native_name: "tool.execute.before",
            },
            parse_aliases: &["tool.execute.before"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::AfterTool,
            support_level: EventSupportLevel::Hook {
                native_name: "tool.execute.after",
            },
            parse_aliases: &["tool.execute.after"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::ToolError,
            support_level: EventSupportLevel::NotSupported,
            parse_aliases: &[],
            registration_target: false,
        },
        EventMapping {
            event: AgenticEvent::PermissionRequest,
            support_level: EventSupportLevel::Hook {
                native_name: "permission.ask",
            },
            parse_aliases: &["permission.ask"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::HumanInTheLoop,
            support_level: EventSupportLevel::Hook {
                native_name: "permission.asked",
            },
            parse_aliases: &["permission.asked"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::TurnComplete,
            support_level: EventSupportLevel::Hook {
                native_name: "session.idle",
            },
            parse_aliases: &["session.idle"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::TurnError,
            support_level: EventSupportLevel::Hook {
                native_name: "session.error",
            },
            parse_aliases: &["session.error"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::SubagentStart,
            support_level: EventSupportLevel::NotSupported,
            parse_aliases: &[],
            registration_target: false,
        },
        EventMapping {
            event: AgenticEvent::SubagentStop,
            support_level: EventSupportLevel::NotSupported,
            parse_aliases: &[],
            registration_target: false,
        },
        EventMapping {
            event: AgenticEvent::BeforeModel,
            support_level: EventSupportLevel::Hook {
                native_name: "chat.params",
            },
            parse_aliases: &[
                "chat.params",
                "chat.headers",
                "experimental.chat.system.transform",
                "experimental.chat.messages.transform",
            ],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::AfterModel,
            support_level: EventSupportLevel::Hook {
                native_name: "message.updated",
            },
            parse_aliases: &["message.updated", "message.part.updated", "experimental.text.complete"],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::BeforeCompact,
            support_level: EventSupportLevel::Hook {
                native_name: "session.compacted",
            },
            parse_aliases: &[
                "session.compacted",
                "session.compacting",
                "experimental.session.compacting",
            ],
            registration_target: true,
        },
        EventMapping {
            event: AgenticEvent::Notification,
            support_level: EventSupportLevel::Hook {
                native_name: "tui.toast.show",
            },
            parse_aliases: &["tui.toast.show", "event"],
            registration_target: true,
        },
    ],
};

/// Memory / instruction files contributing to the system prompt
/// hierarchy — one list, shared by `memory_files` and
/// `system_prompt.memory_files`.
const OPENCODE_MEMORY_FILES: &[PathTemplate] = &[PathTemplate::Static("AGENTS.md")];

/// Builds the resource portability descriptor served through
/// `resource_support_fn` (heap-backed, so it lives behind the `LazyLock`
/// rather than in the `ProviderInfo` static).
fn build_resource_support() -> ProviderCapabilities {
    ProviderCapabilities {
        provider: Provider::OpenCode,
        skills: ResourceSupport {
            level: SupportLevel::Full,
            format: Some(ResourceFormat::Markdown),
            repo_path: Some(PathBuf::from(".opencode/skills")),
            user_path: Some(PathBuf::from(".config/opencode/skills")),
            also_reads_from: vec![PathBuf::from(".claude/skills"), PathBuf::from(".agents/skills")],
            notes: None,
            properties: Some(ResourcePropertySchema::new(
                &["name", "description"],
                &["license", "compatibility", "metadata"],
                "claudine/docs/cross-referencing/opencode.md",
            )),
        },
        commands: ResourceSupport {
            level: SupportLevel::Full,
            format: Some(ResourceFormat::Markdown),
            repo_path: Some(PathBuf::from(".opencode/commands")),
            user_path: Some(PathBuf::from(".config/opencode/commands")),
            also_reads_from: vec![],
            notes: None,
            properties: Some(ResourcePropertySchema::new(
                &[],
                &["description", "template", "agent", "model", "subtask"],
                "claudine/docs/cross-referencing/opencode.md",
            )),
        },
        agents: ResourceSupport {
            level: SupportLevel::Full,
            format: Some(ResourceFormat::Markdown),
            repo_path: Some(PathBuf::from(".opencode/agents")),
            user_path: Some(PathBuf::from(".config/opencode/agents")),
            also_reads_from: vec![],
            notes: None,
            properties: Some(ResourcePropertySchema::new(
                &["description"],
                &[
                    "mode",
                    "model",
                    "temperature",
                    "top_p",
                    "tools",
                    "permission",
                    "steps",
                    "color",
                    "hidden",
                    "disable",
                    "prompt",
                ],
                "claudine/docs/cross-referencing/opencode.md",
            )),
        },
        scripts: ResourceSupport {
            level: SupportLevel::Full,
            format: Some(ResourceFormat::Executable),
            repo_path: Some(PathBuf::from(".opencode/scripts")),
            user_path: Some(PathBuf::from(".config/opencode/scripts")),
            also_reads_from: vec![],
            notes: None,
            properties: None,
        },
        skill_frontmatter: SkillFrontmatter {
            name: true,
            description: true,
            license: true,
            compatibility: true,
            metadata: true,
            allowed_tools: false,
            user_invocable: false,
            disable_model_invocation: false,
        },
    }
}
