//! Snapshot publication: a committed manifest plus a local journal.
//!
//! The accepted research snapshot (platform documents, catalog, summary) lives
//! at fixed, committed paths. `messenger/docs/research/publication.json` is the
//! single selection point: replacing it selects the new snapshot. A journal
//! with staged copies and backups under `messenger/.research-state/publication/`
//! drives rollback before that replacement and roll-forward after it, so an
//! interrupted publication always recovers to exactly the old or the new
//! snapshot. Generation and reporting read only through [`read_verified`],
//! which refuses any artifact whose bytes differ from the manifest (a hand edit,
//! a partial checkout, or a publication in flight).
//!
//! Design and per-OS evidence: the publication spike findings under
//! `messenger/features/2026-09-17-research-metadata-pipeline/spikes/publication/`.

pub(crate) mod fsutil;

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

pub use fsutil::RetryPolicy;
use fsutil::{LockError, PublicationLock, read_optional, remove_if_present, replace_file, sync_dir, write_durable};

use super::canonical::{canonical_json, xxh64_digest};
use super::load::SUPPORTED_SCHEMA_VERSION;
use super::paths::{MANIFEST, RepoPath, Workspace, is_portable};

/// The manifest format tag.
pub const FORMAT: &str = "messenger-research-publication/1";
const JOURNAL_FORMAT: &str = "messenger-research-publication-journal/1";

/// Opens a machine-derived region inside an authored file.
pub const REGION_BEGIN: &str = "<!-- BEGIN GENERATED by `messenger research generate`; do not edit -->";
/// Closes a machine-derived region.
pub const REGION_END: &str = "<!-- END GENERATED -->";

/// What a manifest hash covers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactScope {
    /// Every byte of the file.
    File,
    /// Only the generated regions ([`REGION_BEGIN`]…[`REGION_END`]); the
    /// authored prose around them may change without invalidating the snapshot.
    GeneratedRegions,
}

/// One artifact of a snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifact {
    pub bytes: Vec<u8>,
    pub scope: ArtifactScope,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SchemaEntry {
    pub version: u64,
    /// `_schema.yaml` + `_types.yaml` fingerprint.
    pub xxh64: String,
}

/// A generation input and its fingerprint. Markdown inputs also carry
/// Darkmatter's frontmatter and body hashes.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InputEntry {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frontmatter: Option<String>,
    pub path: String,
    pub xxh64: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactEntry {
    pub len: u64,
    pub path: String,
    pub scope: ArtifactScope,
    pub xxh64: String,
}

/// The committed manifest. Fields are declared in key order; the file has
/// LF line endings, a trailing newline, and no timestamps or host paths.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Manifest {
    pub artifacts: Vec<ArtifactEntry>,
    pub format: String,
    pub inputs: Vec<InputEntry>,
    pub schema: SchemaEntry,
    /// xxh64 of the canonical JSON of every other field.
    pub snapshot_id: String,
}

impl Manifest {
    /// Deterministic bytes of the manifest.
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut bytes = serde_json::to_vec_pretty(self).expect("a manifest always serializes");
        bytes.push(b'\n');
        bytes
    }

    /// Parses and checks the format tag.
    ///
    /// ## Errors
    ///
    /// [`PublishError::Corrupt`] for unparseable bytes or another format.
    pub fn parse(bytes: &[u8]) -> Result<Self, PublishError> {
        let manifest: Manifest =
            serde_json::from_slice(bytes).map_err(|error| PublishError::Corrupt(format!("{MANIFEST}: {error}")))?;
        if manifest.format != FORMAT {
            return Err(PublishError::Corrupt(format!("{MANIFEST}: unknown format {}", manifest.format)));
        }
        if let Some(entry) = manifest.artifacts.iter().find(|entry| !is_portable(&entry.path)) {
            return Err(PublishError::Corrupt(format!("{MANIFEST}: {} is not a repository-relative path", entry.path)));
        }
        Ok(manifest)
    }

    pub fn artifact(&self, path: &str) -> Option<&ArtifactEntry> {
        self.artifacts.iter().find(|entry| entry.path == path)
    }
}

/// A complete snapshot to publish, keyed by repository-relative path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Snapshot {
    pub schema: SchemaEntry,
    pub inputs: Vec<InputEntry>,
    pub artifacts: BTreeMap<String, Artifact>,
}

impl Snapshot {
    /// The manifest selecting this snapshot. Identical snapshots produce
    /// identical manifests.
    ///
    /// ## Panics
    ///
    /// When a [`ArtifactScope::GeneratedRegions`] artifact has malformed
    /// markers; the generator never produces one.
    pub fn manifest(&self) -> Manifest {
        let artifacts = self
            .artifacts
            .iter()
            .map(|(path, artifact)| {
                let covered = covered_bytes(&artifact.bytes, artifact.scope)
                    .unwrap_or_else(|| panic!("{path}: malformed generated-region markers"));
                ArtifactEntry {
                    len: covered.len() as u64,
                    path: path.clone(),
                    scope: artifact.scope,
                    xxh64: xxh64_digest(&covered),
                }
            })
            .collect();
        let mut inputs = self.inputs.clone();
        inputs.sort();
        let mut manifest = Manifest {
            artifacts,
            format: FORMAT.to_string(),
            inputs,
            schema: self.schema.clone(),
            snapshot_id: String::new(),
        };
        let mut body = serde_json::to_value(&manifest).expect("a manifest always serializes");
        body.as_object_mut().expect("object").remove("snapshot_id");
        manifest.snapshot_id = xxh64_digest(canonical_json(&body).as_bytes());
        manifest
    }
}

/// The bytes a manifest entry covers: the whole file, or the generated
/// regions joined by NUL so region boundaries count (`None` when the markers
/// are unbalanced).
pub fn covered_bytes(bytes: &[u8], scope: ArtifactScope) -> Option<Vec<u8>> {
    match scope {
        ArtifactScope::File => Some(bytes.to_vec()),
        ArtifactScope::GeneratedRegions => {
            let text = std::str::from_utf8(bytes).ok()?;
            generated_regions(text).map(|regions| regions.join("\0").into_bytes())
        }
    }
}

/// The text between each [`REGION_BEGIN`]/[`REGION_END`] pair, in order.
/// `None` when a marker is unpaired or nested.
pub fn generated_regions(text: &str) -> Option<Vec<&str>> {
    let mut regions = Vec::new();
    let mut rest = text;
    loop {
        let begin = rest.find(REGION_BEGIN);
        let end = rest.find(REGION_END);
        match (begin, end) {
            (None, None) => return Some(regions),
            (Some(begin), Some(end)) if begin < end => {
                let inner = &rest[begin + REGION_BEGIN.len()..end];
                if inner.contains(REGION_BEGIN) {
                    return None;
                }
                regions.push(inner);
                rest = &rest[end + REGION_END.len()..];
            }
            _ => return None,
        }
    }
}

/// Replaces the generated regions of `authored` with `regions`, keeping the
/// prose around them byte for byte. `None` when the region count differs or
/// the markers are malformed.
pub fn splice_regions(authored: &str, regions: &[String]) -> Option<String> {
    if generated_regions(authored)?.len() != regions.len() {
        return None;
    }
    let mut out = String::with_capacity(authored.len());
    let mut rest = authored;
    for region in regions {
        let begin = rest.find(REGION_BEGIN)? + REGION_BEGIN.len();
        let end = rest.find(REGION_END)?;
        out.push_str(&rest[..begin]);
        out.push_str(region);
        rest = &rest[end..];
    }
    out.push_str(rest);
    Some(out)
}

/// A named protocol step at which a test can inject an interruption.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Point {
    /// Lock held, nothing written.
    BeforeStaging,
    /// The first artifact is staged, the rest are not.
    DuringStaging,
    /// All bytes and backups staged; no journal yet.
    StagedNoJournal,
    /// Journal durable; no fixed path touched.
    BeforeSelection,
    /// After this many fixed paths were replaced (or restored).
    MidReplacement(usize),
    /// Every artifact replaced; manifest not yet replaced.
    BeforeManifest,
    /// Manifest replaced (selected); journal not yet removed.
    AfterSelection,
    /// Journal removed; staging not yet cleaned.
    BeforeCleanup,
}

impl std::fmt::Display for Point {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Point::MidReplacement(count) => write!(f, "MidReplacement({count})"),
            other => write!(f, "{other:?}"),
        }
    }
}

/// Publication options. `interrupt_at` exists for fault-injection tests: the
/// step returns [`PublishError::Interrupted`] and leaves disk as it is.
#[derive(Debug, Clone, Copy, Default)]
pub struct Options {
    pub retry: RetryPolicy,
    pub interrupt_at: Option<Point>,
}

impl Options {
    fn check(&self, point: Point) -> Result<(), PublishError> {
        match self.interrupt_at {
            Some(at) if at == point => Err(PublishError::Interrupted(point)),
            _ => Ok(()),
        }
    }
}

/// Publication and verified-read failures. Paths are repository-relative.
#[derive(Debug, thiserror::Error)]
pub enum PublishError {
    #[error("{context}: {source}")]
    Io {
        context: String,
        #[source]
        source: io::Error,
    },

    #[error("publication interrupted at {0} (fault injection)")]
    Interrupted(Point),

    #[error("another process holds the research publication lock")]
    Locked,

    #[error("no published research snapshot: {MANIFEST} does not exist")]
    NoSnapshot,

    #[error("{path} does not match the published snapshot: {reason}")]
    Inconsistent { path: String, reason: String },

    #[error("a research publication was interrupted; run `messenger research recover` first")]
    RecoveryRequired,

    #[error("corrupt publication state: {0}; restore the snapshot with `git checkout` of the research artifacts")]
    Corrupt(String),
}

fn io_err(context: impl Into<String>) -> impl FnOnce(io::Error) -> PublishError {
    let context = context.into();
    move |source| PublishError::Io { context, source }
}

/// What a publication changed at the fixed paths.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct PublishReport {
    pub replaced: usize,
    pub unchanged: usize,
    pub removed: usize,
}

/// What recovery did.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Recovery {
    /// No transaction was pending; leftovers (if any) were removed.
    Clean,
    RolledBack,
    RolledForward,
}

/// A snapshot whose every artifact matched the committed manifest.
#[derive(Debug, Clone)]
pub struct Verified {
    pub manifest: Manifest,
    pub manifest_bytes: Vec<u8>,
    /// Whole-file bytes by repository-relative path.
    pub files: BTreeMap<String, Vec<u8>>,
}

/// Reads the selected snapshot, or refuses it.
///
/// Reads the manifest, then every listed artifact into memory, and accepts
/// only when each covered byte range hashes to the manifest's value and the
/// schema version is supported. The returned bytes therefore equal exactly
/// one published snapshot even while a publication runs concurrently (that
/// read fails and may be retried). A pending journal alone is not a refusal.
///
/// ## Errors
///
/// [`PublishError::NoSnapshot`], [`PublishError::Inconsistent`],
/// [`PublishError::Corrupt`], or an I/O error.
pub fn read_verified(workspace: &Workspace) -> Result<Verified, PublishError> {
    let manifest_bytes = read_optional(&workspace.manifest())
        .map_err(io_err(format!("read {MANIFEST}")))?
        .ok_or(PublishError::NoSnapshot)?;
    let manifest = Manifest::parse(&manifest_bytes)?;
    if manifest.schema.version != SUPPORTED_SCHEMA_VERSION {
        return Err(PublishError::Inconsistent {
            path: MANIFEST.to_string(),
            reason: format!("unsupported schema version {}", manifest.schema.version),
        });
    }
    let mut files = BTreeMap::new();
    for entry in &manifest.artifacts {
        let bytes = read_optional(&resolve(workspace, &entry.path))
            .map_err(io_err(format!("read {}", entry.path)))?
            .ok_or_else(|| PublishError::Inconsistent {
                path: entry.path.clone(),
                reason: "missing".to_string(),
            })?;
        let covered = covered_bytes(&bytes, entry.scope).ok_or_else(|| PublishError::Inconsistent {
            path: entry.path.clone(),
            reason: "generated-region markers are malformed".to_string(),
        })?;
        if covered.len() as u64 != entry.len || xxh64_digest(&covered) != entry.xxh64 {
            let reason = match entry.scope {
                ArtifactScope::File => "content differs from the manifest",
                ArtifactScope::GeneratedRegions => "a generated region differs from the manifest",
            };
            return Err(PublishError::Inconsistent {
                path: entry.path.clone(),
                reason: reason.to_string(),
            });
        }
        files.insert(entry.path.clone(), bytes);
    }
    Ok(Verified {
        manifest,
        manifest_bytes,
        files,
    })
}

/// Whether a publication is pending recovery.
pub fn pending(workspace: &Workspace) -> bool {
    journal_path(workspace).exists()
}

fn resolve(workspace: &Workspace, path: &str) -> PathBuf {
    workspace.resolve(&RepoPath::from_portable(path))
}

fn under(root: &Path, path: &str) -> PathBuf {
    path.split('/').fold(root.to_path_buf(), |acc, segment| acc.join(segment))
}

fn state(workspace: &Workspace) -> PathBuf {
    workspace.state_dir().join("publication")
}

fn journal_path(workspace: &Workspace) -> PathBuf {
    state(workspace).join("journal.json")
}

fn tx_dir(workspace: &Workspace, txid: &str) -> PathBuf {
    state(workspace).join("tx").join(txid)
}

fn lock(workspace: &Workspace) -> Result<PublicationLock, PublishError> {
    PublicationLock::try_acquire(&state(workspace).join("lock")).map_err(|error| match error {
        LockError::Held => PublishError::Locked,
        LockError::Io(source) => PublishError::Io {
            context: "open the publication lock".to_string(),
            source,
        },
    })
}

fn hash_at(path: &Path, display: &str) -> Result<Option<String>, PublishError> {
    Ok(read_optional(path).map_err(io_err(format!("read {display}")))?.map(|bytes| xxh64_digest(&bytes)))
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Entry {
    path: String,
    old_xxh64: Option<String>,
    new_xxh64: Option<String>,
}

/// The only durable journal state is `prepared`: whether the transaction
/// committed is decided by the committed manifest, never by the journal.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Journal {
    format: String,
    txid: String,
    state: String,
    old_manifest_xxh64: Option<String>,
    new_manifest_xxh64: String,
    entries: Vec<Entry>,
}

impl Journal {
    fn parse(bytes: &[u8]) -> Result<Self, PublishError> {
        let journal: Journal =
            serde_json::from_slice(bytes).map_err(|error| PublishError::Corrupt(format!("journal: {error}")))?;
        if journal.format != JOURNAL_FORMAT || journal.state != "prepared" {
            return Err(PublishError::Corrupt("journal: unknown format or state".to_string()));
        }
        if journal.txid.is_empty() || journal.txid.contains(['/', '\\', '.']) {
            return Err(PublishError::Corrupt("journal: invalid transaction id".to_string()));
        }
        if journal.entries.iter().any(|entry| !is_portable(&entry.path)) {
            return Err(PublishError::Corrupt("journal: an entry is not a repository-relative path".to_string()));
        }
        Ok(journal)
    }
}

fn txid(new_manifest: &[u8]) -> String {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |elapsed| elapsed.as_nanos());
    let digest = xxh64_digest(new_manifest);
    format!("{}-{:x}-{nanos:x}", &digest[6..14], std::process::id())
}

/// Publishes `snapshot` to its fixed paths and selects it.
///
/// Artifacts whose bytes already match are left untouched (a failed
/// platform's carried-over document, or a republication of identical
/// content); artifacts listed by the previous manifest but absent from
/// `snapshot` are removed.
///
/// ## Errors
///
/// [`PublishError::Locked`] when another publisher runs,
/// [`PublishError::RecoveryRequired`] when a journal is pending, and I/O
/// errors. After an error the previous snapshot stays selected, or recovery
/// restores it.
pub fn publish(workspace: &Workspace, snapshot: &Snapshot, options: Options) -> Result<PublishReport, PublishError> {
    let _lock = lock(workspace)?;
    if pending(workspace) {
        return Err(PublishError::RecoveryRequired);
    }
    options.check(Point::BeforeStaging)?;

    let new_manifest = snapshot.manifest().to_bytes();
    let old_manifest = read_optional(&workspace.manifest()).map_err(io_err(format!("read {MANIFEST}")))?;
    let old_paths: Vec<String> = match &old_manifest {
        Some(bytes) => Manifest::parse(bytes)?.artifacts.into_iter().map(|entry| entry.path).collect(),
        None => Vec::new(),
    };
    let txid = txid(&new_manifest);
    let tx = tx_dir(workspace, &txid);

    for (index, (path, artifact)) in snapshot.artifacts.iter().enumerate() {
        write_durable(&under(&tx.join("new"), path), &artifact.bytes).map_err(io_err(format!("stage {path}")))?;
        if index == 0 {
            options.check(Point::DuringStaging)?;
        }
    }
    write_durable(&under(&tx.join("new"), MANIFEST), &new_manifest).map_err(io_err("stage the manifest"))?;

    let mut paths: Vec<String> = snapshot.artifacts.keys().cloned().collect();
    paths.extend(old_paths.into_iter().filter(|path| !snapshot.artifacts.contains_key(path)));
    paths.sort();
    paths.dedup();
    let mut entries = Vec::new();
    for path in paths.iter().map(String::as_str).chain(std::iter::once(MANIFEST)) {
        let current = read_optional(&resolve(workspace, path)).map_err(io_err(format!("read {path}")))?;
        if let Some(bytes) = &current {
            write_durable(&under(&tx.join("old"), path), bytes).map_err(io_err(format!("back up {path}")))?;
        }
        if path != MANIFEST {
            entries.push(Entry {
                path: path.to_string(),
                old_xxh64: current.as_deref().map(xxh64_digest),
                new_xxh64: snapshot.artifacts.get(path).map(|artifact| xxh64_digest(&artifact.bytes)),
            });
        }
    }
    sync_dir(&tx);
    options.check(Point::StagedNoJournal)?;

    let journal = Journal {
        format: JOURNAL_FORMAT.to_string(),
        txid: txid.clone(),
        state: "prepared".to_string(),
        old_manifest_xxh64: old_manifest.as_deref().map(xxh64_digest),
        new_manifest_xxh64: xxh64_digest(&new_manifest),
        entries,
    };
    let mut journal_bytes = serde_json::to_vec_pretty(&journal).expect("a journal always serializes");
    journal_bytes.push(b'\n');
    replace_file(&journal_path(workspace), &journal_bytes, &txid, options.retry).map_err(io_err("write the journal"))?;
    options.check(Point::BeforeSelection)?;

    let report = roll_forward(workspace, &journal, options)?;
    finish(workspace, &journal, options)?;
    Ok(report)
}

/// Applies staged bytes to every fixed path, then replaces the manifest last.
fn roll_forward(workspace: &Workspace, journal: &Journal, options: Options) -> Result<PublishReport, PublishError> {
    let tx = tx_dir(workspace, &journal.txid);
    let mut report = PublishReport::default();
    for (index, entry) in journal.entries.iter().enumerate() {
        let dest = resolve(workspace, &entry.path);
        match &entry.new_xxh64 {
            Some(new) if hash_at(&dest, &entry.path)?.as_ref() == Some(new) => report.unchanged += 1,
            Some(new) => {
                let bytes = staged(&under(&tx.join("new"), &entry.path), &entry.path, new)?;
                replace_file(&dest, &bytes, &journal.txid, options.retry)
                    .map_err(io_err(format!("replace {}", entry.path)))?;
                report.replaced += 1;
            }
            None => {
                remove_if_present(&dest, options.retry).map_err(io_err(format!("remove {}", entry.path)))?;
                report.removed += 1;
            }
        }
        options.check(Point::MidReplacement(index + 1))?;
    }
    options.check(Point::BeforeManifest)?;
    let manifest = workspace.manifest();
    if hash_at(&manifest, MANIFEST)?.as_ref() != Some(&journal.new_manifest_xxh64) {
        let bytes = staged(&under(&tx.join("new"), MANIFEST), MANIFEST, &journal.new_manifest_xxh64)?;
        replace_file(&manifest, &bytes, &journal.txid, options.retry).map_err(io_err(format!("replace {MANIFEST}")))?;
    }
    options.check(Point::AfterSelection)?;
    Ok(report)
}

/// Restores backups, or removes paths that did not exist, for every entry.
fn roll_back(workspace: &Workspace, journal: &Journal, options: Options) -> Result<(), PublishError> {
    let tx = tx_dir(workspace, &journal.txid);
    for (index, entry) in journal.entries.iter().enumerate() {
        let dest = resolve(workspace, &entry.path);
        match &entry.old_xxh64 {
            Some(old) if hash_at(&dest, &entry.path)?.as_ref() == Some(old) => {}
            Some(old) => {
                let bytes = staged(&under(&tx.join("old"), &entry.path), &entry.path, old)?;
                replace_file(&dest, &bytes, &journal.txid, options.retry)
                    .map_err(io_err(format!("restore {}", entry.path)))?;
            }
            None => remove_if_present(&dest, options.retry).map_err(io_err(format!("remove {}", entry.path)))?,
        }
        options.check(Point::MidReplacement(index + 1))?;
    }
    Ok(())
}

fn staged(path: &Path, display: &str, expected: &str) -> Result<Vec<u8>, PublishError> {
    let bytes = read_optional(path)
        .map_err(io_err(format!("read the staged copy of {display}")))?
        .ok_or_else(|| PublishError::Corrupt(format!("the staged copy of {display} is missing")))?;
    if xxh64_digest(&bytes) != expected {
        return Err(PublishError::Corrupt(format!("the staged copy of {display} does not match the journal")));
    }
    Ok(bytes)
}

/// Removes the journal (closing the transaction), then staging and temps.
fn finish(workspace: &Workspace, journal: &Journal, options: Options) -> Result<(), PublishError> {
    remove_if_present(&journal_path(workspace), options.retry).map_err(io_err("remove the journal"))?;
    sync_dir(&state(workspace));
    options.check(Point::BeforeCleanup)?;
    cleanup_leftovers(workspace, journal.entries.iter().map(|entry| entry.path.as_str()))
}

/// Removes every transaction directory and every `*.publish-tmp` beside the
/// given paths and the manifest. Only valid while no journal is pending.
fn cleanup_leftovers<'a>(workspace: &Workspace, paths: impl Iterator<Item = &'a str>) -> Result<(), PublishError> {
    let tx_root = state(workspace).join("tx");
    if tx_root.exists() {
        fs::remove_dir_all(&tx_root).map_err(io_err("remove publication staging"))?;
    }
    let mut dirs: Vec<PathBuf> = paths
        .chain(std::iter::once(MANIFEST))
        .filter_map(|path| resolve(workspace, path).parent().map(Path::to_path_buf))
        .collect();
    dirs.push(state(workspace));
    dirs.sort();
    dirs.dedup();
    for dir in dirs {
        let Ok(entries) = fs::read_dir(&dir) else { continue };
        for entry in entries.flatten() {
            if entry.file_name().to_string_lossy().ends_with(".publish-tmp") {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
    Ok(())
}

/// Completes or undoes an interrupted publication.
///
/// The committed manifest decides: equal to the journal's new manifest rolls
/// forward, equal to the old one (or absent when there was none) rolls back,
/// and anything else is refused as corrupt. Every step is hash-guarded, so
/// recovery interrupted part way is repaired by running it again.
///
/// ## Errors
///
/// [`PublishError::Locked`], [`PublishError::Corrupt`], or an I/O error.
pub fn recover(workspace: &Workspace, options: Options) -> Result<Recovery, PublishError> {
    let _lock = lock(workspace)?;
    let Some(bytes) = read_optional(&journal_path(workspace)).map_err(io_err("read the journal"))? else {
        let paths: Vec<String> = match read_optional(&workspace.manifest()).map_err(io_err(format!("read {MANIFEST}")))? {
            Some(bytes) => Manifest::parse(&bytes)
                .map(|manifest| manifest.artifacts.into_iter().map(|entry| entry.path).collect())
                .unwrap_or_default(),
            None => Vec::new(),
        };
        cleanup_leftovers(workspace, paths.iter().map(String::as_str))?;
        return Ok(Recovery::Clean);
    };
    let journal = Journal::parse(&bytes)?;
    let current = hash_at(&workspace.manifest(), MANIFEST)?;
    let outcome = if current.as_ref() == Some(&journal.new_manifest_xxh64) {
        roll_forward(workspace, &journal, options)?;
        Recovery::RolledForward
    } else if current == journal.old_manifest_xxh64 {
        roll_back(workspace, &journal, options)?;
        Recovery::RolledBack
    } else {
        return Err(PublishError::Corrupt(format!(
            "{MANIFEST} matches neither side of the pending journal"
        )));
    };
    finish(workspace, &journal, options)?;
    Ok(outcome)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn regions_are_extracted_and_spliced_without_touching_prose() {
        let authored = format!("# Title\n\nAuthored.\n\n{REGION_BEGIN}\nold table\n{REGION_END}\n\nMore prose.\n");
        assert_eq!(generated_regions(&authored).expect("balanced"), vec!["\nold table\n"]);
        let spliced = splice_regions(&authored, &["\nnew table\n".to_string()]).expect("splice");
        assert_eq!(
            spliced,
            format!("# Title\n\nAuthored.\n\n{REGION_BEGIN}\nnew table\n{REGION_END}\n\nMore prose.\n")
        );
        assert!(splice_regions(&authored, &[]).is_none(), "region count must match");
        assert!(generated_regions(&format!("{REGION_END}{REGION_BEGIN}")).is_none());
        assert!(generated_regions(&format!("{REGION_BEGIN}{REGION_BEGIN}{REGION_END}")).is_none());
        assert!(generated_regions(REGION_BEGIN).is_none());
    }

    #[test]
    fn region_scope_ignores_authored_prose_but_not_generated_text() {
        let a = format!("A\n{REGION_BEGIN}x{REGION_END}\n");
        let b = format!("B changed\n{REGION_BEGIN}x{REGION_END}\n");
        let c = format!("A\n{REGION_BEGIN}y{REGION_END}\n");
        let covered = |text: &str| covered_bytes(text.as_bytes(), ArtifactScope::GeneratedRegions);
        assert_eq!(covered(&a), covered(&b));
        assert_ne!(covered(&a), covered(&c));
        assert_ne!(covered_bytes(a.as_bytes(), ArtifactScope::File), covered_bytes(b.as_bytes(), ArtifactScope::File));
    }
}
